// <auto-generated>
/*
 * AIA Calculator API
 *
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Intermediate emissions calculation output for the Vineyard calculator
    /// </summary>
    public partial class PostVineyard200ResponseIntermediateInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostVineyard200ResponseIntermediateInner" /> class.
        /// </summary>
        /// <param name="id">Unique identifier for this Vineyard activity</param>
        /// <param name="scope1">scope1</param>
        /// <param name="scope2">scope2</param>
        /// <param name="scope3">scope3</param>
        /// <param name="carbonSequestration">Carbon sequestration, in tonnes-CO2e</param>
        /// <param name="intensities">intensities</param>
        /// <param name="net">net</param>
        [JsonConstructor]
        public PostVineyard200ResponseIntermediateInner(string id, PostVineyard200ResponseScope1 scope1, PostAquaculture200ResponseScope2 scope2, PostVineyard200ResponseScope3 scope3, decimal carbonSequestration, PostVineyard200ResponseIntermediateInnerIntensities intensities, PostAquaculture200ResponseNet net)
        {
            Id = id;
            Scope1 = scope1;
            Scope2 = scope2;
            Scope3 = scope3;
            CarbonSequestration = carbonSequestration;
            Intensities = intensities;
            Net = net;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Unique identifier for this Vineyard activity
        /// </summary>
        /// <value>Unique identifier for this Vineyard activity</value>
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Scope1
        /// </summary>
        [JsonPropertyName("scope1")]
        public PostVineyard200ResponseScope1 Scope1 { get; set; }

        /// <summary>
        /// Gets or Sets Scope2
        /// </summary>
        [JsonPropertyName("scope2")]
        public PostAquaculture200ResponseScope2 Scope2 { get; set; }

        /// <summary>
        /// Gets or Sets Scope3
        /// </summary>
        [JsonPropertyName("scope3")]
        public PostVineyard200ResponseScope3 Scope3 { get; set; }

        /// <summary>
        /// Carbon sequestration, in tonnes-CO2e
        /// </summary>
        /// <value>Carbon sequestration, in tonnes-CO2e</value>
        [JsonPropertyName("carbonSequestration")]
        public decimal CarbonSequestration { get; set; }

        /// <summary>
        /// Gets or Sets Intensities
        /// </summary>
        [JsonPropertyName("intensities")]
        public PostVineyard200ResponseIntermediateInnerIntensities Intensities { get; set; }

        /// <summary>
        /// Gets or Sets Net
        /// </summary>
        [JsonPropertyName("net")]
        public PostAquaculture200ResponseNet Net { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PostVineyard200ResponseIntermediateInner {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Scope1: ").Append(Scope1).Append("\n");
            sb.Append("  Scope2: ").Append(Scope2).Append("\n");
            sb.Append("  Scope3: ").Append(Scope3).Append("\n");
            sb.Append("  CarbonSequestration: ").Append(CarbonSequestration).Append("\n");
            sb.Append("  Intensities: ").Append(Intensities).Append("\n");
            sb.Append("  Net: ").Append(Net).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PostVineyard200ResponseIntermediateInner" />
    /// </summary>
    public class PostVineyard200ResponseIntermediateInnerJsonConverter : JsonConverter<PostVineyard200ResponseIntermediateInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="PostVineyard200ResponseIntermediateInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PostVineyard200ResponseIntermediateInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<PostVineyard200ResponseScope1?> scope1 = default;
            Option<PostAquaculture200ResponseScope2?> scope2 = default;
            Option<PostVineyard200ResponseScope3?> scope3 = default;
            Option<decimal?> carbonSequestration = default;
            Option<PostVineyard200ResponseIntermediateInnerIntensities?> intensities = default;
            Option<PostAquaculture200ResponseNet?> net = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "scope1":
                            scope1 = new Option<PostVineyard200ResponseScope1?>(JsonSerializer.Deserialize<PostVineyard200ResponseScope1>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "scope2":
                            scope2 = new Option<PostAquaculture200ResponseScope2?>(JsonSerializer.Deserialize<PostAquaculture200ResponseScope2>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "scope3":
                            scope3 = new Option<PostVineyard200ResponseScope3?>(JsonSerializer.Deserialize<PostVineyard200ResponseScope3>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "carbonSequestration":
                            carbonSequestration = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "intensities":
                            intensities = new Option<PostVineyard200ResponseIntermediateInnerIntensities?>(JsonSerializer.Deserialize<PostVineyard200ResponseIntermediateInnerIntensities>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "net":
                            net = new Option<PostAquaculture200ResponseNet?>(JsonSerializer.Deserialize<PostAquaculture200ResponseNet>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class PostVineyard200ResponseIntermediateInner.", nameof(id));

            if (!scope1.IsSet)
                throw new ArgumentException("Property is required for class PostVineyard200ResponseIntermediateInner.", nameof(scope1));

            if (!scope2.IsSet)
                throw new ArgumentException("Property is required for class PostVineyard200ResponseIntermediateInner.", nameof(scope2));

            if (!scope3.IsSet)
                throw new ArgumentException("Property is required for class PostVineyard200ResponseIntermediateInner.", nameof(scope3));

            if (!carbonSequestration.IsSet)
                throw new ArgumentException("Property is required for class PostVineyard200ResponseIntermediateInner.", nameof(carbonSequestration));

            if (!intensities.IsSet)
                throw new ArgumentException("Property is required for class PostVineyard200ResponseIntermediateInner.", nameof(intensities));

            if (!net.IsSet)
                throw new ArgumentException("Property is required for class PostVineyard200ResponseIntermediateInner.", nameof(net));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class PostVineyard200ResponseIntermediateInner.");

            if (scope1.IsSet && scope1.Value == null)
                throw new ArgumentNullException(nameof(scope1), "Property is not nullable for class PostVineyard200ResponseIntermediateInner.");

            if (scope2.IsSet && scope2.Value == null)
                throw new ArgumentNullException(nameof(scope2), "Property is not nullable for class PostVineyard200ResponseIntermediateInner.");

            if (scope3.IsSet && scope3.Value == null)
                throw new ArgumentNullException(nameof(scope3), "Property is not nullable for class PostVineyard200ResponseIntermediateInner.");

            if (carbonSequestration.IsSet && carbonSequestration.Value == null)
                throw new ArgumentNullException(nameof(carbonSequestration), "Property is not nullable for class PostVineyard200ResponseIntermediateInner.");

            if (intensities.IsSet && intensities.Value == null)
                throw new ArgumentNullException(nameof(intensities), "Property is not nullable for class PostVineyard200ResponseIntermediateInner.");

            if (net.IsSet && net.Value == null)
                throw new ArgumentNullException(nameof(net), "Property is not nullable for class PostVineyard200ResponseIntermediateInner.");

            return new PostVineyard200ResponseIntermediateInner(id.Value!, scope1.Value!, scope2.Value!, scope3.Value!, carbonSequestration.Value!.Value!, intensities.Value!, net.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="PostVineyard200ResponseIntermediateInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="postVineyard200ResponseIntermediateInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PostVineyard200ResponseIntermediateInner postVineyard200ResponseIntermediateInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, postVineyard200ResponseIntermediateInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PostVineyard200ResponseIntermediateInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="postVineyard200ResponseIntermediateInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PostVineyard200ResponseIntermediateInner postVineyard200ResponseIntermediateInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (postVineyard200ResponseIntermediateInner.Id == null)
                throw new ArgumentNullException(nameof(postVineyard200ResponseIntermediateInner.Id), "Property is required for class PostVineyard200ResponseIntermediateInner.");

            if (postVineyard200ResponseIntermediateInner.Scope1 == null)
                throw new ArgumentNullException(nameof(postVineyard200ResponseIntermediateInner.Scope1), "Property is required for class PostVineyard200ResponseIntermediateInner.");

            if (postVineyard200ResponseIntermediateInner.Scope2 == null)
                throw new ArgumentNullException(nameof(postVineyard200ResponseIntermediateInner.Scope2), "Property is required for class PostVineyard200ResponseIntermediateInner.");

            if (postVineyard200ResponseIntermediateInner.Scope3 == null)
                throw new ArgumentNullException(nameof(postVineyard200ResponseIntermediateInner.Scope3), "Property is required for class PostVineyard200ResponseIntermediateInner.");

            if (postVineyard200ResponseIntermediateInner.Intensities == null)
                throw new ArgumentNullException(nameof(postVineyard200ResponseIntermediateInner.Intensities), "Property is required for class PostVineyard200ResponseIntermediateInner.");

            if (postVineyard200ResponseIntermediateInner.Net == null)
                throw new ArgumentNullException(nameof(postVineyard200ResponseIntermediateInner.Net), "Property is required for class PostVineyard200ResponseIntermediateInner.");

            writer.WriteString("id", postVineyard200ResponseIntermediateInner.Id);

            writer.WritePropertyName("scope1");
            JsonSerializer.Serialize(writer, postVineyard200ResponseIntermediateInner.Scope1, jsonSerializerOptions);
            writer.WritePropertyName("scope2");
            JsonSerializer.Serialize(writer, postVineyard200ResponseIntermediateInner.Scope2, jsonSerializerOptions);
            writer.WritePropertyName("scope3");
            JsonSerializer.Serialize(writer, postVineyard200ResponseIntermediateInner.Scope3, jsonSerializerOptions);
            writer.WriteNumber("carbonSequestration", postVineyard200ResponseIntermediateInner.CarbonSequestration);

            writer.WritePropertyName("intensities");
            JsonSerializer.Serialize(writer, postVineyard200ResponseIntermediateInner.Intensities, jsonSerializerOptions);
            writer.WritePropertyName("net");
            JsonSerializer.Serialize(writer, postVineyard200ResponseIntermediateInner.Net, jsonSerializerOptions);
        }
    }
}
