// <auto-generated>
/*
 * AIA Calculator API
 *
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Input data required for processing a specific product
    /// </summary>
    public partial class PostProcessingRequestProductsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostProcessingRequestProductsInner" /> class.
        /// </summary>
        /// <param name="product">product</param>
        /// <param name="electricityRenewable">Percent of total electricity usage that is drawn from renewable sources, between 0 and 1. Unused if &#x60;electricitySource&#x60; is &#x60;Renewable&#x60;</param>
        /// <param name="electricityUse">Electricity use in KWh (kilowatt hours)</param>
        /// <param name="electricitySource">Source of electricity</param>
        /// <param name="fuel">fuel</param>
        /// <param name="refrigerants">Refrigerant type</param>
        /// <param name="fluidWaste">Amount of fluid waste, in kL (kilolitres)</param>
        /// <param name="solidWaste">solidWaste</param>
        /// <param name="purchasedCO2">Quantity of CO2 purchased, in kg CO2</param>
        /// <param name="id">Unique identifier for this activity</param>
        /// <param name="carbonOffsets">Carbon offsets purchased, in t CO2. Offsetting 2 t CO2 would be 2.0 (not -2.0)</param>
        [JsonConstructor]
        public PostProcessingRequestProductsInner(PostProcessingRequestProductsInnerProduct product, decimal electricityRenewable, decimal electricityUse, ElectricitySourceEnum electricitySource, PostAquacultureRequestEnterprisesInnerFuel fuel, List<PostHorticultureRequestCropsInnerRefrigerantsInner> refrigerants, List<PostAquacultureRequestEnterprisesInnerFluidWasteInner> fluidWaste, PostAquacultureRequestEnterprisesInnerSolidWaste solidWaste, decimal purchasedCO2, Option<string?> id = default, Option<decimal?> carbonOffsets = default)
        {
            Product = product;
            ElectricityRenewable = electricityRenewable;
            ElectricityUse = electricityUse;
            ElectricitySource = electricitySource;
            Fuel = fuel;
            Refrigerants = refrigerants;
            FluidWaste = fluidWaste;
            SolidWaste = solidWaste;
            PurchasedCO2 = purchasedCO2;
            IdOption = id;
            CarbonOffsetsOption = carbonOffsets;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Source of electricity
        /// </summary>
        /// <value>Source of electricity</value>
        public enum ElectricitySourceEnum
        {
            /// <summary>
            /// Enum StateGrid for value: State Grid
            /// </summary>
            StateGrid = 1,

            /// <summary>
            /// Enum Renewable for value: Renewable
            /// </summary>
            Renewable = 2
        }

        /// <summary>
        /// Returns a <see cref="ElectricitySourceEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ElectricitySourceEnum ElectricitySourceEnumFromString(string value)
        {
            if (value.Equals("State Grid"))
                return ElectricitySourceEnum.StateGrid;

            if (value.Equals("Renewable"))
                return ElectricitySourceEnum.Renewable;

            throw new NotImplementedException($"Could not convert value to type ElectricitySourceEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ElectricitySourceEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ElectricitySourceEnum? ElectricitySourceEnumFromStringOrDefault(string value)
        {
            if (value.Equals("State Grid"))
                return ElectricitySourceEnum.StateGrid;

            if (value.Equals("Renewable"))
                return ElectricitySourceEnum.Renewable;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ElectricitySourceEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ElectricitySourceEnumToJsonValue(ElectricitySourceEnum value)
        {
            if (value == ElectricitySourceEnum.StateGrid)
                return "State Grid";

            if (value == ElectricitySourceEnum.Renewable)
                return "Renewable";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Source of electricity
        /// </summary>
        /// <value>Source of electricity</value>
        [JsonPropertyName("electricitySource")]
        public ElectricitySourceEnum ElectricitySource { get; set; }

        /// <summary>
        /// Gets or Sets Product
        /// </summary>
        [JsonPropertyName("product")]
        public PostProcessingRequestProductsInnerProduct Product { get; set; }

        /// <summary>
        /// Percent of total electricity usage that is drawn from renewable sources, between 0 and 1. Unused if &#x60;electricitySource&#x60; is &#x60;Renewable&#x60;
        /// </summary>
        /// <value>Percent of total electricity usage that is drawn from renewable sources, between 0 and 1. Unused if &#x60;electricitySource&#x60; is &#x60;Renewable&#x60;</value>
        [JsonPropertyName("electricityRenewable")]
        public decimal ElectricityRenewable { get; set; }

        /// <summary>
        /// Electricity use in KWh (kilowatt hours)
        /// </summary>
        /// <value>Electricity use in KWh (kilowatt hours)</value>
        [JsonPropertyName("electricityUse")]
        public decimal ElectricityUse { get; set; }

        /// <summary>
        /// Gets or Sets Fuel
        /// </summary>
        [JsonPropertyName("fuel")]
        public PostAquacultureRequestEnterprisesInnerFuel Fuel { get; set; }

        /// <summary>
        /// Refrigerant type
        /// </summary>
        /// <value>Refrigerant type</value>
        [JsonPropertyName("refrigerants")]
        public List<PostHorticultureRequestCropsInnerRefrigerantsInner> Refrigerants { get; set; }

        /// <summary>
        /// Amount of fluid waste, in kL (kilolitres)
        /// </summary>
        /// <value>Amount of fluid waste, in kL (kilolitres)</value>
        [JsonPropertyName("fluidWaste")]
        public List<PostAquacultureRequestEnterprisesInnerFluidWasteInner> FluidWaste { get; set; }

        /// <summary>
        /// Gets or Sets SolidWaste
        /// </summary>
        [JsonPropertyName("solidWaste")]
        public PostAquacultureRequestEnterprisesInnerSolidWaste SolidWaste { get; set; }

        /// <summary>
        /// Quantity of CO2 purchased, in kg CO2
        /// </summary>
        /// <value>Quantity of CO2 purchased, in kg CO2</value>
        [JsonPropertyName("purchasedCO2")]
        public decimal PurchasedCO2 { get; set; }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdOption { get; private set; }

        /// <summary>
        /// Unique identifier for this activity
        /// </summary>
        /// <value>Unique identifier for this activity</value>
        [JsonPropertyName("id")]
        public string? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of CarbonOffsets
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> CarbonOffsetsOption { get; private set; }

        /// <summary>
        /// Carbon offsets purchased, in t CO2. Offsetting 2 t CO2 would be 2.0 (not -2.0)
        /// </summary>
        /// <value>Carbon offsets purchased, in t CO2. Offsetting 2 t CO2 would be 2.0 (not -2.0)</value>
        [JsonPropertyName("carbonOffsets")]
        public decimal? CarbonOffsets { get { return this.CarbonOffsetsOption; } set { this.CarbonOffsetsOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PostProcessingRequestProductsInner {\n");
            sb.Append("  Product: ").Append(Product).Append("\n");
            sb.Append("  ElectricityRenewable: ").Append(ElectricityRenewable).Append("\n");
            sb.Append("  ElectricityUse: ").Append(ElectricityUse).Append("\n");
            sb.Append("  ElectricitySource: ").Append(ElectricitySource).Append("\n");
            sb.Append("  Fuel: ").Append(Fuel).Append("\n");
            sb.Append("  Refrigerants: ").Append(Refrigerants).Append("\n");
            sb.Append("  FluidWaste: ").Append(FluidWaste).Append("\n");
            sb.Append("  SolidWaste: ").Append(SolidWaste).Append("\n");
            sb.Append("  PurchasedCO2: ").Append(PurchasedCO2).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  CarbonOffsets: ").Append(CarbonOffsets).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // ElectricityRenewable (decimal) maximum
            if (this.ElectricityRenewable > (decimal)1)
            {
                yield return new ValidationResult("Invalid value for ElectricityRenewable, must be a value less than or equal to 1.", new [] { "ElectricityRenewable" });
            }

            // ElectricityRenewable (decimal) minimum
            if (this.ElectricityRenewable < (decimal)0)
            {
                yield return new ValidationResult("Invalid value for ElectricityRenewable, must be a value greater than or equal to 0.", new [] { "ElectricityRenewable" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PostProcessingRequestProductsInner" />
    /// </summary>
    public class PostProcessingRequestProductsInnerJsonConverter : JsonConverter<PostProcessingRequestProductsInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="PostProcessingRequestProductsInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PostProcessingRequestProductsInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<PostProcessingRequestProductsInnerProduct?> product = default;
            Option<decimal?> electricityRenewable = default;
            Option<decimal?> electricityUse = default;
            Option<PostProcessingRequestProductsInner.ElectricitySourceEnum?> electricitySource = default;
            Option<PostAquacultureRequestEnterprisesInnerFuel?> fuel = default;
            Option<List<PostHorticultureRequestCropsInnerRefrigerantsInner>?> refrigerants = default;
            Option<List<PostAquacultureRequestEnterprisesInnerFluidWasteInner>?> fluidWaste = default;
            Option<PostAquacultureRequestEnterprisesInnerSolidWaste?> solidWaste = default;
            Option<decimal?> purchasedCO2 = default;
            Option<string?> id = default;
            Option<decimal?> carbonOffsets = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "product":
                            product = new Option<PostProcessingRequestProductsInnerProduct?>(JsonSerializer.Deserialize<PostProcessingRequestProductsInnerProduct>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "electricityRenewable":
                            electricityRenewable = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "electricityUse":
                            electricityUse = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "electricitySource":
                            string? electricitySourceRawValue = utf8JsonReader.GetString();
                            if (electricitySourceRawValue != null)
                                electricitySource = new Option<PostProcessingRequestProductsInner.ElectricitySourceEnum?>(PostProcessingRequestProductsInner.ElectricitySourceEnumFromStringOrDefault(electricitySourceRawValue));
                            break;
                        case "fuel":
                            fuel = new Option<PostAquacultureRequestEnterprisesInnerFuel?>(JsonSerializer.Deserialize<PostAquacultureRequestEnterprisesInnerFuel>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "refrigerants":
                            refrigerants = new Option<List<PostHorticultureRequestCropsInnerRefrigerantsInner>?>(JsonSerializer.Deserialize<List<PostHorticultureRequestCropsInnerRefrigerantsInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "fluidWaste":
                            fluidWaste = new Option<List<PostAquacultureRequestEnterprisesInnerFluidWasteInner>?>(JsonSerializer.Deserialize<List<PostAquacultureRequestEnterprisesInnerFluidWasteInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "solidWaste":
                            solidWaste = new Option<PostAquacultureRequestEnterprisesInnerSolidWaste?>(JsonSerializer.Deserialize<PostAquacultureRequestEnterprisesInnerSolidWaste>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "purchasedCO2":
                            purchasedCO2 = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "carbonOffsets":
                            carbonOffsets = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!product.IsSet)
                throw new ArgumentException("Property is required for class PostProcessingRequestProductsInner.", nameof(product));

            if (!electricityRenewable.IsSet)
                throw new ArgumentException("Property is required for class PostProcessingRequestProductsInner.", nameof(electricityRenewable));

            if (!electricityUse.IsSet)
                throw new ArgumentException("Property is required for class PostProcessingRequestProductsInner.", nameof(electricityUse));

            if (!electricitySource.IsSet)
                throw new ArgumentException("Property is required for class PostProcessingRequestProductsInner.", nameof(electricitySource));

            if (!fuel.IsSet)
                throw new ArgumentException("Property is required for class PostProcessingRequestProductsInner.", nameof(fuel));

            if (!refrigerants.IsSet)
                throw new ArgumentException("Property is required for class PostProcessingRequestProductsInner.", nameof(refrigerants));

            if (!fluidWaste.IsSet)
                throw new ArgumentException("Property is required for class PostProcessingRequestProductsInner.", nameof(fluidWaste));

            if (!solidWaste.IsSet)
                throw new ArgumentException("Property is required for class PostProcessingRequestProductsInner.", nameof(solidWaste));

            if (!purchasedCO2.IsSet)
                throw new ArgumentException("Property is required for class PostProcessingRequestProductsInner.", nameof(purchasedCO2));

            if (product.IsSet && product.Value == null)
                throw new ArgumentNullException(nameof(product), "Property is not nullable for class PostProcessingRequestProductsInner.");

            if (electricityRenewable.IsSet && electricityRenewable.Value == null)
                throw new ArgumentNullException(nameof(electricityRenewable), "Property is not nullable for class PostProcessingRequestProductsInner.");

            if (electricityUse.IsSet && electricityUse.Value == null)
                throw new ArgumentNullException(nameof(electricityUse), "Property is not nullable for class PostProcessingRequestProductsInner.");

            if (electricitySource.IsSet && electricitySource.Value == null)
                throw new ArgumentNullException(nameof(electricitySource), "Property is not nullable for class PostProcessingRequestProductsInner.");

            if (fuel.IsSet && fuel.Value == null)
                throw new ArgumentNullException(nameof(fuel), "Property is not nullable for class PostProcessingRequestProductsInner.");

            if (refrigerants.IsSet && refrigerants.Value == null)
                throw new ArgumentNullException(nameof(refrigerants), "Property is not nullable for class PostProcessingRequestProductsInner.");

            if (fluidWaste.IsSet && fluidWaste.Value == null)
                throw new ArgumentNullException(nameof(fluidWaste), "Property is not nullable for class PostProcessingRequestProductsInner.");

            if (solidWaste.IsSet && solidWaste.Value == null)
                throw new ArgumentNullException(nameof(solidWaste), "Property is not nullable for class PostProcessingRequestProductsInner.");

            if (purchasedCO2.IsSet && purchasedCO2.Value == null)
                throw new ArgumentNullException(nameof(purchasedCO2), "Property is not nullable for class PostProcessingRequestProductsInner.");

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class PostProcessingRequestProductsInner.");

            if (carbonOffsets.IsSet && carbonOffsets.Value == null)
                throw new ArgumentNullException(nameof(carbonOffsets), "Property is not nullable for class PostProcessingRequestProductsInner.");

            return new PostProcessingRequestProductsInner(product.Value!, electricityRenewable.Value!.Value!, electricityUse.Value!.Value!, electricitySource.Value!.Value!, fuel.Value!, refrigerants.Value!, fluidWaste.Value!, solidWaste.Value!, purchasedCO2.Value!.Value!, id, carbonOffsets);
        }

        /// <summary>
        /// Serializes a <see cref="PostProcessingRequestProductsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="postProcessingRequestProductsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PostProcessingRequestProductsInner postProcessingRequestProductsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, postProcessingRequestProductsInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PostProcessingRequestProductsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="postProcessingRequestProductsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PostProcessingRequestProductsInner postProcessingRequestProductsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (postProcessingRequestProductsInner.Product == null)
                throw new ArgumentNullException(nameof(postProcessingRequestProductsInner.Product), "Property is required for class PostProcessingRequestProductsInner.");

            if (postProcessingRequestProductsInner.Fuel == null)
                throw new ArgumentNullException(nameof(postProcessingRequestProductsInner.Fuel), "Property is required for class PostProcessingRequestProductsInner.");

            if (postProcessingRequestProductsInner.Refrigerants == null)
                throw new ArgumentNullException(nameof(postProcessingRequestProductsInner.Refrigerants), "Property is required for class PostProcessingRequestProductsInner.");

            if (postProcessingRequestProductsInner.FluidWaste == null)
                throw new ArgumentNullException(nameof(postProcessingRequestProductsInner.FluidWaste), "Property is required for class PostProcessingRequestProductsInner.");

            if (postProcessingRequestProductsInner.SolidWaste == null)
                throw new ArgumentNullException(nameof(postProcessingRequestProductsInner.SolidWaste), "Property is required for class PostProcessingRequestProductsInner.");

            if (postProcessingRequestProductsInner.IdOption.IsSet && postProcessingRequestProductsInner.Id == null)
                throw new ArgumentNullException(nameof(postProcessingRequestProductsInner.Id), "Property is required for class PostProcessingRequestProductsInner.");

            writer.WritePropertyName("product");
            JsonSerializer.Serialize(writer, postProcessingRequestProductsInner.Product, jsonSerializerOptions);
            writer.WriteNumber("electricityRenewable", postProcessingRequestProductsInner.ElectricityRenewable);

            writer.WriteNumber("electricityUse", postProcessingRequestProductsInner.ElectricityUse);

            var electricitySourceRawValue = PostProcessingRequestProductsInner.ElectricitySourceEnumToJsonValue(postProcessingRequestProductsInner.ElectricitySource);
            writer.WriteString("electricitySource", electricitySourceRawValue);
            writer.WritePropertyName("fuel");
            JsonSerializer.Serialize(writer, postProcessingRequestProductsInner.Fuel, jsonSerializerOptions);
            writer.WritePropertyName("refrigerants");
            JsonSerializer.Serialize(writer, postProcessingRequestProductsInner.Refrigerants, jsonSerializerOptions);
            writer.WritePropertyName("fluidWaste");
            JsonSerializer.Serialize(writer, postProcessingRequestProductsInner.FluidWaste, jsonSerializerOptions);
            writer.WritePropertyName("solidWaste");
            JsonSerializer.Serialize(writer, postProcessingRequestProductsInner.SolidWaste, jsonSerializerOptions);
            writer.WriteNumber("purchasedCO2", postProcessingRequestProductsInner.PurchasedCO2);

            if (postProcessingRequestProductsInner.IdOption.IsSet)
                writer.WriteString("id", postProcessingRequestProductsInner.Id);

            if (postProcessingRequestProductsInner.CarbonOffsetsOption.IsSet)
                writer.WriteNumber("carbonOffsets", postProcessingRequestProductsInner.CarbonOffsetsOption.Value!.Value);
        }
    }
}
