// <auto-generated>
/*
 * AIA Calculator API
 *
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Emissions calculation output for the Beef calculator
    /// </summary>
    public partial class PostBeef200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostBeef200Response" /> class.
        /// </summary>
        /// <param name="scope1">scope1</param>
        /// <param name="scope2">scope2</param>
        /// <param name="scope3">scope3</param>
        /// <param name="carbonSequestration">carbonSequestration</param>
        /// <param name="intermediate">intermediate</param>
        /// <param name="net">net</param>
        /// <param name="intensities">intensities</param>
        [JsonConstructor]
        public PostBeef200Response(PostBeef200ResponseScope1 scope1, PostAquaculture200ResponseScope2 scope2, PostBeef200ResponseScope3 scope3, PostAquaculture200ResponseCarbonSequestration carbonSequestration, List<PostBeef200ResponseIntermediateInner> intermediate, PostBeef200ResponseNet net, PostBeef200ResponseIntermediateInnerIntensities intensities)
        {
            Scope1 = scope1;
            Scope2 = scope2;
            Scope3 = scope3;
            CarbonSequestration = carbonSequestration;
            Intermediate = intermediate;
            Net = net;
            Intensities = intensities;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Scope1
        /// </summary>
        [JsonPropertyName("scope1")]
        public PostBeef200ResponseScope1 Scope1 { get; set; }

        /// <summary>
        /// Gets or Sets Scope2
        /// </summary>
        [JsonPropertyName("scope2")]
        public PostAquaculture200ResponseScope2 Scope2 { get; set; }

        /// <summary>
        /// Gets or Sets Scope3
        /// </summary>
        [JsonPropertyName("scope3")]
        public PostBeef200ResponseScope3 Scope3 { get; set; }

        /// <summary>
        /// Gets or Sets CarbonSequestration
        /// </summary>
        [JsonPropertyName("carbonSequestration")]
        public PostAquaculture200ResponseCarbonSequestration CarbonSequestration { get; set; }

        /// <summary>
        /// Gets or Sets Intermediate
        /// </summary>
        [JsonPropertyName("intermediate")]
        public List<PostBeef200ResponseIntermediateInner> Intermediate { get; set; }

        /// <summary>
        /// Gets or Sets Net
        /// </summary>
        [JsonPropertyName("net")]
        public PostBeef200ResponseNet Net { get; set; }

        /// <summary>
        /// Gets or Sets Intensities
        /// </summary>
        [JsonPropertyName("intensities")]
        public PostBeef200ResponseIntermediateInnerIntensities Intensities { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PostBeef200Response {\n");
            sb.Append("  Scope1: ").Append(Scope1).Append("\n");
            sb.Append("  Scope2: ").Append(Scope2).Append("\n");
            sb.Append("  Scope3: ").Append(Scope3).Append("\n");
            sb.Append("  CarbonSequestration: ").Append(CarbonSequestration).Append("\n");
            sb.Append("  Intermediate: ").Append(Intermediate).Append("\n");
            sb.Append("  Net: ").Append(Net).Append("\n");
            sb.Append("  Intensities: ").Append(Intensities).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PostBeef200Response" />
    /// </summary>
    public class PostBeef200ResponseJsonConverter : JsonConverter<PostBeef200Response>
    {
        /// <summary>
        /// Deserializes json to <see cref="PostBeef200Response" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PostBeef200Response Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<PostBeef200ResponseScope1?> scope1 = default;
            Option<PostAquaculture200ResponseScope2?> scope2 = default;
            Option<PostBeef200ResponseScope3?> scope3 = default;
            Option<PostAquaculture200ResponseCarbonSequestration?> carbonSequestration = default;
            Option<List<PostBeef200ResponseIntermediateInner>?> intermediate = default;
            Option<PostBeef200ResponseNet?> net = default;
            Option<PostBeef200ResponseIntermediateInnerIntensities?> intensities = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "scope1":
                            scope1 = new Option<PostBeef200ResponseScope1?>(JsonSerializer.Deserialize<PostBeef200ResponseScope1>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "scope2":
                            scope2 = new Option<PostAquaculture200ResponseScope2?>(JsonSerializer.Deserialize<PostAquaculture200ResponseScope2>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "scope3":
                            scope3 = new Option<PostBeef200ResponseScope3?>(JsonSerializer.Deserialize<PostBeef200ResponseScope3>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "carbonSequestration":
                            carbonSequestration = new Option<PostAquaculture200ResponseCarbonSequestration?>(JsonSerializer.Deserialize<PostAquaculture200ResponseCarbonSequestration>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "intermediate":
                            intermediate = new Option<List<PostBeef200ResponseIntermediateInner>?>(JsonSerializer.Deserialize<List<PostBeef200ResponseIntermediateInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "net":
                            net = new Option<PostBeef200ResponseNet?>(JsonSerializer.Deserialize<PostBeef200ResponseNet>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "intensities":
                            intensities = new Option<PostBeef200ResponseIntermediateInnerIntensities?>(JsonSerializer.Deserialize<PostBeef200ResponseIntermediateInnerIntensities>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!scope1.IsSet)
                throw new ArgumentException("Property is required for class PostBeef200Response.", nameof(scope1));

            if (!scope2.IsSet)
                throw new ArgumentException("Property is required for class PostBeef200Response.", nameof(scope2));

            if (!scope3.IsSet)
                throw new ArgumentException("Property is required for class PostBeef200Response.", nameof(scope3));

            if (!carbonSequestration.IsSet)
                throw new ArgumentException("Property is required for class PostBeef200Response.", nameof(carbonSequestration));

            if (!intermediate.IsSet)
                throw new ArgumentException("Property is required for class PostBeef200Response.", nameof(intermediate));

            if (!net.IsSet)
                throw new ArgumentException("Property is required for class PostBeef200Response.", nameof(net));

            if (!intensities.IsSet)
                throw new ArgumentException("Property is required for class PostBeef200Response.", nameof(intensities));

            if (scope1.IsSet && scope1.Value == null)
                throw new ArgumentNullException(nameof(scope1), "Property is not nullable for class PostBeef200Response.");

            if (scope2.IsSet && scope2.Value == null)
                throw new ArgumentNullException(nameof(scope2), "Property is not nullable for class PostBeef200Response.");

            if (scope3.IsSet && scope3.Value == null)
                throw new ArgumentNullException(nameof(scope3), "Property is not nullable for class PostBeef200Response.");

            if (carbonSequestration.IsSet && carbonSequestration.Value == null)
                throw new ArgumentNullException(nameof(carbonSequestration), "Property is not nullable for class PostBeef200Response.");

            if (intermediate.IsSet && intermediate.Value == null)
                throw new ArgumentNullException(nameof(intermediate), "Property is not nullable for class PostBeef200Response.");

            if (net.IsSet && net.Value == null)
                throw new ArgumentNullException(nameof(net), "Property is not nullable for class PostBeef200Response.");

            if (intensities.IsSet && intensities.Value == null)
                throw new ArgumentNullException(nameof(intensities), "Property is not nullable for class PostBeef200Response.");

            return new PostBeef200Response(scope1.Value!, scope2.Value!, scope3.Value!, carbonSequestration.Value!, intermediate.Value!, net.Value!, intensities.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="PostBeef200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="postBeef200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PostBeef200Response postBeef200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, postBeef200Response, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PostBeef200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="postBeef200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PostBeef200Response postBeef200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            if (postBeef200Response.Scope1 == null)
                throw new ArgumentNullException(nameof(postBeef200Response.Scope1), "Property is required for class PostBeef200Response.");

            if (postBeef200Response.Scope2 == null)
                throw new ArgumentNullException(nameof(postBeef200Response.Scope2), "Property is required for class PostBeef200Response.");

            if (postBeef200Response.Scope3 == null)
                throw new ArgumentNullException(nameof(postBeef200Response.Scope3), "Property is required for class PostBeef200Response.");

            if (postBeef200Response.CarbonSequestration == null)
                throw new ArgumentNullException(nameof(postBeef200Response.CarbonSequestration), "Property is required for class PostBeef200Response.");

            if (postBeef200Response.Intermediate == null)
                throw new ArgumentNullException(nameof(postBeef200Response.Intermediate), "Property is required for class PostBeef200Response.");

            if (postBeef200Response.Net == null)
                throw new ArgumentNullException(nameof(postBeef200Response.Net), "Property is required for class PostBeef200Response.");

            if (postBeef200Response.Intensities == null)
                throw new ArgumentNullException(nameof(postBeef200Response.Intensities), "Property is required for class PostBeef200Response.");

            writer.WritePropertyName("scope1");
            JsonSerializer.Serialize(writer, postBeef200Response.Scope1, jsonSerializerOptions);
            writer.WritePropertyName("scope2");
            JsonSerializer.Serialize(writer, postBeef200Response.Scope2, jsonSerializerOptions);
            writer.WritePropertyName("scope3");
            JsonSerializer.Serialize(writer, postBeef200Response.Scope3, jsonSerializerOptions);
            writer.WritePropertyName("carbonSequestration");
            JsonSerializer.Serialize(writer, postBeef200Response.CarbonSequestration, jsonSerializerOptions);
            writer.WritePropertyName("intermediate");
            JsonSerializer.Serialize(writer, postBeef200Response.Intermediate, jsonSerializerOptions);
            writer.WritePropertyName("net");
            JsonSerializer.Serialize(writer, postBeef200Response.Net, jsonSerializerOptions);
            writer.WritePropertyName("intensities");
            JsonSerializer.Serialize(writer, postBeef200Response.Intensities, jsonSerializerOptions);
        }
    }
}
