// <auto-generated>
/*
 * AIA Calculator API
 *
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// breeding does/nannies
    /// </summary>
    public partial class PostGoatRequestGoatsInnerClassesBreedingDoesNannies : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostGoatRequestGoatsInnerClassesBreedingDoesNannies" /> class.
        /// </summary>
        /// <param name="autumn">autumn</param>
        /// <param name="winter">winter</param>
        /// <param name="spring">spring</param>
        /// <param name="summer">summer</param>
        /// <param name="headSold">Number of animals sold (head)</param>
        /// <param name="saleWeight">Weight at sale, in liveweight kg/head (kilogram per head)</param>
        /// <param name="headShorn">Number of goat shorn, in head</param>
        /// <param name="woolShorn">Weight of wool shorn, in kg/head (kilogram per head)</param>
        /// <param name="cleanWoolYield">Percentage of clean wool from weight of yield, from 0 to 100</param>
        /// <param name="purchases">purchases</param>
        [JsonConstructor]
        public PostGoatRequestGoatsInnerClassesBreedingDoesNannies(PostBuffaloRequestBuffalosInnerClassesBullsAutumn autumn, PostBuffaloRequestBuffalosInnerClassesBullsAutumn winter, PostBuffaloRequestBuffalosInnerClassesBullsAutumn spring, PostBuffaloRequestBuffalosInnerClassesBullsAutumn summer, decimal headSold, decimal saleWeight, decimal headShorn, decimal woolShorn, decimal cleanWoolYield, Option<List<PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInner>?> purchases = default)
        {
            Autumn = autumn;
            Winter = winter;
            Spring = spring;
            Summer = summer;
            HeadSold = headSold;
            SaleWeight = saleWeight;
            HeadShorn = headShorn;
            WoolShorn = woolShorn;
            CleanWoolYield = cleanWoolYield;
            PurchasesOption = purchases;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Autumn
        /// </summary>
        [JsonPropertyName("autumn")]
        public PostBuffaloRequestBuffalosInnerClassesBullsAutumn Autumn { get; set; }

        /// <summary>
        /// Gets or Sets Winter
        /// </summary>
        [JsonPropertyName("winter")]
        public PostBuffaloRequestBuffalosInnerClassesBullsAutumn Winter { get; set; }

        /// <summary>
        /// Gets or Sets Spring
        /// </summary>
        [JsonPropertyName("spring")]
        public PostBuffaloRequestBuffalosInnerClassesBullsAutumn Spring { get; set; }

        /// <summary>
        /// Gets or Sets Summer
        /// </summary>
        [JsonPropertyName("summer")]
        public PostBuffaloRequestBuffalosInnerClassesBullsAutumn Summer { get; set; }

        /// <summary>
        /// Number of animals sold (head)
        /// </summary>
        /// <value>Number of animals sold (head)</value>
        [JsonPropertyName("headSold")]
        public decimal HeadSold { get; set; }

        /// <summary>
        /// Weight at sale, in liveweight kg/head (kilogram per head)
        /// </summary>
        /// <value>Weight at sale, in liveweight kg/head (kilogram per head)</value>
        [JsonPropertyName("saleWeight")]
        public decimal SaleWeight { get; set; }

        /// <summary>
        /// Number of goat shorn, in head
        /// </summary>
        /// <value>Number of goat shorn, in head</value>
        [JsonPropertyName("headShorn")]
        public decimal HeadShorn { get; set; }

        /// <summary>
        /// Weight of wool shorn, in kg/head (kilogram per head)
        /// </summary>
        /// <value>Weight of wool shorn, in kg/head (kilogram per head)</value>
        [JsonPropertyName("woolShorn")]
        public decimal WoolShorn { get; set; }

        /// <summary>
        /// Percentage of clean wool from weight of yield, from 0 to 100
        /// </summary>
        /// <value>Percentage of clean wool from weight of yield, from 0 to 100</value>
        [JsonPropertyName("cleanWoolYield")]
        public decimal CleanWoolYield { get; set; }

        /// <summary>
        /// Used to track the state of Purchases
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInner>?> PurchasesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Purchases
        /// </summary>
        [JsonPropertyName("purchases")]
        public List<PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInner>? Purchases { get { return this.PurchasesOption; } set { this.PurchasesOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PostGoatRequestGoatsInnerClassesBreedingDoesNannies {\n");
            sb.Append("  Autumn: ").Append(Autumn).Append("\n");
            sb.Append("  Winter: ").Append(Winter).Append("\n");
            sb.Append("  Spring: ").Append(Spring).Append("\n");
            sb.Append("  Summer: ").Append(Summer).Append("\n");
            sb.Append("  HeadSold: ").Append(HeadSold).Append("\n");
            sb.Append("  SaleWeight: ").Append(SaleWeight).Append("\n");
            sb.Append("  HeadShorn: ").Append(HeadShorn).Append("\n");
            sb.Append("  WoolShorn: ").Append(WoolShorn).Append("\n");
            sb.Append("  CleanWoolYield: ").Append(CleanWoolYield).Append("\n");
            sb.Append("  Purchases: ").Append(Purchases).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // HeadSold (decimal) minimum
            if (this.HeadSold < (decimal)0)
            {
                yield return new ValidationResult("Invalid value for HeadSold, must be a value greater than or equal to 0.", new [] { "HeadSold" });
            }

            // SaleWeight (decimal) minimum
            if (this.SaleWeight < (decimal)0)
            {
                yield return new ValidationResult("Invalid value for SaleWeight, must be a value greater than or equal to 0.", new [] { "SaleWeight" });
            }

            // HeadShorn (decimal) minimum
            if (this.HeadShorn < (decimal)0)
            {
                yield return new ValidationResult("Invalid value for HeadShorn, must be a value greater than or equal to 0.", new [] { "HeadShorn" });
            }

            // WoolShorn (decimal) minimum
            if (this.WoolShorn < (decimal)0)
            {
                yield return new ValidationResult("Invalid value for WoolShorn, must be a value greater than or equal to 0.", new [] { "WoolShorn" });
            }

            // CleanWoolYield (decimal) maximum
            if (this.CleanWoolYield > (decimal)100)
            {
                yield return new ValidationResult("Invalid value for CleanWoolYield, must be a value less than or equal to 100.", new [] { "CleanWoolYield" });
            }

            // CleanWoolYield (decimal) minimum
            if (this.CleanWoolYield < (decimal)0)
            {
                yield return new ValidationResult("Invalid value for CleanWoolYield, must be a value greater than or equal to 0.", new [] { "CleanWoolYield" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PostGoatRequestGoatsInnerClassesBreedingDoesNannies" />
    /// </summary>
    public class PostGoatRequestGoatsInnerClassesBreedingDoesNanniesJsonConverter : JsonConverter<PostGoatRequestGoatsInnerClassesBreedingDoesNannies>
    {
        /// <summary>
        /// Deserializes json to <see cref="PostGoatRequestGoatsInnerClassesBreedingDoesNannies" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PostGoatRequestGoatsInnerClassesBreedingDoesNannies Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<PostBuffaloRequestBuffalosInnerClassesBullsAutumn?> autumn = default;
            Option<PostBuffaloRequestBuffalosInnerClassesBullsAutumn?> winter = default;
            Option<PostBuffaloRequestBuffalosInnerClassesBullsAutumn?> spring = default;
            Option<PostBuffaloRequestBuffalosInnerClassesBullsAutumn?> summer = default;
            Option<decimal?> headSold = default;
            Option<decimal?> saleWeight = default;
            Option<decimal?> headShorn = default;
            Option<decimal?> woolShorn = default;
            Option<decimal?> cleanWoolYield = default;
            Option<List<PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInner>?> purchases = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "autumn":
                            autumn = new Option<PostBuffaloRequestBuffalosInnerClassesBullsAutumn?>(JsonSerializer.Deserialize<PostBuffaloRequestBuffalosInnerClassesBullsAutumn>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "winter":
                            winter = new Option<PostBuffaloRequestBuffalosInnerClassesBullsAutumn?>(JsonSerializer.Deserialize<PostBuffaloRequestBuffalosInnerClassesBullsAutumn>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "spring":
                            spring = new Option<PostBuffaloRequestBuffalosInnerClassesBullsAutumn?>(JsonSerializer.Deserialize<PostBuffaloRequestBuffalosInnerClassesBullsAutumn>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "summer":
                            summer = new Option<PostBuffaloRequestBuffalosInnerClassesBullsAutumn?>(JsonSerializer.Deserialize<PostBuffaloRequestBuffalosInnerClassesBullsAutumn>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "headSold":
                            headSold = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "saleWeight":
                            saleWeight = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "headShorn":
                            headShorn = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "woolShorn":
                            woolShorn = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "cleanWoolYield":
                            cleanWoolYield = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "purchases":
                            purchases = new Option<List<PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInner>?>(JsonSerializer.Deserialize<List<PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!autumn.IsSet)
                throw new ArgumentException("Property is required for class PostGoatRequestGoatsInnerClassesBreedingDoesNannies.", nameof(autumn));

            if (!winter.IsSet)
                throw new ArgumentException("Property is required for class PostGoatRequestGoatsInnerClassesBreedingDoesNannies.", nameof(winter));

            if (!spring.IsSet)
                throw new ArgumentException("Property is required for class PostGoatRequestGoatsInnerClassesBreedingDoesNannies.", nameof(spring));

            if (!summer.IsSet)
                throw new ArgumentException("Property is required for class PostGoatRequestGoatsInnerClassesBreedingDoesNannies.", nameof(summer));

            if (!headSold.IsSet)
                throw new ArgumentException("Property is required for class PostGoatRequestGoatsInnerClassesBreedingDoesNannies.", nameof(headSold));

            if (!saleWeight.IsSet)
                throw new ArgumentException("Property is required for class PostGoatRequestGoatsInnerClassesBreedingDoesNannies.", nameof(saleWeight));

            if (!headShorn.IsSet)
                throw new ArgumentException("Property is required for class PostGoatRequestGoatsInnerClassesBreedingDoesNannies.", nameof(headShorn));

            if (!woolShorn.IsSet)
                throw new ArgumentException("Property is required for class PostGoatRequestGoatsInnerClassesBreedingDoesNannies.", nameof(woolShorn));

            if (!cleanWoolYield.IsSet)
                throw new ArgumentException("Property is required for class PostGoatRequestGoatsInnerClassesBreedingDoesNannies.", nameof(cleanWoolYield));

            if (autumn.IsSet && autumn.Value == null)
                throw new ArgumentNullException(nameof(autumn), "Property is not nullable for class PostGoatRequestGoatsInnerClassesBreedingDoesNannies.");

            if (winter.IsSet && winter.Value == null)
                throw new ArgumentNullException(nameof(winter), "Property is not nullable for class PostGoatRequestGoatsInnerClassesBreedingDoesNannies.");

            if (spring.IsSet && spring.Value == null)
                throw new ArgumentNullException(nameof(spring), "Property is not nullable for class PostGoatRequestGoatsInnerClassesBreedingDoesNannies.");

            if (summer.IsSet && summer.Value == null)
                throw new ArgumentNullException(nameof(summer), "Property is not nullable for class PostGoatRequestGoatsInnerClassesBreedingDoesNannies.");

            if (headSold.IsSet && headSold.Value == null)
                throw new ArgumentNullException(nameof(headSold), "Property is not nullable for class PostGoatRequestGoatsInnerClassesBreedingDoesNannies.");

            if (saleWeight.IsSet && saleWeight.Value == null)
                throw new ArgumentNullException(nameof(saleWeight), "Property is not nullable for class PostGoatRequestGoatsInnerClassesBreedingDoesNannies.");

            if (headShorn.IsSet && headShorn.Value == null)
                throw new ArgumentNullException(nameof(headShorn), "Property is not nullable for class PostGoatRequestGoatsInnerClassesBreedingDoesNannies.");

            if (woolShorn.IsSet && woolShorn.Value == null)
                throw new ArgumentNullException(nameof(woolShorn), "Property is not nullable for class PostGoatRequestGoatsInnerClassesBreedingDoesNannies.");

            if (cleanWoolYield.IsSet && cleanWoolYield.Value == null)
                throw new ArgumentNullException(nameof(cleanWoolYield), "Property is not nullable for class PostGoatRequestGoatsInnerClassesBreedingDoesNannies.");

            if (purchases.IsSet && purchases.Value == null)
                throw new ArgumentNullException(nameof(purchases), "Property is not nullable for class PostGoatRequestGoatsInnerClassesBreedingDoesNannies.");

            return new PostGoatRequestGoatsInnerClassesBreedingDoesNannies(autumn.Value!, winter.Value!, spring.Value!, summer.Value!, headSold.Value!.Value!, saleWeight.Value!.Value!, headShorn.Value!.Value!, woolShorn.Value!.Value!, cleanWoolYield.Value!.Value!, purchases);
        }

        /// <summary>
        /// Serializes a <see cref="PostGoatRequestGoatsInnerClassesBreedingDoesNannies" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="postGoatRequestGoatsInnerClassesBreedingDoesNannies"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PostGoatRequestGoatsInnerClassesBreedingDoesNannies postGoatRequestGoatsInnerClassesBreedingDoesNannies, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, postGoatRequestGoatsInnerClassesBreedingDoesNannies, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PostGoatRequestGoatsInnerClassesBreedingDoesNannies" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="postGoatRequestGoatsInnerClassesBreedingDoesNannies"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PostGoatRequestGoatsInnerClassesBreedingDoesNannies postGoatRequestGoatsInnerClassesBreedingDoesNannies, JsonSerializerOptions jsonSerializerOptions)
        {
            if (postGoatRequestGoatsInnerClassesBreedingDoesNannies.Autumn == null)
                throw new ArgumentNullException(nameof(postGoatRequestGoatsInnerClassesBreedingDoesNannies.Autumn), "Property is required for class PostGoatRequestGoatsInnerClassesBreedingDoesNannies.");

            if (postGoatRequestGoatsInnerClassesBreedingDoesNannies.Winter == null)
                throw new ArgumentNullException(nameof(postGoatRequestGoatsInnerClassesBreedingDoesNannies.Winter), "Property is required for class PostGoatRequestGoatsInnerClassesBreedingDoesNannies.");

            if (postGoatRequestGoatsInnerClassesBreedingDoesNannies.Spring == null)
                throw new ArgumentNullException(nameof(postGoatRequestGoatsInnerClassesBreedingDoesNannies.Spring), "Property is required for class PostGoatRequestGoatsInnerClassesBreedingDoesNannies.");

            if (postGoatRequestGoatsInnerClassesBreedingDoesNannies.Summer == null)
                throw new ArgumentNullException(nameof(postGoatRequestGoatsInnerClassesBreedingDoesNannies.Summer), "Property is required for class PostGoatRequestGoatsInnerClassesBreedingDoesNannies.");

            if (postGoatRequestGoatsInnerClassesBreedingDoesNannies.PurchasesOption.IsSet && postGoatRequestGoatsInnerClassesBreedingDoesNannies.Purchases == null)
                throw new ArgumentNullException(nameof(postGoatRequestGoatsInnerClassesBreedingDoesNannies.Purchases), "Property is required for class PostGoatRequestGoatsInnerClassesBreedingDoesNannies.");

            writer.WritePropertyName("autumn");
            JsonSerializer.Serialize(writer, postGoatRequestGoatsInnerClassesBreedingDoesNannies.Autumn, jsonSerializerOptions);
            writer.WritePropertyName("winter");
            JsonSerializer.Serialize(writer, postGoatRequestGoatsInnerClassesBreedingDoesNannies.Winter, jsonSerializerOptions);
            writer.WritePropertyName("spring");
            JsonSerializer.Serialize(writer, postGoatRequestGoatsInnerClassesBreedingDoesNannies.Spring, jsonSerializerOptions);
            writer.WritePropertyName("summer");
            JsonSerializer.Serialize(writer, postGoatRequestGoatsInnerClassesBreedingDoesNannies.Summer, jsonSerializerOptions);
            writer.WriteNumber("headSold", postGoatRequestGoatsInnerClassesBreedingDoesNannies.HeadSold);

            writer.WriteNumber("saleWeight", postGoatRequestGoatsInnerClassesBreedingDoesNannies.SaleWeight);

            writer.WriteNumber("headShorn", postGoatRequestGoatsInnerClassesBreedingDoesNannies.HeadShorn);

            writer.WriteNumber("woolShorn", postGoatRequestGoatsInnerClassesBreedingDoesNannies.WoolShorn);

            writer.WriteNumber("cleanWoolYield", postGoatRequestGoatsInnerClassesBreedingDoesNannies.CleanWoolYield);

            if (postGoatRequestGoatsInnerClassesBreedingDoesNannies.PurchasesOption.IsSet)
            {
                writer.WritePropertyName("purchases");
                JsonSerializer.Serialize(writer, postGoatRequestGoatsInnerClassesBreedingDoesNannies.Purchases, jsonSerializerOptions);
            }
        }
    }
}
