// <auto-generated>
/*
 * AIA Calculator API
 *
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// PostRice200ResponseIntermediateInnerIntensities
    /// </summary>
    public partial class PostRice200ResponseIntermediateInnerIntensities : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostRice200ResponseIntermediateInnerIntensities" /> class.
        /// </summary>
        /// <param name="riceProducedTonnes">Rice produced in tonnes</param>
        /// <param name="riceExcludingSequestration">Rice emissions intensity excluding sequestration, in t-CO2e/t rice</param>
        /// <param name="riceIncludingSequestration">Rice emissions intensity including sequestration, in t-CO2e/t rice</param>
        [JsonConstructor]
        public PostRice200ResponseIntermediateInnerIntensities(decimal riceProducedTonnes, decimal riceExcludingSequestration, decimal riceIncludingSequestration)
        {
            RiceProducedTonnes = riceProducedTonnes;
            RiceExcludingSequestration = riceExcludingSequestration;
            RiceIncludingSequestration = riceIncludingSequestration;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Rice produced in tonnes
        /// </summary>
        /// <value>Rice produced in tonnes</value>
        [JsonPropertyName("riceProducedTonnes")]
        public decimal RiceProducedTonnes { get; set; }

        /// <summary>
        /// Rice emissions intensity excluding sequestration, in t-CO2e/t rice
        /// </summary>
        /// <value>Rice emissions intensity excluding sequestration, in t-CO2e/t rice</value>
        [JsonPropertyName("riceExcludingSequestration")]
        public decimal RiceExcludingSequestration { get; set; }

        /// <summary>
        /// Rice emissions intensity including sequestration, in t-CO2e/t rice
        /// </summary>
        /// <value>Rice emissions intensity including sequestration, in t-CO2e/t rice</value>
        [JsonPropertyName("riceIncludingSequestration")]
        public decimal RiceIncludingSequestration { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PostRice200ResponseIntermediateInnerIntensities {\n");
            sb.Append("  RiceProducedTonnes: ").Append(RiceProducedTonnes).Append("\n");
            sb.Append("  RiceExcludingSequestration: ").Append(RiceExcludingSequestration).Append("\n");
            sb.Append("  RiceIncludingSequestration: ").Append(RiceIncludingSequestration).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PostRice200ResponseIntermediateInnerIntensities" />
    /// </summary>
    public class PostRice200ResponseIntermediateInnerIntensitiesJsonConverter : JsonConverter<PostRice200ResponseIntermediateInnerIntensities>
    {
        /// <summary>
        /// Deserializes json to <see cref="PostRice200ResponseIntermediateInnerIntensities" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PostRice200ResponseIntermediateInnerIntensities Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<decimal?> riceProducedTonnes = default;
            Option<decimal?> riceExcludingSequestration = default;
            Option<decimal?> riceIncludingSequestration = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "riceProducedTonnes":
                            riceProducedTonnes = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "riceExcludingSequestration":
                            riceExcludingSequestration = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "riceIncludingSequestration":
                            riceIncludingSequestration = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!riceProducedTonnes.IsSet)
                throw new ArgumentException("Property is required for class PostRice200ResponseIntermediateInnerIntensities.", nameof(riceProducedTonnes));

            if (!riceExcludingSequestration.IsSet)
                throw new ArgumentException("Property is required for class PostRice200ResponseIntermediateInnerIntensities.", nameof(riceExcludingSequestration));

            if (!riceIncludingSequestration.IsSet)
                throw new ArgumentException("Property is required for class PostRice200ResponseIntermediateInnerIntensities.", nameof(riceIncludingSequestration));

            if (riceProducedTonnes.IsSet && riceProducedTonnes.Value == null)
                throw new ArgumentNullException(nameof(riceProducedTonnes), "Property is not nullable for class PostRice200ResponseIntermediateInnerIntensities.");

            if (riceExcludingSequestration.IsSet && riceExcludingSequestration.Value == null)
                throw new ArgumentNullException(nameof(riceExcludingSequestration), "Property is not nullable for class PostRice200ResponseIntermediateInnerIntensities.");

            if (riceIncludingSequestration.IsSet && riceIncludingSequestration.Value == null)
                throw new ArgumentNullException(nameof(riceIncludingSequestration), "Property is not nullable for class PostRice200ResponseIntermediateInnerIntensities.");

            return new PostRice200ResponseIntermediateInnerIntensities(riceProducedTonnes.Value!.Value!, riceExcludingSequestration.Value!.Value!, riceIncludingSequestration.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="PostRice200ResponseIntermediateInnerIntensities" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="postRice200ResponseIntermediateInnerIntensities"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PostRice200ResponseIntermediateInnerIntensities postRice200ResponseIntermediateInnerIntensities, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, postRice200ResponseIntermediateInnerIntensities, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PostRice200ResponseIntermediateInnerIntensities" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="postRice200ResponseIntermediateInnerIntensities"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PostRice200ResponseIntermediateInnerIntensities postRice200ResponseIntermediateInnerIntensities, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("riceProducedTonnes", postRice200ResponseIntermediateInnerIntensities.RiceProducedTonnes);

            writer.WriteNumber("riceExcludingSequestration", postRice200ResponseIntermediateInnerIntensities.RiceExcludingSequestration);

            writer.WriteNumber("riceIncludingSequestration", postRice200ResponseIntermediateInnerIntensities.RiceIncludingSequestration);
        }
    }
}
