// <auto-generated>
/*
 * AIA Calculator API
 *
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Input data required for a single Pork enterprise
    /// </summary>
    public partial class PostPorkRequestPorkInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostPorkRequestPorkInner" /> class.
        /// </summary>
        /// <param name="classes">classes</param>
        /// <param name="limestone">Lime applied in tonnes</param>
        /// <param name="limestoneFraction">Fraction of lime as limestone vs dolomite, between 0 and 1</param>
        /// <param name="fertiliser">fertiliser</param>
        /// <param name="diesel">Diesel usage in L (litres)</param>
        /// <param name="petrol">Petrol usage in L (litres)</param>
        /// <param name="lpg">LPG Fuel usage in L (litres)</param>
        /// <param name="electricitySource">Source of electricity</param>
        /// <param name="electricityRenewable">Percent of total electricity usage that is drawn from renewable sources, between 0 and 1. Unused if &#x60;electricitySource&#x60; is &#x60;Renewable&#x60;</param>
        /// <param name="electricityUse">Electricity use in KWh (kilowatt hours)</param>
        /// <param name="herbicide">Total amount of active ingredients of from herbicide (Paraquat, Diquat, Glyphosate) in kg (kilograms)</param>
        /// <param name="herbicideOther">Total amount of active ingredients of from other herbicides in kg (kilograms)</param>
        /// <param name="beddingHayBarleyStraw">Hay, barley, straw, etc. purchased for pig bedding, in tonnes</param>
        /// <param name="feedProducts">feedProducts</param>
        /// <param name="id">Unique identifier for this Pork activity</param>
        [JsonConstructor]
        public PostPorkRequestPorkInner(PostPorkRequestPorkInnerClasses classes, decimal limestone, decimal limestoneFraction, PostBeefRequestBeefInnerFertiliser fertiliser, decimal diesel, decimal petrol, decimal lpg, ElectricitySourceEnum electricitySource, decimal electricityRenewable, decimal electricityUse, decimal herbicide, decimal herbicideOther, decimal beddingHayBarleyStraw, List<PostPorkRequestPorkInnerFeedProductsInner> feedProducts, Option<string?> id = default)
        {
            Classes = classes;
            Limestone = limestone;
            LimestoneFraction = limestoneFraction;
            Fertiliser = fertiliser;
            Diesel = diesel;
            Petrol = petrol;
            Lpg = lpg;
            ElectricitySource = electricitySource;
            ElectricityRenewable = electricityRenewable;
            ElectricityUse = electricityUse;
            Herbicide = herbicide;
            HerbicideOther = herbicideOther;
            BeddingHayBarleyStraw = beddingHayBarleyStraw;
            FeedProducts = feedProducts;
            IdOption = id;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Source of electricity
        /// </summary>
        /// <value>Source of electricity</value>
        public enum ElectricitySourceEnum
        {
            /// <summary>
            /// Enum StateGrid for value: State Grid
            /// </summary>
            StateGrid = 1,

            /// <summary>
            /// Enum Renewable for value: Renewable
            /// </summary>
            Renewable = 2
        }

        /// <summary>
        /// Returns a <see cref="ElectricitySourceEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ElectricitySourceEnum ElectricitySourceEnumFromString(string value)
        {
            if (value.Equals("State Grid"))
                return ElectricitySourceEnum.StateGrid;

            if (value.Equals("Renewable"))
                return ElectricitySourceEnum.Renewable;

            throw new NotImplementedException($"Could not convert value to type ElectricitySourceEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ElectricitySourceEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ElectricitySourceEnum? ElectricitySourceEnumFromStringOrDefault(string value)
        {
            if (value.Equals("State Grid"))
                return ElectricitySourceEnum.StateGrid;

            if (value.Equals("Renewable"))
                return ElectricitySourceEnum.Renewable;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ElectricitySourceEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ElectricitySourceEnumToJsonValue(ElectricitySourceEnum value)
        {
            if (value == ElectricitySourceEnum.StateGrid)
                return "State Grid";

            if (value == ElectricitySourceEnum.Renewable)
                return "Renewable";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Source of electricity
        /// </summary>
        /// <value>Source of electricity</value>
        [JsonPropertyName("electricitySource")]
        public ElectricitySourceEnum ElectricitySource { get; set; }

        /// <summary>
        /// Gets or Sets Classes
        /// </summary>
        [JsonPropertyName("classes")]
        public PostPorkRequestPorkInnerClasses Classes { get; set; }

        /// <summary>
        /// Lime applied in tonnes
        /// </summary>
        /// <value>Lime applied in tonnes</value>
        [JsonPropertyName("limestone")]
        public decimal Limestone { get; set; }

        /// <summary>
        /// Fraction of lime as limestone vs dolomite, between 0 and 1
        /// </summary>
        /// <value>Fraction of lime as limestone vs dolomite, between 0 and 1</value>
        [JsonPropertyName("limestoneFraction")]
        public decimal LimestoneFraction { get; set; }

        /// <summary>
        /// Gets or Sets Fertiliser
        /// </summary>
        [JsonPropertyName("fertiliser")]
        public PostBeefRequestBeefInnerFertiliser Fertiliser { get; set; }

        /// <summary>
        /// Diesel usage in L (litres)
        /// </summary>
        /// <value>Diesel usage in L (litres)</value>
        [JsonPropertyName("diesel")]
        public decimal Diesel { get; set; }

        /// <summary>
        /// Petrol usage in L (litres)
        /// </summary>
        /// <value>Petrol usage in L (litres)</value>
        [JsonPropertyName("petrol")]
        public decimal Petrol { get; set; }

        /// <summary>
        /// LPG Fuel usage in L (litres)
        /// </summary>
        /// <value>LPG Fuel usage in L (litres)</value>
        [JsonPropertyName("lpg")]
        public decimal Lpg { get; set; }

        /// <summary>
        /// Percent of total electricity usage that is drawn from renewable sources, between 0 and 1. Unused if &#x60;electricitySource&#x60; is &#x60;Renewable&#x60;
        /// </summary>
        /// <value>Percent of total electricity usage that is drawn from renewable sources, between 0 and 1. Unused if &#x60;electricitySource&#x60; is &#x60;Renewable&#x60;</value>
        [JsonPropertyName("electricityRenewable")]
        public decimal ElectricityRenewable { get; set; }

        /// <summary>
        /// Electricity use in KWh (kilowatt hours)
        /// </summary>
        /// <value>Electricity use in KWh (kilowatt hours)</value>
        [JsonPropertyName("electricityUse")]
        public decimal ElectricityUse { get; set; }

        /// <summary>
        /// Total amount of active ingredients of from herbicide (Paraquat, Diquat, Glyphosate) in kg (kilograms)
        /// </summary>
        /// <value>Total amount of active ingredients of from herbicide (Paraquat, Diquat, Glyphosate) in kg (kilograms)</value>
        [JsonPropertyName("herbicide")]
        public decimal Herbicide { get; set; }

        /// <summary>
        /// Total amount of active ingredients of from other herbicides in kg (kilograms)
        /// </summary>
        /// <value>Total amount of active ingredients of from other herbicides in kg (kilograms)</value>
        [JsonPropertyName("herbicideOther")]
        public decimal HerbicideOther { get; set; }

        /// <summary>
        /// Hay, barley, straw, etc. purchased for pig bedding, in tonnes
        /// </summary>
        /// <value>Hay, barley, straw, etc. purchased for pig bedding, in tonnes</value>
        [JsonPropertyName("beddingHayBarleyStraw")]
        public decimal BeddingHayBarleyStraw { get; set; }

        /// <summary>
        /// Gets or Sets FeedProducts
        /// </summary>
        [JsonPropertyName("feedProducts")]
        public List<PostPorkRequestPorkInnerFeedProductsInner> FeedProducts { get; set; }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdOption { get; private set; }

        /// <summary>
        /// Unique identifier for this Pork activity
        /// </summary>
        /// <value>Unique identifier for this Pork activity</value>
        [JsonPropertyName("id")]
        public string? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PostPorkRequestPorkInner {\n");
            sb.Append("  Classes: ").Append(Classes).Append("\n");
            sb.Append("  Limestone: ").Append(Limestone).Append("\n");
            sb.Append("  LimestoneFraction: ").Append(LimestoneFraction).Append("\n");
            sb.Append("  Fertiliser: ").Append(Fertiliser).Append("\n");
            sb.Append("  Diesel: ").Append(Diesel).Append("\n");
            sb.Append("  Petrol: ").Append(Petrol).Append("\n");
            sb.Append("  Lpg: ").Append(Lpg).Append("\n");
            sb.Append("  ElectricitySource: ").Append(ElectricitySource).Append("\n");
            sb.Append("  ElectricityRenewable: ").Append(ElectricityRenewable).Append("\n");
            sb.Append("  ElectricityUse: ").Append(ElectricityUse).Append("\n");
            sb.Append("  Herbicide: ").Append(Herbicide).Append("\n");
            sb.Append("  HerbicideOther: ").Append(HerbicideOther).Append("\n");
            sb.Append("  BeddingHayBarleyStraw: ").Append(BeddingHayBarleyStraw).Append("\n");
            sb.Append("  FeedProducts: ").Append(FeedProducts).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // LimestoneFraction (decimal) maximum
            if (this.LimestoneFraction > (decimal)1)
            {
                yield return new ValidationResult("Invalid value for LimestoneFraction, must be a value less than or equal to 1.", new [] { "LimestoneFraction" });
            }

            // LimestoneFraction (decimal) minimum
            if (this.LimestoneFraction < (decimal)0)
            {
                yield return new ValidationResult("Invalid value for LimestoneFraction, must be a value greater than or equal to 0.", new [] { "LimestoneFraction" });
            }

            // ElectricityRenewable (decimal) maximum
            if (this.ElectricityRenewable > (decimal)1)
            {
                yield return new ValidationResult("Invalid value for ElectricityRenewable, must be a value less than or equal to 1.", new [] { "ElectricityRenewable" });
            }

            // ElectricityRenewable (decimal) minimum
            if (this.ElectricityRenewable < (decimal)0)
            {
                yield return new ValidationResult("Invalid value for ElectricityRenewable, must be a value greater than or equal to 0.", new [] { "ElectricityRenewable" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PostPorkRequestPorkInner" />
    /// </summary>
    public class PostPorkRequestPorkInnerJsonConverter : JsonConverter<PostPorkRequestPorkInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="PostPorkRequestPorkInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PostPorkRequestPorkInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<PostPorkRequestPorkInnerClasses?> classes = default;
            Option<decimal?> limestone = default;
            Option<decimal?> limestoneFraction = default;
            Option<PostBeefRequestBeefInnerFertiliser?> fertiliser = default;
            Option<decimal?> diesel = default;
            Option<decimal?> petrol = default;
            Option<decimal?> lpg = default;
            Option<PostPorkRequestPorkInner.ElectricitySourceEnum?> electricitySource = default;
            Option<decimal?> electricityRenewable = default;
            Option<decimal?> electricityUse = default;
            Option<decimal?> herbicide = default;
            Option<decimal?> herbicideOther = default;
            Option<decimal?> beddingHayBarleyStraw = default;
            Option<List<PostPorkRequestPorkInnerFeedProductsInner>?> feedProducts = default;
            Option<string?> id = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "classes":
                            classes = new Option<PostPorkRequestPorkInnerClasses?>(JsonSerializer.Deserialize<PostPorkRequestPorkInnerClasses>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "limestone":
                            limestone = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "limestoneFraction":
                            limestoneFraction = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "fertiliser":
                            fertiliser = new Option<PostBeefRequestBeefInnerFertiliser?>(JsonSerializer.Deserialize<PostBeefRequestBeefInnerFertiliser>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "diesel":
                            diesel = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "petrol":
                            petrol = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "lpg":
                            lpg = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "electricitySource":
                            string? electricitySourceRawValue = utf8JsonReader.GetString();
                            if (electricitySourceRawValue != null)
                                electricitySource = new Option<PostPorkRequestPorkInner.ElectricitySourceEnum?>(PostPorkRequestPorkInner.ElectricitySourceEnumFromStringOrDefault(electricitySourceRawValue));
                            break;
                        case "electricityRenewable":
                            electricityRenewable = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "electricityUse":
                            electricityUse = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "herbicide":
                            herbicide = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "herbicideOther":
                            herbicideOther = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "beddingHayBarleyStraw":
                            beddingHayBarleyStraw = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "feedProducts":
                            feedProducts = new Option<List<PostPorkRequestPorkInnerFeedProductsInner>?>(JsonSerializer.Deserialize<List<PostPorkRequestPorkInnerFeedProductsInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!classes.IsSet)
                throw new ArgumentException("Property is required for class PostPorkRequestPorkInner.", nameof(classes));

            if (!limestone.IsSet)
                throw new ArgumentException("Property is required for class PostPorkRequestPorkInner.", nameof(limestone));

            if (!limestoneFraction.IsSet)
                throw new ArgumentException("Property is required for class PostPorkRequestPorkInner.", nameof(limestoneFraction));

            if (!fertiliser.IsSet)
                throw new ArgumentException("Property is required for class PostPorkRequestPorkInner.", nameof(fertiliser));

            if (!diesel.IsSet)
                throw new ArgumentException("Property is required for class PostPorkRequestPorkInner.", nameof(diesel));

            if (!petrol.IsSet)
                throw new ArgumentException("Property is required for class PostPorkRequestPorkInner.", nameof(petrol));

            if (!lpg.IsSet)
                throw new ArgumentException("Property is required for class PostPorkRequestPorkInner.", nameof(lpg));

            if (!electricitySource.IsSet)
                throw new ArgumentException("Property is required for class PostPorkRequestPorkInner.", nameof(electricitySource));

            if (!electricityRenewable.IsSet)
                throw new ArgumentException("Property is required for class PostPorkRequestPorkInner.", nameof(electricityRenewable));

            if (!electricityUse.IsSet)
                throw new ArgumentException("Property is required for class PostPorkRequestPorkInner.", nameof(electricityUse));

            if (!herbicide.IsSet)
                throw new ArgumentException("Property is required for class PostPorkRequestPorkInner.", nameof(herbicide));

            if (!herbicideOther.IsSet)
                throw new ArgumentException("Property is required for class PostPorkRequestPorkInner.", nameof(herbicideOther));

            if (!beddingHayBarleyStraw.IsSet)
                throw new ArgumentException("Property is required for class PostPorkRequestPorkInner.", nameof(beddingHayBarleyStraw));

            if (!feedProducts.IsSet)
                throw new ArgumentException("Property is required for class PostPorkRequestPorkInner.", nameof(feedProducts));

            if (classes.IsSet && classes.Value == null)
                throw new ArgumentNullException(nameof(classes), "Property is not nullable for class PostPorkRequestPorkInner.");

            if (limestone.IsSet && limestone.Value == null)
                throw new ArgumentNullException(nameof(limestone), "Property is not nullable for class PostPorkRequestPorkInner.");

            if (limestoneFraction.IsSet && limestoneFraction.Value == null)
                throw new ArgumentNullException(nameof(limestoneFraction), "Property is not nullable for class PostPorkRequestPorkInner.");

            if (fertiliser.IsSet && fertiliser.Value == null)
                throw new ArgumentNullException(nameof(fertiliser), "Property is not nullable for class PostPorkRequestPorkInner.");

            if (diesel.IsSet && diesel.Value == null)
                throw new ArgumentNullException(nameof(diesel), "Property is not nullable for class PostPorkRequestPorkInner.");

            if (petrol.IsSet && petrol.Value == null)
                throw new ArgumentNullException(nameof(petrol), "Property is not nullable for class PostPorkRequestPorkInner.");

            if (lpg.IsSet && lpg.Value == null)
                throw new ArgumentNullException(nameof(lpg), "Property is not nullable for class PostPorkRequestPorkInner.");

            if (electricitySource.IsSet && electricitySource.Value == null)
                throw new ArgumentNullException(nameof(electricitySource), "Property is not nullable for class PostPorkRequestPorkInner.");

            if (electricityRenewable.IsSet && electricityRenewable.Value == null)
                throw new ArgumentNullException(nameof(electricityRenewable), "Property is not nullable for class PostPorkRequestPorkInner.");

            if (electricityUse.IsSet && electricityUse.Value == null)
                throw new ArgumentNullException(nameof(electricityUse), "Property is not nullable for class PostPorkRequestPorkInner.");

            if (herbicide.IsSet && herbicide.Value == null)
                throw new ArgumentNullException(nameof(herbicide), "Property is not nullable for class PostPorkRequestPorkInner.");

            if (herbicideOther.IsSet && herbicideOther.Value == null)
                throw new ArgumentNullException(nameof(herbicideOther), "Property is not nullable for class PostPorkRequestPorkInner.");

            if (beddingHayBarleyStraw.IsSet && beddingHayBarleyStraw.Value == null)
                throw new ArgumentNullException(nameof(beddingHayBarleyStraw), "Property is not nullable for class PostPorkRequestPorkInner.");

            if (feedProducts.IsSet && feedProducts.Value == null)
                throw new ArgumentNullException(nameof(feedProducts), "Property is not nullable for class PostPorkRequestPorkInner.");

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class PostPorkRequestPorkInner.");

            return new PostPorkRequestPorkInner(classes.Value!, limestone.Value!.Value!, limestoneFraction.Value!.Value!, fertiliser.Value!, diesel.Value!.Value!, petrol.Value!.Value!, lpg.Value!.Value!, electricitySource.Value!.Value!, electricityRenewable.Value!.Value!, electricityUse.Value!.Value!, herbicide.Value!.Value!, herbicideOther.Value!.Value!, beddingHayBarleyStraw.Value!.Value!, feedProducts.Value!, id);
        }

        /// <summary>
        /// Serializes a <see cref="PostPorkRequestPorkInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="postPorkRequestPorkInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PostPorkRequestPorkInner postPorkRequestPorkInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, postPorkRequestPorkInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PostPorkRequestPorkInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="postPorkRequestPorkInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PostPorkRequestPorkInner postPorkRequestPorkInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (postPorkRequestPorkInner.Classes == null)
                throw new ArgumentNullException(nameof(postPorkRequestPorkInner.Classes), "Property is required for class PostPorkRequestPorkInner.");

            if (postPorkRequestPorkInner.Fertiliser == null)
                throw new ArgumentNullException(nameof(postPorkRequestPorkInner.Fertiliser), "Property is required for class PostPorkRequestPorkInner.");

            if (postPorkRequestPorkInner.FeedProducts == null)
                throw new ArgumentNullException(nameof(postPorkRequestPorkInner.FeedProducts), "Property is required for class PostPorkRequestPorkInner.");

            if (postPorkRequestPorkInner.IdOption.IsSet && postPorkRequestPorkInner.Id == null)
                throw new ArgumentNullException(nameof(postPorkRequestPorkInner.Id), "Property is required for class PostPorkRequestPorkInner.");

            writer.WritePropertyName("classes");
            JsonSerializer.Serialize(writer, postPorkRequestPorkInner.Classes, jsonSerializerOptions);
            writer.WriteNumber("limestone", postPorkRequestPorkInner.Limestone);

            writer.WriteNumber("limestoneFraction", postPorkRequestPorkInner.LimestoneFraction);

            writer.WritePropertyName("fertiliser");
            JsonSerializer.Serialize(writer, postPorkRequestPorkInner.Fertiliser, jsonSerializerOptions);
            writer.WriteNumber("diesel", postPorkRequestPorkInner.Diesel);

            writer.WriteNumber("petrol", postPorkRequestPorkInner.Petrol);

            writer.WriteNumber("lpg", postPorkRequestPorkInner.Lpg);

            var electricitySourceRawValue = PostPorkRequestPorkInner.ElectricitySourceEnumToJsonValue(postPorkRequestPorkInner.ElectricitySource);
            writer.WriteString("electricitySource", electricitySourceRawValue);
            writer.WriteNumber("electricityRenewable", postPorkRequestPorkInner.ElectricityRenewable);

            writer.WriteNumber("electricityUse", postPorkRequestPorkInner.ElectricityUse);

            writer.WriteNumber("herbicide", postPorkRequestPorkInner.Herbicide);

            writer.WriteNumber("herbicideOther", postPorkRequestPorkInner.HerbicideOther);

            writer.WriteNumber("beddingHayBarleyStraw", postPorkRequestPorkInner.BeddingHayBarleyStraw);

            writer.WritePropertyName("feedProducts");
            JsonSerializer.Serialize(writer, postPorkRequestPorkInner.FeedProducts, jsonSerializerOptions);
            if (postPorkRequestPorkInner.IdOption.IsSet)
                writer.WriteString("id", postPorkRequestPorkInner.Id);
        }
    }
}
