// <auto-generated>
/*
 * AIA Calculator API
 *
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// PostWildseafisheriesRequestEnterprisesInnerRefrigerantsInner
    /// </summary>
    public partial class PostWildseafisheriesRequestEnterprisesInnerRefrigerantsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostWildseafisheriesRequestEnterprisesInnerRefrigerantsInner" /> class.
        /// </summary>
        /// <param name="refrigerant">Refrigerant type</param>
        /// <param name="annualRecharge">Amount of refrigerant annually recharged, kg product/year</param>
        [JsonConstructor]
        public PostWildseafisheriesRequestEnterprisesInnerRefrigerantsInner(RefrigerantEnum refrigerant, decimal annualRecharge)
        {
            Refrigerant = refrigerant;
            AnnualRecharge = annualRecharge;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Refrigerant type
        /// </summary>
        /// <value>Refrigerant type</value>
        public enum RefrigerantEnum
        {
            /// <summary>
            /// Enum HFC23 for value: HFC-23
            /// </summary>
            HFC23 = 1,

            /// <summary>
            /// Enum HFC32 for value: HFC-32
            /// </summary>
            HFC32 = 2,

            /// <summary>
            /// Enum HFC41 for value: HFC-41
            /// </summary>
            HFC41 = 3,

            /// <summary>
            /// Enum HFC4310mee for value: HFC-43-10mee
            /// </summary>
            HFC4310mee = 4,

            /// <summary>
            /// Enum HFC125 for value: HFC-125
            /// </summary>
            HFC125 = 5,

            /// <summary>
            /// Enum HFC134 for value: HFC-134
            /// </summary>
            HFC134 = 6,

            /// <summary>
            /// Enum HFC134a for value: HFC-134a
            /// </summary>
            HFC134a = 7,

            /// <summary>
            /// Enum HFC143 for value: HFC-143
            /// </summary>
            HFC143 = 8,

            /// <summary>
            /// Enum HFC143a for value: HFC-143a
            /// </summary>
            HFC143a = 9,

            /// <summary>
            /// Enum HFC152a for value: HFC-152a
            /// </summary>
            HFC152a = 10,

            /// <summary>
            /// Enum HFC227ea for value: HFC-227ea
            /// </summary>
            HFC227ea = 11,

            /// <summary>
            /// Enum HFC236fa for value: HFC-236fa
            /// </summary>
            HFC236fa = 12,

            /// <summary>
            /// Enum HFC245ca for value: HFC-245ca
            /// </summary>
            HFC245ca = 13,

            /// <summary>
            /// Enum HFC245fa for value: HFC-245fa
            /// </summary>
            HFC245fa = 14,

            /// <summary>
            /// Enum HFC365mfc for value: HFC-365mfc
            /// </summary>
            HFC365mfc = 15,

            /// <summary>
            /// Enum R438A for value: R438A
            /// </summary>
            R438A = 16,

            /// <summary>
            /// Enum R448A for value: R448A
            /// </summary>
            R448A = 17,

            /// <summary>
            /// Enum R22 for value: R-22
            /// </summary>
            R22 = 18,

            /// <summary>
            /// Enum AmmoniaR717 for value: Ammonia (R-717)
            /// </summary>
            AmmoniaR717 = 19,

            /// <summary>
            /// Enum R11 for value: R-11
            /// </summary>
            R11 = 20,

            /// <summary>
            /// Enum R12 for value: R-12
            /// </summary>
            R12 = 21,

            /// <summary>
            /// Enum R13 for value: R-13
            /// </summary>
            R13 = 22,

            /// <summary>
            /// Enum R23 for value: R-23
            /// </summary>
            R23 = 23,

            /// <summary>
            /// Enum R32 for value: R-32
            /// </summary>
            R32 = 24,

            /// <summary>
            /// Enum R113 for value: R-113
            /// </summary>
            R113 = 25,

            /// <summary>
            /// Enum R114 for value: R-114
            /// </summary>
            R114 = 26,

            /// <summary>
            /// Enum R115 for value: R-115
            /// </summary>
            R115 = 27,

            /// <summary>
            /// Enum R116 for value: R-116
            /// </summary>
            R116 = 28,

            /// <summary>
            /// Enum R123 for value: R-123
            /// </summary>
            R123 = 29,

            /// <summary>
            /// Enum R124 for value: R-124
            /// </summary>
            R124 = 30,

            /// <summary>
            /// Enum R125 for value: R-125
            /// </summary>
            R125 = 31,

            /// <summary>
            /// Enum R134a for value: R-134a
            /// </summary>
            R134a = 32,

            /// <summary>
            /// Enum R141b for value: R-141b
            /// </summary>
            R141b = 33,

            /// <summary>
            /// Enum R142b for value: R-142b
            /// </summary>
            R142b = 34,

            /// <summary>
            /// Enum R143a for value: R-143a
            /// </summary>
            R143a = 35,

            /// <summary>
            /// Enum R152a for value: R-152a
            /// </summary>
            R152a = 36,

            /// <summary>
            /// Enum R218 for value: R-218
            /// </summary>
            R218 = 37,

            /// <summary>
            /// Enum R227ea for value: R-227ea
            /// </summary>
            R227ea = 38,

            /// <summary>
            /// Enum R236fa for value: R-236fa
            /// </summary>
            R236fa = 39,

            /// <summary>
            /// Enum R245ca for value: R-245ca
            /// </summary>
            R245ca = 40,

            /// <summary>
            /// Enum R245fa for value: R-245fa
            /// </summary>
            R245fa = 41,

            /// <summary>
            /// Enum RC318 for value: R-C318
            /// </summary>
            RC318 = 42,

            /// <summary>
            /// Enum R401A for value: R-401A
            /// </summary>
            R401A = 43,

            /// <summary>
            /// Enum R401B for value: R-401B
            /// </summary>
            R401B = 44,

            /// <summary>
            /// Enum R401C for value: R-401C
            /// </summary>
            R401C = 45,

            /// <summary>
            /// Enum R402A for value: R-402A
            /// </summary>
            R402A = 46,

            /// <summary>
            /// Enum R402B for value: R-402B
            /// </summary>
            R402B = 47,

            /// <summary>
            /// Enum R403A for value: R-403A
            /// </summary>
            R403A = 48,

            /// <summary>
            /// Enum R403B for value: R-403B
            /// </summary>
            R403B = 49,

            /// <summary>
            /// Enum R404A for value: R-404A
            /// </summary>
            R404A = 50,

            /// <summary>
            /// Enum R405A for value: R-405A
            /// </summary>
            R405A = 51,

            /// <summary>
            /// Enum R406A for value: R-406A
            /// </summary>
            R406A = 52,

            /// <summary>
            /// Enum R407A for value: R-407A
            /// </summary>
            R407A = 53,

            /// <summary>
            /// Enum R407B for value: R-407B
            /// </summary>
            R407B = 54,

            /// <summary>
            /// Enum R407C for value: R-407C
            /// </summary>
            R407C = 55,

            /// <summary>
            /// Enum R407D for value: R-407D
            /// </summary>
            R407D = 56,

            /// <summary>
            /// Enum R407E for value: R-407E
            /// </summary>
            R407E = 57,

            /// <summary>
            /// Enum R408A for value: R-408A
            /// </summary>
            R408A = 58,

            /// <summary>
            /// Enum R409A for value: R-409A
            /// </summary>
            R409A = 59,

            /// <summary>
            /// Enum R409B for value: R-409B
            /// </summary>
            R409B = 60,

            /// <summary>
            /// Enum R410A for value: R-410A
            /// </summary>
            R410A = 61,

            /// <summary>
            /// Enum R411A for value: R-411A
            /// </summary>
            R411A = 62,

            /// <summary>
            /// Enum R411B for value: R-411B
            /// </summary>
            R411B = 63,

            /// <summary>
            /// Enum R412A for value: R-412A
            /// </summary>
            R412A = 64,

            /// <summary>
            /// Enum R413A for value: R-413A
            /// </summary>
            R413A = 65,

            /// <summary>
            /// Enum R414A for value: R-414A
            /// </summary>
            R414A = 66,

            /// <summary>
            /// Enum R414B for value: R-414B
            /// </summary>
            R414B = 67,

            /// <summary>
            /// Enum R415A for value: R-415A
            /// </summary>
            R415A = 68,

            /// <summary>
            /// Enum R415B for value: R-415B
            /// </summary>
            R415B = 69,

            /// <summary>
            /// Enum R416A for value: R-416A
            /// </summary>
            R416A = 70,

            /// <summary>
            /// Enum R417A for value: R-417A
            /// </summary>
            R417A = 71,

            /// <summary>
            /// Enum R418A for value: R-418A
            /// </summary>
            R418A = 72,

            /// <summary>
            /// Enum R419A for value: R-419A
            /// </summary>
            R419A = 73,

            /// <summary>
            /// Enum R420A for value: R-420A
            /// </summary>
            R420A = 74,

            /// <summary>
            /// Enum R421A for value: R-421A
            /// </summary>
            R421A = 75,

            /// <summary>
            /// Enum R421B for value: R-421B
            /// </summary>
            R421B = 76,

            /// <summary>
            /// Enum R422A for value: R-422A
            /// </summary>
            R422A = 77,

            /// <summary>
            /// Enum R422B for value: R-422B
            /// </summary>
            R422B = 78,

            /// <summary>
            /// Enum R422C for value: R-422C
            /// </summary>
            R422C = 79,

            /// <summary>
            /// Enum R422D for value: R-422D
            /// </summary>
            R422D = 80,

            /// <summary>
            /// Enum R423A for value: R-423A
            /// </summary>
            R423A = 81,

            /// <summary>
            /// Enum R424A for value: R-424A
            /// </summary>
            R424A = 82,

            /// <summary>
            /// Enum R425A for value: R-425A
            /// </summary>
            R425A = 83,

            /// <summary>
            /// Enum R426A for value: R-426A
            /// </summary>
            R426A = 84,

            /// <summary>
            /// Enum R427A for value: R-427A
            /// </summary>
            R427A = 85,

            /// <summary>
            /// Enum R428A for value: R-428A
            /// </summary>
            R428A = 86,

            /// <summary>
            /// Enum R500 for value: R-500
            /// </summary>
            R500 = 87,

            /// <summary>
            /// Enum R502 for value: R-502
            /// </summary>
            R502 = 88,

            /// <summary>
            /// Enum R503 for value: R-503
            /// </summary>
            R503 = 89,

            /// <summary>
            /// Enum R507A for value: R-507A
            /// </summary>
            R507A = 90,

            /// <summary>
            /// Enum R508A for value: R-508A
            /// </summary>
            R508A = 91,

            /// <summary>
            /// Enum R508B for value: R-508B
            /// </summary>
            R508B = 92,

            /// <summary>
            /// Enum R509A for value: R-509A
            /// </summary>
            R509A = 93
        }

        /// <summary>
        /// Returns a <see cref="RefrigerantEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static RefrigerantEnum RefrigerantEnumFromString(string value)
        {
            if (value.Equals("HFC-23"))
                return RefrigerantEnum.HFC23;

            if (value.Equals("HFC-32"))
                return RefrigerantEnum.HFC32;

            if (value.Equals("HFC-41"))
                return RefrigerantEnum.HFC41;

            if (value.Equals("HFC-43-10mee"))
                return RefrigerantEnum.HFC4310mee;

            if (value.Equals("HFC-125"))
                return RefrigerantEnum.HFC125;

            if (value.Equals("HFC-134"))
                return RefrigerantEnum.HFC134;

            if (value.Equals("HFC-134a"))
                return RefrigerantEnum.HFC134a;

            if (value.Equals("HFC-143"))
                return RefrigerantEnum.HFC143;

            if (value.Equals("HFC-143a"))
                return RefrigerantEnum.HFC143a;

            if (value.Equals("HFC-152a"))
                return RefrigerantEnum.HFC152a;

            if (value.Equals("HFC-227ea"))
                return RefrigerantEnum.HFC227ea;

            if (value.Equals("HFC-236fa"))
                return RefrigerantEnum.HFC236fa;

            if (value.Equals("HFC-245ca"))
                return RefrigerantEnum.HFC245ca;

            if (value.Equals("HFC-245fa"))
                return RefrigerantEnum.HFC245fa;

            if (value.Equals("HFC-365mfc"))
                return RefrigerantEnum.HFC365mfc;

            if (value.Equals("R438A"))
                return RefrigerantEnum.R438A;

            if (value.Equals("R448A"))
                return RefrigerantEnum.R448A;

            if (value.Equals("R-22"))
                return RefrigerantEnum.R22;

            if (value.Equals("Ammonia (R-717)"))
                return RefrigerantEnum.AmmoniaR717;

            if (value.Equals("R-11"))
                return RefrigerantEnum.R11;

            if (value.Equals("R-12"))
                return RefrigerantEnum.R12;

            if (value.Equals("R-13"))
                return RefrigerantEnum.R13;

            if (value.Equals("R-23"))
                return RefrigerantEnum.R23;

            if (value.Equals("R-32"))
                return RefrigerantEnum.R32;

            if (value.Equals("R-113"))
                return RefrigerantEnum.R113;

            if (value.Equals("R-114"))
                return RefrigerantEnum.R114;

            if (value.Equals("R-115"))
                return RefrigerantEnum.R115;

            if (value.Equals("R-116"))
                return RefrigerantEnum.R116;

            if (value.Equals("R-123"))
                return RefrigerantEnum.R123;

            if (value.Equals("R-124"))
                return RefrigerantEnum.R124;

            if (value.Equals("R-125"))
                return RefrigerantEnum.R125;

            if (value.Equals("R-134a"))
                return RefrigerantEnum.R134a;

            if (value.Equals("R-141b"))
                return RefrigerantEnum.R141b;

            if (value.Equals("R-142b"))
                return RefrigerantEnum.R142b;

            if (value.Equals("R-143a"))
                return RefrigerantEnum.R143a;

            if (value.Equals("R-152a"))
                return RefrigerantEnum.R152a;

            if (value.Equals("R-218"))
                return RefrigerantEnum.R218;

            if (value.Equals("R-227ea"))
                return RefrigerantEnum.R227ea;

            if (value.Equals("R-236fa"))
                return RefrigerantEnum.R236fa;

            if (value.Equals("R-245ca"))
                return RefrigerantEnum.R245ca;

            if (value.Equals("R-245fa"))
                return RefrigerantEnum.R245fa;

            if (value.Equals("R-C318"))
                return RefrigerantEnum.RC318;

            if (value.Equals("R-401A"))
                return RefrigerantEnum.R401A;

            if (value.Equals("R-401B"))
                return RefrigerantEnum.R401B;

            if (value.Equals("R-401C"))
                return RefrigerantEnum.R401C;

            if (value.Equals("R-402A"))
                return RefrigerantEnum.R402A;

            if (value.Equals("R-402B"))
                return RefrigerantEnum.R402B;

            if (value.Equals("R-403A"))
                return RefrigerantEnum.R403A;

            if (value.Equals("R-403B"))
                return RefrigerantEnum.R403B;

            if (value.Equals("R-404A"))
                return RefrigerantEnum.R404A;

            if (value.Equals("R-405A"))
                return RefrigerantEnum.R405A;

            if (value.Equals("R-406A"))
                return RefrigerantEnum.R406A;

            if (value.Equals("R-407A"))
                return RefrigerantEnum.R407A;

            if (value.Equals("R-407B"))
                return RefrigerantEnum.R407B;

            if (value.Equals("R-407C"))
                return RefrigerantEnum.R407C;

            if (value.Equals("R-407D"))
                return RefrigerantEnum.R407D;

            if (value.Equals("R-407E"))
                return RefrigerantEnum.R407E;

            if (value.Equals("R-408A"))
                return RefrigerantEnum.R408A;

            if (value.Equals("R-409A"))
                return RefrigerantEnum.R409A;

            if (value.Equals("R-409B"))
                return RefrigerantEnum.R409B;

            if (value.Equals("R-410A"))
                return RefrigerantEnum.R410A;

            if (value.Equals("R-411A"))
                return RefrigerantEnum.R411A;

            if (value.Equals("R-411B"))
                return RefrigerantEnum.R411B;

            if (value.Equals("R-412A"))
                return RefrigerantEnum.R412A;

            if (value.Equals("R-413A"))
                return RefrigerantEnum.R413A;

            if (value.Equals("R-414A"))
                return RefrigerantEnum.R414A;

            if (value.Equals("R-414B"))
                return RefrigerantEnum.R414B;

            if (value.Equals("R-415A"))
                return RefrigerantEnum.R415A;

            if (value.Equals("R-415B"))
                return RefrigerantEnum.R415B;

            if (value.Equals("R-416A"))
                return RefrigerantEnum.R416A;

            if (value.Equals("R-417A"))
                return RefrigerantEnum.R417A;

            if (value.Equals("R-418A"))
                return RefrigerantEnum.R418A;

            if (value.Equals("R-419A"))
                return RefrigerantEnum.R419A;

            if (value.Equals("R-420A"))
                return RefrigerantEnum.R420A;

            if (value.Equals("R-421A"))
                return RefrigerantEnum.R421A;

            if (value.Equals("R-421B"))
                return RefrigerantEnum.R421B;

            if (value.Equals("R-422A"))
                return RefrigerantEnum.R422A;

            if (value.Equals("R-422B"))
                return RefrigerantEnum.R422B;

            if (value.Equals("R-422C"))
                return RefrigerantEnum.R422C;

            if (value.Equals("R-422D"))
                return RefrigerantEnum.R422D;

            if (value.Equals("R-423A"))
                return RefrigerantEnum.R423A;

            if (value.Equals("R-424A"))
                return RefrigerantEnum.R424A;

            if (value.Equals("R-425A"))
                return RefrigerantEnum.R425A;

            if (value.Equals("R-426A"))
                return RefrigerantEnum.R426A;

            if (value.Equals("R-427A"))
                return RefrigerantEnum.R427A;

            if (value.Equals("R-428A"))
                return RefrigerantEnum.R428A;

            if (value.Equals("R-500"))
                return RefrigerantEnum.R500;

            if (value.Equals("R-502"))
                return RefrigerantEnum.R502;

            if (value.Equals("R-503"))
                return RefrigerantEnum.R503;

            if (value.Equals("R-507A"))
                return RefrigerantEnum.R507A;

            if (value.Equals("R-508A"))
                return RefrigerantEnum.R508A;

            if (value.Equals("R-508B"))
                return RefrigerantEnum.R508B;

            if (value.Equals("R-509A"))
                return RefrigerantEnum.R509A;

            throw new NotImplementedException($"Could not convert value to type RefrigerantEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="RefrigerantEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static RefrigerantEnum? RefrigerantEnumFromStringOrDefault(string value)
        {
            if (value.Equals("HFC-23"))
                return RefrigerantEnum.HFC23;

            if (value.Equals("HFC-32"))
                return RefrigerantEnum.HFC32;

            if (value.Equals("HFC-41"))
                return RefrigerantEnum.HFC41;

            if (value.Equals("HFC-43-10mee"))
                return RefrigerantEnum.HFC4310mee;

            if (value.Equals("HFC-125"))
                return RefrigerantEnum.HFC125;

            if (value.Equals("HFC-134"))
                return RefrigerantEnum.HFC134;

            if (value.Equals("HFC-134a"))
                return RefrigerantEnum.HFC134a;

            if (value.Equals("HFC-143"))
                return RefrigerantEnum.HFC143;

            if (value.Equals("HFC-143a"))
                return RefrigerantEnum.HFC143a;

            if (value.Equals("HFC-152a"))
                return RefrigerantEnum.HFC152a;

            if (value.Equals("HFC-227ea"))
                return RefrigerantEnum.HFC227ea;

            if (value.Equals("HFC-236fa"))
                return RefrigerantEnum.HFC236fa;

            if (value.Equals("HFC-245ca"))
                return RefrigerantEnum.HFC245ca;

            if (value.Equals("HFC-245fa"))
                return RefrigerantEnum.HFC245fa;

            if (value.Equals("HFC-365mfc"))
                return RefrigerantEnum.HFC365mfc;

            if (value.Equals("R438A"))
                return RefrigerantEnum.R438A;

            if (value.Equals("R448A"))
                return RefrigerantEnum.R448A;

            if (value.Equals("R-22"))
                return RefrigerantEnum.R22;

            if (value.Equals("Ammonia (R-717)"))
                return RefrigerantEnum.AmmoniaR717;

            if (value.Equals("R-11"))
                return RefrigerantEnum.R11;

            if (value.Equals("R-12"))
                return RefrigerantEnum.R12;

            if (value.Equals("R-13"))
                return RefrigerantEnum.R13;

            if (value.Equals("R-23"))
                return RefrigerantEnum.R23;

            if (value.Equals("R-32"))
                return RefrigerantEnum.R32;

            if (value.Equals("R-113"))
                return RefrigerantEnum.R113;

            if (value.Equals("R-114"))
                return RefrigerantEnum.R114;

            if (value.Equals("R-115"))
                return RefrigerantEnum.R115;

            if (value.Equals("R-116"))
                return RefrigerantEnum.R116;

            if (value.Equals("R-123"))
                return RefrigerantEnum.R123;

            if (value.Equals("R-124"))
                return RefrigerantEnum.R124;

            if (value.Equals("R-125"))
                return RefrigerantEnum.R125;

            if (value.Equals("R-134a"))
                return RefrigerantEnum.R134a;

            if (value.Equals("R-141b"))
                return RefrigerantEnum.R141b;

            if (value.Equals("R-142b"))
                return RefrigerantEnum.R142b;

            if (value.Equals("R-143a"))
                return RefrigerantEnum.R143a;

            if (value.Equals("R-152a"))
                return RefrigerantEnum.R152a;

            if (value.Equals("R-218"))
                return RefrigerantEnum.R218;

            if (value.Equals("R-227ea"))
                return RefrigerantEnum.R227ea;

            if (value.Equals("R-236fa"))
                return RefrigerantEnum.R236fa;

            if (value.Equals("R-245ca"))
                return RefrigerantEnum.R245ca;

            if (value.Equals("R-245fa"))
                return RefrigerantEnum.R245fa;

            if (value.Equals("R-C318"))
                return RefrigerantEnum.RC318;

            if (value.Equals("R-401A"))
                return RefrigerantEnum.R401A;

            if (value.Equals("R-401B"))
                return RefrigerantEnum.R401B;

            if (value.Equals("R-401C"))
                return RefrigerantEnum.R401C;

            if (value.Equals("R-402A"))
                return RefrigerantEnum.R402A;

            if (value.Equals("R-402B"))
                return RefrigerantEnum.R402B;

            if (value.Equals("R-403A"))
                return RefrigerantEnum.R403A;

            if (value.Equals("R-403B"))
                return RefrigerantEnum.R403B;

            if (value.Equals("R-404A"))
                return RefrigerantEnum.R404A;

            if (value.Equals("R-405A"))
                return RefrigerantEnum.R405A;

            if (value.Equals("R-406A"))
                return RefrigerantEnum.R406A;

            if (value.Equals("R-407A"))
                return RefrigerantEnum.R407A;

            if (value.Equals("R-407B"))
                return RefrigerantEnum.R407B;

            if (value.Equals("R-407C"))
                return RefrigerantEnum.R407C;

            if (value.Equals("R-407D"))
                return RefrigerantEnum.R407D;

            if (value.Equals("R-407E"))
                return RefrigerantEnum.R407E;

            if (value.Equals("R-408A"))
                return RefrigerantEnum.R408A;

            if (value.Equals("R-409A"))
                return RefrigerantEnum.R409A;

            if (value.Equals("R-409B"))
                return RefrigerantEnum.R409B;

            if (value.Equals("R-410A"))
                return RefrigerantEnum.R410A;

            if (value.Equals("R-411A"))
                return RefrigerantEnum.R411A;

            if (value.Equals("R-411B"))
                return RefrigerantEnum.R411B;

            if (value.Equals("R-412A"))
                return RefrigerantEnum.R412A;

            if (value.Equals("R-413A"))
                return RefrigerantEnum.R413A;

            if (value.Equals("R-414A"))
                return RefrigerantEnum.R414A;

            if (value.Equals("R-414B"))
                return RefrigerantEnum.R414B;

            if (value.Equals("R-415A"))
                return RefrigerantEnum.R415A;

            if (value.Equals("R-415B"))
                return RefrigerantEnum.R415B;

            if (value.Equals("R-416A"))
                return RefrigerantEnum.R416A;

            if (value.Equals("R-417A"))
                return RefrigerantEnum.R417A;

            if (value.Equals("R-418A"))
                return RefrigerantEnum.R418A;

            if (value.Equals("R-419A"))
                return RefrigerantEnum.R419A;

            if (value.Equals("R-420A"))
                return RefrigerantEnum.R420A;

            if (value.Equals("R-421A"))
                return RefrigerantEnum.R421A;

            if (value.Equals("R-421B"))
                return RefrigerantEnum.R421B;

            if (value.Equals("R-422A"))
                return RefrigerantEnum.R422A;

            if (value.Equals("R-422B"))
                return RefrigerantEnum.R422B;

            if (value.Equals("R-422C"))
                return RefrigerantEnum.R422C;

            if (value.Equals("R-422D"))
                return RefrigerantEnum.R422D;

            if (value.Equals("R-423A"))
                return RefrigerantEnum.R423A;

            if (value.Equals("R-424A"))
                return RefrigerantEnum.R424A;

            if (value.Equals("R-425A"))
                return RefrigerantEnum.R425A;

            if (value.Equals("R-426A"))
                return RefrigerantEnum.R426A;

            if (value.Equals("R-427A"))
                return RefrigerantEnum.R427A;

            if (value.Equals("R-428A"))
                return RefrigerantEnum.R428A;

            if (value.Equals("R-500"))
                return RefrigerantEnum.R500;

            if (value.Equals("R-502"))
                return RefrigerantEnum.R502;

            if (value.Equals("R-503"))
                return RefrigerantEnum.R503;

            if (value.Equals("R-507A"))
                return RefrigerantEnum.R507A;

            if (value.Equals("R-508A"))
                return RefrigerantEnum.R508A;

            if (value.Equals("R-508B"))
                return RefrigerantEnum.R508B;

            if (value.Equals("R-509A"))
                return RefrigerantEnum.R509A;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="RefrigerantEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string RefrigerantEnumToJsonValue(RefrigerantEnum value)
        {
            if (value == RefrigerantEnum.HFC23)
                return "HFC-23";

            if (value == RefrigerantEnum.HFC32)
                return "HFC-32";

            if (value == RefrigerantEnum.HFC41)
                return "HFC-41";

            if (value == RefrigerantEnum.HFC4310mee)
                return "HFC-43-10mee";

            if (value == RefrigerantEnum.HFC125)
                return "HFC-125";

            if (value == RefrigerantEnum.HFC134)
                return "HFC-134";

            if (value == RefrigerantEnum.HFC134a)
                return "HFC-134a";

            if (value == RefrigerantEnum.HFC143)
                return "HFC-143";

            if (value == RefrigerantEnum.HFC143a)
                return "HFC-143a";

            if (value == RefrigerantEnum.HFC152a)
                return "HFC-152a";

            if (value == RefrigerantEnum.HFC227ea)
                return "HFC-227ea";

            if (value == RefrigerantEnum.HFC236fa)
                return "HFC-236fa";

            if (value == RefrigerantEnum.HFC245ca)
                return "HFC-245ca";

            if (value == RefrigerantEnum.HFC245fa)
                return "HFC-245fa";

            if (value == RefrigerantEnum.HFC365mfc)
                return "HFC-365mfc";

            if (value == RefrigerantEnum.R438A)
                return "R438A";

            if (value == RefrigerantEnum.R448A)
                return "R448A";

            if (value == RefrigerantEnum.R22)
                return "R-22";

            if (value == RefrigerantEnum.AmmoniaR717)
                return "Ammonia (R-717)";

            if (value == RefrigerantEnum.R11)
                return "R-11";

            if (value == RefrigerantEnum.R12)
                return "R-12";

            if (value == RefrigerantEnum.R13)
                return "R-13";

            if (value == RefrigerantEnum.R23)
                return "R-23";

            if (value == RefrigerantEnum.R32)
                return "R-32";

            if (value == RefrigerantEnum.R113)
                return "R-113";

            if (value == RefrigerantEnum.R114)
                return "R-114";

            if (value == RefrigerantEnum.R115)
                return "R-115";

            if (value == RefrigerantEnum.R116)
                return "R-116";

            if (value == RefrigerantEnum.R123)
                return "R-123";

            if (value == RefrigerantEnum.R124)
                return "R-124";

            if (value == RefrigerantEnum.R125)
                return "R-125";

            if (value == RefrigerantEnum.R134a)
                return "R-134a";

            if (value == RefrigerantEnum.R141b)
                return "R-141b";

            if (value == RefrigerantEnum.R142b)
                return "R-142b";

            if (value == RefrigerantEnum.R143a)
                return "R-143a";

            if (value == RefrigerantEnum.R152a)
                return "R-152a";

            if (value == RefrigerantEnum.R218)
                return "R-218";

            if (value == RefrigerantEnum.R227ea)
                return "R-227ea";

            if (value == RefrigerantEnum.R236fa)
                return "R-236fa";

            if (value == RefrigerantEnum.R245ca)
                return "R-245ca";

            if (value == RefrigerantEnum.R245fa)
                return "R-245fa";

            if (value == RefrigerantEnum.RC318)
                return "R-C318";

            if (value == RefrigerantEnum.R401A)
                return "R-401A";

            if (value == RefrigerantEnum.R401B)
                return "R-401B";

            if (value == RefrigerantEnum.R401C)
                return "R-401C";

            if (value == RefrigerantEnum.R402A)
                return "R-402A";

            if (value == RefrigerantEnum.R402B)
                return "R-402B";

            if (value == RefrigerantEnum.R403A)
                return "R-403A";

            if (value == RefrigerantEnum.R403B)
                return "R-403B";

            if (value == RefrigerantEnum.R404A)
                return "R-404A";

            if (value == RefrigerantEnum.R405A)
                return "R-405A";

            if (value == RefrigerantEnum.R406A)
                return "R-406A";

            if (value == RefrigerantEnum.R407A)
                return "R-407A";

            if (value == RefrigerantEnum.R407B)
                return "R-407B";

            if (value == RefrigerantEnum.R407C)
                return "R-407C";

            if (value == RefrigerantEnum.R407D)
                return "R-407D";

            if (value == RefrigerantEnum.R407E)
                return "R-407E";

            if (value == RefrigerantEnum.R408A)
                return "R-408A";

            if (value == RefrigerantEnum.R409A)
                return "R-409A";

            if (value == RefrigerantEnum.R409B)
                return "R-409B";

            if (value == RefrigerantEnum.R410A)
                return "R-410A";

            if (value == RefrigerantEnum.R411A)
                return "R-411A";

            if (value == RefrigerantEnum.R411B)
                return "R-411B";

            if (value == RefrigerantEnum.R412A)
                return "R-412A";

            if (value == RefrigerantEnum.R413A)
                return "R-413A";

            if (value == RefrigerantEnum.R414A)
                return "R-414A";

            if (value == RefrigerantEnum.R414B)
                return "R-414B";

            if (value == RefrigerantEnum.R415A)
                return "R-415A";

            if (value == RefrigerantEnum.R415B)
                return "R-415B";

            if (value == RefrigerantEnum.R416A)
                return "R-416A";

            if (value == RefrigerantEnum.R417A)
                return "R-417A";

            if (value == RefrigerantEnum.R418A)
                return "R-418A";

            if (value == RefrigerantEnum.R419A)
                return "R-419A";

            if (value == RefrigerantEnum.R420A)
                return "R-420A";

            if (value == RefrigerantEnum.R421A)
                return "R-421A";

            if (value == RefrigerantEnum.R421B)
                return "R-421B";

            if (value == RefrigerantEnum.R422A)
                return "R-422A";

            if (value == RefrigerantEnum.R422B)
                return "R-422B";

            if (value == RefrigerantEnum.R422C)
                return "R-422C";

            if (value == RefrigerantEnum.R422D)
                return "R-422D";

            if (value == RefrigerantEnum.R423A)
                return "R-423A";

            if (value == RefrigerantEnum.R424A)
                return "R-424A";

            if (value == RefrigerantEnum.R425A)
                return "R-425A";

            if (value == RefrigerantEnum.R426A)
                return "R-426A";

            if (value == RefrigerantEnum.R427A)
                return "R-427A";

            if (value == RefrigerantEnum.R428A)
                return "R-428A";

            if (value == RefrigerantEnum.R500)
                return "R-500";

            if (value == RefrigerantEnum.R502)
                return "R-502";

            if (value == RefrigerantEnum.R503)
                return "R-503";

            if (value == RefrigerantEnum.R507A)
                return "R-507A";

            if (value == RefrigerantEnum.R508A)
                return "R-508A";

            if (value == RefrigerantEnum.R508B)
                return "R-508B";

            if (value == RefrigerantEnum.R509A)
                return "R-509A";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Refrigerant type
        /// </summary>
        /// <value>Refrigerant type</value>
        [JsonPropertyName("refrigerant")]
        public RefrigerantEnum Refrigerant { get; set; }

        /// <summary>
        /// Amount of refrigerant annually recharged, kg product/year
        /// </summary>
        /// <value>Amount of refrigerant annually recharged, kg product/year</value>
        [JsonPropertyName("annualRecharge")]
        public decimal AnnualRecharge { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PostWildseafisheriesRequestEnterprisesInnerRefrigerantsInner {\n");
            sb.Append("  Refrigerant: ").Append(Refrigerant).Append("\n");
            sb.Append("  AnnualRecharge: ").Append(AnnualRecharge).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PostWildseafisheriesRequestEnterprisesInnerRefrigerantsInner" />
    /// </summary>
    public class PostWildseafisheriesRequestEnterprisesInnerRefrigerantsInnerJsonConverter : JsonConverter<PostWildseafisheriesRequestEnterprisesInnerRefrigerantsInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="PostWildseafisheriesRequestEnterprisesInnerRefrigerantsInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PostWildseafisheriesRequestEnterprisesInnerRefrigerantsInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<PostWildseafisheriesRequestEnterprisesInnerRefrigerantsInner.RefrigerantEnum?> refrigerant = default;
            Option<decimal?> annualRecharge = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "refrigerant":
                            string? refrigerantRawValue = utf8JsonReader.GetString();
                            if (refrigerantRawValue != null)
                                refrigerant = new Option<PostWildseafisheriesRequestEnterprisesInnerRefrigerantsInner.RefrigerantEnum?>(PostWildseafisheriesRequestEnterprisesInnerRefrigerantsInner.RefrigerantEnumFromStringOrDefault(refrigerantRawValue));
                            break;
                        case "annualRecharge":
                            annualRecharge = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!refrigerant.IsSet)
                throw new ArgumentException("Property is required for class PostWildseafisheriesRequestEnterprisesInnerRefrigerantsInner.", nameof(refrigerant));

            if (!annualRecharge.IsSet)
                throw new ArgumentException("Property is required for class PostWildseafisheriesRequestEnterprisesInnerRefrigerantsInner.", nameof(annualRecharge));

            if (refrigerant.IsSet && refrigerant.Value == null)
                throw new ArgumentNullException(nameof(refrigerant), "Property is not nullable for class PostWildseafisheriesRequestEnterprisesInnerRefrigerantsInner.");

            if (annualRecharge.IsSet && annualRecharge.Value == null)
                throw new ArgumentNullException(nameof(annualRecharge), "Property is not nullable for class PostWildseafisheriesRequestEnterprisesInnerRefrigerantsInner.");

            return new PostWildseafisheriesRequestEnterprisesInnerRefrigerantsInner(refrigerant.Value!.Value!, annualRecharge.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="PostWildseafisheriesRequestEnterprisesInnerRefrigerantsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="postWildseafisheriesRequestEnterprisesInnerRefrigerantsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PostWildseafisheriesRequestEnterprisesInnerRefrigerantsInner postWildseafisheriesRequestEnterprisesInnerRefrigerantsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, postWildseafisheriesRequestEnterprisesInnerRefrigerantsInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PostWildseafisheriesRequestEnterprisesInnerRefrigerantsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="postWildseafisheriesRequestEnterprisesInnerRefrigerantsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PostWildseafisheriesRequestEnterprisesInnerRefrigerantsInner postWildseafisheriesRequestEnterprisesInnerRefrigerantsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            var refrigerantRawValue = PostWildseafisheriesRequestEnterprisesInnerRefrigerantsInner.RefrigerantEnumToJsonValue(postWildseafisheriesRequestEnterprisesInnerRefrigerantsInner.Refrigerant);
            writer.WriteString("refrigerant", refrigerantRawValue);
            writer.WriteNumber("annualRecharge", postWildseafisheriesRequestEnterprisesInnerRefrigerantsInner.AnnualRecharge);
        }
    }
}
