// <auto-generated>
/*
 * AIA Calculator API
 *
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Net emissions for each vineyard (in order)
    /// </summary>
    public partial class PostVineyard200ResponseNet : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostVineyard200ResponseNet" /> class.
        /// </summary>
        /// <param name="total">total</param>
        /// <param name="vineyards">vineyards</param>
        [JsonConstructor]
        public PostVineyard200ResponseNet(decimal total, List<decimal> vineyards)
        {
            Total = total;
            Vineyards = vineyards;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Total
        /// </summary>
        [JsonPropertyName("total")]
        public decimal Total { get; set; }

        /// <summary>
        /// Gets or Sets Vineyards
        /// </summary>
        [JsonPropertyName("vineyards")]
        public List<decimal> Vineyards { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PostVineyard200ResponseNet {\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("  Vineyards: ").Append(Vineyards).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PostVineyard200ResponseNet" />
    /// </summary>
    public class PostVineyard200ResponseNetJsonConverter : JsonConverter<PostVineyard200ResponseNet>
    {
        /// <summary>
        /// Deserializes json to <see cref="PostVineyard200ResponseNet" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PostVineyard200ResponseNet Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<decimal?> total = default;
            Option<List<decimal>?> vineyards = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "total":
                            total = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "vineyards":
                            vineyards = new Option<List<decimal>?>(JsonSerializer.Deserialize<List<decimal>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!total.IsSet)
                throw new ArgumentException("Property is required for class PostVineyard200ResponseNet.", nameof(total));

            if (!vineyards.IsSet)
                throw new ArgumentException("Property is required for class PostVineyard200ResponseNet.", nameof(vineyards));

            if (total.IsSet && total.Value == null)
                throw new ArgumentNullException(nameof(total), "Property is not nullable for class PostVineyard200ResponseNet.");

            if (vineyards.IsSet && vineyards.Value == null)
                throw new ArgumentNullException(nameof(vineyards), "Property is not nullable for class PostVineyard200ResponseNet.");

            return new PostVineyard200ResponseNet(total.Value!.Value!, vineyards.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="PostVineyard200ResponseNet" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="postVineyard200ResponseNet"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PostVineyard200ResponseNet postVineyard200ResponseNet, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, postVineyard200ResponseNet, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PostVineyard200ResponseNet" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="postVineyard200ResponseNet"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PostVineyard200ResponseNet postVineyard200ResponseNet, JsonSerializerOptions jsonSerializerOptions)
        {
            if (postVineyard200ResponseNet.Vineyards == null)
                throw new ArgumentNullException(nameof(postVineyard200ResponseNet.Vineyards), "Property is required for class PostVineyard200ResponseNet.");

            writer.WriteNumber("total", postVineyard200ResponseNet.Total);

            writer.WritePropertyName("vineyards");
            JsonSerializer.Serialize(writer, postVineyard200ResponseNet.Vineyards, jsonSerializerOptions);
        }
    }
}
