<?php
/**
 * PostPoultryRequestBroilersInnerGroupsInnerMeatChickenGrowers
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AIA Calculator API
 *
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PostPoultryRequestBroilersInnerGroupsInnerMeatChickenGrowers Class Doc Comment
 *
 * @category Class
 * @description Broiler class with seasonal data
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PostPoultryRequestBroilersInnerGroupsInnerMeatChickenGrowers implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'post_poultry_request_broilers_inner_groups_inner_meatChickenGrowers';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'birds' => 'float',
        'average_stay_length50' => 'float',
        'liveweight50' => 'float',
        'average_stay_length100' => 'float',
        'liveweight100' => 'float',
        'dry_matter_intake' => 'float',
        'dry_matter_digestibility' => 'float',
        'crude_protein' => 'float',
        'manure_ash' => 'float',
        'nitrogen_retention_rate' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'birds' => null,
        'average_stay_length50' => null,
        'liveweight50' => null,
        'average_stay_length100' => null,
        'liveweight100' => null,
        'dry_matter_intake' => null,
        'dry_matter_digestibility' => null,
        'crude_protein' => null,
        'manure_ash' => null,
        'nitrogen_retention_rate' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'birds' => false,
        'average_stay_length50' => false,
        'liveweight50' => false,
        'average_stay_length100' => false,
        'liveweight100' => false,
        'dry_matter_intake' => false,
        'dry_matter_digestibility' => false,
        'crude_protein' => false,
        'manure_ash' => false,
        'nitrogen_retention_rate' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'birds' => 'birds',
        'average_stay_length50' => 'averageStayLength50',
        'liveweight50' => 'liveweight50',
        'average_stay_length100' => 'averageStayLength100',
        'liveweight100' => 'liveweight100',
        'dry_matter_intake' => 'dryMatterIntake',
        'dry_matter_digestibility' => 'dryMatterDigestibility',
        'crude_protein' => 'crudeProtein',
        'manure_ash' => 'manureAsh',
        'nitrogen_retention_rate' => 'nitrogenRetentionRate'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'birds' => 'setBirds',
        'average_stay_length50' => 'setAverageStayLength50',
        'liveweight50' => 'setLiveweight50',
        'average_stay_length100' => 'setAverageStayLength100',
        'liveweight100' => 'setLiveweight100',
        'dry_matter_intake' => 'setDryMatterIntake',
        'dry_matter_digestibility' => 'setDryMatterDigestibility',
        'crude_protein' => 'setCrudeProtein',
        'manure_ash' => 'setManureAsh',
        'nitrogen_retention_rate' => 'setNitrogenRetentionRate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'birds' => 'getBirds',
        'average_stay_length50' => 'getAverageStayLength50',
        'liveweight50' => 'getLiveweight50',
        'average_stay_length100' => 'getAverageStayLength100',
        'liveweight100' => 'getLiveweight100',
        'dry_matter_intake' => 'getDryMatterIntake',
        'dry_matter_digestibility' => 'getDryMatterDigestibility',
        'crude_protein' => 'getCrudeProtein',
        'manure_ash' => 'getManureAsh',
        'nitrogen_retention_rate' => 'getNitrogenRetentionRate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('birds', $data ?? [], null);
        $this->setIfExists('average_stay_length50', $data ?? [], null);
        $this->setIfExists('liveweight50', $data ?? [], null);
        $this->setIfExists('average_stay_length100', $data ?? [], null);
        $this->setIfExists('liveweight100', $data ?? [], null);
        $this->setIfExists('dry_matter_intake', $data ?? [], null);
        $this->setIfExists('dry_matter_digestibility', $data ?? [], null);
        $this->setIfExists('crude_protein', $data ?? [], null);
        $this->setIfExists('manure_ash', $data ?? [], null);
        $this->setIfExists('nitrogen_retention_rate', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['birds'] === null) {
            $invalidProperties[] = "'birds' can't be null";
        }
        if ($this->container['average_stay_length50'] === null) {
            $invalidProperties[] = "'average_stay_length50' can't be null";
        }
        if ($this->container['liveweight50'] === null) {
            $invalidProperties[] = "'liveweight50' can't be null";
        }
        if ($this->container['average_stay_length100'] === null) {
            $invalidProperties[] = "'average_stay_length100' can't be null";
        }
        if ($this->container['liveweight100'] === null) {
            $invalidProperties[] = "'liveweight100' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets birds
     *
     * @return float
     */
    public function getBirds()
    {
        return $this->container['birds'];
    }

    /**
     * Sets birds
     *
     * @param float $birds Total number of birds/head
     *
     * @return self
     */
    public function setBirds($birds)
    {
        if (is_null($birds)) {
            throw new \InvalidArgumentException('non-nullable birds cannot be null');
        }
        $this->container['birds'] = $birds;

        return $this;
    }

    /**
     * Gets average_stay_length50
     *
     * @return float
     */
    public function getAverageStayLength50()
    {
        return $this->container['average_stay_length50'];
    }

    /**
     * Sets average_stay_length50
     *
     * @param float $average_stay_length50 Average length of stay until 50% of the flock is depleted, in days
     *
     * @return self
     */
    public function setAverageStayLength50($average_stay_length50)
    {
        if (is_null($average_stay_length50)) {
            throw new \InvalidArgumentException('non-nullable average_stay_length50 cannot be null');
        }
        $this->container['average_stay_length50'] = $average_stay_length50;

        return $this;
    }

    /**
     * Gets liveweight50
     *
     * @return float
     */
    public function getLiveweight50()
    {
        return $this->container['liveweight50'];
    }

    /**
     * Sets liveweight50
     *
     * @param float $liveweight50 Average liveweight during the 50% depletion period, in kg
     *
     * @return self
     */
    public function setLiveweight50($liveweight50)
    {
        if (is_null($liveweight50)) {
            throw new \InvalidArgumentException('non-nullable liveweight50 cannot be null');
        }
        $this->container['liveweight50'] = $liveweight50;

        return $this;
    }

    /**
     * Gets average_stay_length100
     *
     * @return float
     */
    public function getAverageStayLength100()
    {
        return $this->container['average_stay_length100'];
    }

    /**
     * Sets average_stay_length100
     *
     * @param float $average_stay_length100 Average length of stay until 100% of the flock is depleted, in days
     *
     * @return self
     */
    public function setAverageStayLength100($average_stay_length100)
    {
        if (is_null($average_stay_length100)) {
            throw new \InvalidArgumentException('non-nullable average_stay_length100 cannot be null');
        }
        $this->container['average_stay_length100'] = $average_stay_length100;

        return $this;
    }

    /**
     * Gets liveweight100
     *
     * @return float
     */
    public function getLiveweight100()
    {
        return $this->container['liveweight100'];
    }

    /**
     * Sets liveweight100
     *
     * @param float $liveweight100 Average liveweight during the 100% depletion period, in kg
     *
     * @return self
     */
    public function setLiveweight100($liveweight100)
    {
        if (is_null($liveweight100)) {
            throw new \InvalidArgumentException('non-nullable liveweight100 cannot be null');
        }
        $this->container['liveweight100'] = $liveweight100;

        return $this;
    }

    /**
     * Gets dry_matter_intake
     *
     * @return float|null
     */
    public function getDryMatterIntake()
    {
        return $this->container['dry_matter_intake'];
    }

    /**
     * Sets dry_matter_intake
     *
     * @param float|null $dry_matter_intake Dry matter intake, in kg/head/day
     *
     * @return self
     */
    public function setDryMatterIntake($dry_matter_intake)
    {
        if (is_null($dry_matter_intake)) {
            throw new \InvalidArgumentException('non-nullable dry_matter_intake cannot be null');
        }
        $this->container['dry_matter_intake'] = $dry_matter_intake;

        return $this;
    }

    /**
     * Gets dry_matter_digestibility
     *
     * @return float|null
     */
    public function getDryMatterDigestibility()
    {
        return $this->container['dry_matter_digestibility'];
    }

    /**
     * Sets dry_matter_digestibility
     *
     * @param float|null $dry_matter_digestibility Dry matter digestibility fraction, from 0 to 1
     *
     * @return self
     */
    public function setDryMatterDigestibility($dry_matter_digestibility)
    {
        if (is_null($dry_matter_digestibility)) {
            throw new \InvalidArgumentException('non-nullable dry_matter_digestibility cannot be null');
        }
        $this->container['dry_matter_digestibility'] = $dry_matter_digestibility;

        return $this;
    }

    /**
     * Gets crude_protein
     *
     * @return float|null
     */
    public function getCrudeProtein()
    {
        return $this->container['crude_protein'];
    }

    /**
     * Sets crude_protein
     *
     * @param float|null $crude_protein Crude protein fraction, from 0 to 1
     *
     * @return self
     */
    public function setCrudeProtein($crude_protein)
    {
        if (is_null($crude_protein)) {
            throw new \InvalidArgumentException('non-nullable crude_protein cannot be null');
        }
        $this->container['crude_protein'] = $crude_protein;

        return $this;
    }

    /**
     * Gets manure_ash
     *
     * @return float|null
     */
    public function getManureAsh()
    {
        return $this->container['manure_ash'];
    }

    /**
     * Sets manure_ash
     *
     * @param float|null $manure_ash Manure ash fraction, from 0 to 1
     *
     * @return self
     */
    public function setManureAsh($manure_ash)
    {
        if (is_null($manure_ash)) {
            throw new \InvalidArgumentException('non-nullable manure_ash cannot be null');
        }
        $this->container['manure_ash'] = $manure_ash;

        return $this;
    }

    /**
     * Gets nitrogen_retention_rate
     *
     * @return float|null
     */
    public function getNitrogenRetentionRate()
    {
        return $this->container['nitrogen_retention_rate'];
    }

    /**
     * Sets nitrogen_retention_rate
     *
     * @param float|null $nitrogen_retention_rate Nitrogen retention rate fraction, from 0 to 1
     *
     * @return self
     */
    public function setNitrogenRetentionRate($nitrogen_retention_rate)
    {
        if (is_null($nitrogen_retention_rate)) {
            throw new \InvalidArgumentException('non-nullable nitrogen_retention_rate cannot be null');
        }
        $this->container['nitrogen_retention_rate'] = $nitrogen_retention_rate;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


