<?php
/**
 * PostSheepbeef200ResponseIntensities
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AIA Calculator API
 *
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PostSheepbeef200ResponseIntensities Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PostSheepbeef200ResponseIntensities implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'post_sheepbeef_200_response_intensities';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'beef_including_sequestration' => 'float',
        'beef_excluding_sequestration' => 'float',
        'liveweight_beef_produced_kg' => 'float',
        'wool_including_sequestration' => 'float',
        'wool_excluding_sequestration' => 'float',
        'sheep_meat_breeding_including_sequestration' => 'float',
        'sheep_meat_breeding_excluding_sequestration' => 'float',
        'wool_produced_kg' => 'float',
        'sheep_meat_produced_kg' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'beef_including_sequestration' => null,
        'beef_excluding_sequestration' => null,
        'liveweight_beef_produced_kg' => null,
        'wool_including_sequestration' => null,
        'wool_excluding_sequestration' => null,
        'sheep_meat_breeding_including_sequestration' => null,
        'sheep_meat_breeding_excluding_sequestration' => null,
        'wool_produced_kg' => null,
        'sheep_meat_produced_kg' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'beef_including_sequestration' => false,
        'beef_excluding_sequestration' => false,
        'liveweight_beef_produced_kg' => false,
        'wool_including_sequestration' => false,
        'wool_excluding_sequestration' => false,
        'sheep_meat_breeding_including_sequestration' => false,
        'sheep_meat_breeding_excluding_sequestration' => false,
        'wool_produced_kg' => false,
        'sheep_meat_produced_kg' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'beef_including_sequestration' => 'beefIncludingSequestration',
        'beef_excluding_sequestration' => 'beefExcludingSequestration',
        'liveweight_beef_produced_kg' => 'liveweightBeefProducedKg',
        'wool_including_sequestration' => 'woolIncludingSequestration',
        'wool_excluding_sequestration' => 'woolExcludingSequestration',
        'sheep_meat_breeding_including_sequestration' => 'sheepMeatBreedingIncludingSequestration',
        'sheep_meat_breeding_excluding_sequestration' => 'sheepMeatBreedingExcludingSequestration',
        'wool_produced_kg' => 'woolProducedKg',
        'sheep_meat_produced_kg' => 'sheepMeatProducedKg'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'beef_including_sequestration' => 'setBeefIncludingSequestration',
        'beef_excluding_sequestration' => 'setBeefExcludingSequestration',
        'liveweight_beef_produced_kg' => 'setLiveweightBeefProducedKg',
        'wool_including_sequestration' => 'setWoolIncludingSequestration',
        'wool_excluding_sequestration' => 'setWoolExcludingSequestration',
        'sheep_meat_breeding_including_sequestration' => 'setSheepMeatBreedingIncludingSequestration',
        'sheep_meat_breeding_excluding_sequestration' => 'setSheepMeatBreedingExcludingSequestration',
        'wool_produced_kg' => 'setWoolProducedKg',
        'sheep_meat_produced_kg' => 'setSheepMeatProducedKg'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'beef_including_sequestration' => 'getBeefIncludingSequestration',
        'beef_excluding_sequestration' => 'getBeefExcludingSequestration',
        'liveweight_beef_produced_kg' => 'getLiveweightBeefProducedKg',
        'wool_including_sequestration' => 'getWoolIncludingSequestration',
        'wool_excluding_sequestration' => 'getWoolExcludingSequestration',
        'sheep_meat_breeding_including_sequestration' => 'getSheepMeatBreedingIncludingSequestration',
        'sheep_meat_breeding_excluding_sequestration' => 'getSheepMeatBreedingExcludingSequestration',
        'wool_produced_kg' => 'getWoolProducedKg',
        'sheep_meat_produced_kg' => 'getSheepMeatProducedKg'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('beef_including_sequestration', $data ?? [], null);
        $this->setIfExists('beef_excluding_sequestration', $data ?? [], null);
        $this->setIfExists('liveweight_beef_produced_kg', $data ?? [], null);
        $this->setIfExists('wool_including_sequestration', $data ?? [], null);
        $this->setIfExists('wool_excluding_sequestration', $data ?? [], null);
        $this->setIfExists('sheep_meat_breeding_including_sequestration', $data ?? [], null);
        $this->setIfExists('sheep_meat_breeding_excluding_sequestration', $data ?? [], null);
        $this->setIfExists('wool_produced_kg', $data ?? [], null);
        $this->setIfExists('sheep_meat_produced_kg', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['beef_including_sequestration'] === null) {
            $invalidProperties[] = "'beef_including_sequestration' can't be null";
        }
        if ($this->container['beef_excluding_sequestration'] === null) {
            $invalidProperties[] = "'beef_excluding_sequestration' can't be null";
        }
        if ($this->container['liveweight_beef_produced_kg'] === null) {
            $invalidProperties[] = "'liveweight_beef_produced_kg' can't be null";
        }
        if ($this->container['wool_including_sequestration'] === null) {
            $invalidProperties[] = "'wool_including_sequestration' can't be null";
        }
        if ($this->container['wool_excluding_sequestration'] === null) {
            $invalidProperties[] = "'wool_excluding_sequestration' can't be null";
        }
        if ($this->container['sheep_meat_breeding_including_sequestration'] === null) {
            $invalidProperties[] = "'sheep_meat_breeding_including_sequestration' can't be null";
        }
        if ($this->container['sheep_meat_breeding_excluding_sequestration'] === null) {
            $invalidProperties[] = "'sheep_meat_breeding_excluding_sequestration' can't be null";
        }
        if ($this->container['wool_produced_kg'] === null) {
            $invalidProperties[] = "'wool_produced_kg' can't be null";
        }
        if ($this->container['sheep_meat_produced_kg'] === null) {
            $invalidProperties[] = "'sheep_meat_produced_kg' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets beef_including_sequestration
     *
     * @return float
     */
    public function getBeefIncludingSequestration()
    {
        return $this->container['beef_including_sequestration'];
    }

    /**
     * Sets beef_including_sequestration
     *
     * @param float $beef_including_sequestration Beef including carbon sequestration, in kg-CO2e/kg liveweight
     *
     * @return self
     */
    public function setBeefIncludingSequestration($beef_including_sequestration)
    {
        if (is_null($beef_including_sequestration)) {
            throw new \InvalidArgumentException('non-nullable beef_including_sequestration cannot be null');
        }
        $this->container['beef_including_sequestration'] = $beef_including_sequestration;

        return $this;
    }

    /**
     * Gets beef_excluding_sequestration
     *
     * @return float
     */
    public function getBeefExcludingSequestration()
    {
        return $this->container['beef_excluding_sequestration'];
    }

    /**
     * Sets beef_excluding_sequestration
     *
     * @param float $beef_excluding_sequestration Beef excluding carbon sequestration, in kg-CO2e/kg liveweight
     *
     * @return self
     */
    public function setBeefExcludingSequestration($beef_excluding_sequestration)
    {
        if (is_null($beef_excluding_sequestration)) {
            throw new \InvalidArgumentException('non-nullable beef_excluding_sequestration cannot be null');
        }
        $this->container['beef_excluding_sequestration'] = $beef_excluding_sequestration;

        return $this;
    }

    /**
     * Gets liveweight_beef_produced_kg
     *
     * @return float
     */
    public function getLiveweightBeefProducedKg()
    {
        return $this->container['liveweight_beef_produced_kg'];
    }

    /**
     * Sets liveweight_beef_produced_kg
     *
     * @param float $liveweight_beef_produced_kg Liveweight produced in kg
     *
     * @return self
     */
    public function setLiveweightBeefProducedKg($liveweight_beef_produced_kg)
    {
        if (is_null($liveweight_beef_produced_kg)) {
            throw new \InvalidArgumentException('non-nullable liveweight_beef_produced_kg cannot be null');
        }
        $this->container['liveweight_beef_produced_kg'] = $liveweight_beef_produced_kg;

        return $this;
    }

    /**
     * Gets wool_including_sequestration
     *
     * @return float
     */
    public function getWoolIncludingSequestration()
    {
        return $this->container['wool_including_sequestration'];
    }

    /**
     * Sets wool_including_sequestration
     *
     * @param float $wool_including_sequestration Wool production including carbon sequestration, in kg-CO2e/kg greasy
     *
     * @return self
     */
    public function setWoolIncludingSequestration($wool_including_sequestration)
    {
        if (is_null($wool_including_sequestration)) {
            throw new \InvalidArgumentException('non-nullable wool_including_sequestration cannot be null');
        }
        $this->container['wool_including_sequestration'] = $wool_including_sequestration;

        return $this;
    }

    /**
     * Gets wool_excluding_sequestration
     *
     * @return float
     */
    public function getWoolExcludingSequestration()
    {
        return $this->container['wool_excluding_sequestration'];
    }

    /**
     * Sets wool_excluding_sequestration
     *
     * @param float $wool_excluding_sequestration Wool production excluding carbon sequestration, in kg-CO2e/kg greasy
     *
     * @return self
     */
    public function setWoolExcludingSequestration($wool_excluding_sequestration)
    {
        if (is_null($wool_excluding_sequestration)) {
            throw new \InvalidArgumentException('non-nullable wool_excluding_sequestration cannot be null');
        }
        $this->container['wool_excluding_sequestration'] = $wool_excluding_sequestration;

        return $this;
    }

    /**
     * Gets sheep_meat_breeding_including_sequestration
     *
     * @return float
     */
    public function getSheepMeatBreedingIncludingSequestration()
    {
        return $this->container['sheep_meat_breeding_including_sequestration'];
    }

    /**
     * Sets sheep_meat_breeding_including_sequestration
     *
     * @param float $sheep_meat_breeding_including_sequestration Sheep meat (breeding herd) including carbon sequestration, in kg-CO2e/kg liveweight
     *
     * @return self
     */
    public function setSheepMeatBreedingIncludingSequestration($sheep_meat_breeding_including_sequestration)
    {
        if (is_null($sheep_meat_breeding_including_sequestration)) {
            throw new \InvalidArgumentException('non-nullable sheep_meat_breeding_including_sequestration cannot be null');
        }
        $this->container['sheep_meat_breeding_including_sequestration'] = $sheep_meat_breeding_including_sequestration;

        return $this;
    }

    /**
     * Gets sheep_meat_breeding_excluding_sequestration
     *
     * @return float
     */
    public function getSheepMeatBreedingExcludingSequestration()
    {
        return $this->container['sheep_meat_breeding_excluding_sequestration'];
    }

    /**
     * Sets sheep_meat_breeding_excluding_sequestration
     *
     * @param float $sheep_meat_breeding_excluding_sequestration Sheep meat (breeding herd) excluding carbon sequestration, in kg-CO2e/kg liveweight
     *
     * @return self
     */
    public function setSheepMeatBreedingExcludingSequestration($sheep_meat_breeding_excluding_sequestration)
    {
        if (is_null($sheep_meat_breeding_excluding_sequestration)) {
            throw new \InvalidArgumentException('non-nullable sheep_meat_breeding_excluding_sequestration cannot be null');
        }
        $this->container['sheep_meat_breeding_excluding_sequestration'] = $sheep_meat_breeding_excluding_sequestration;

        return $this;
    }

    /**
     * Gets wool_produced_kg
     *
     * @return float
     */
    public function getWoolProducedKg()
    {
        return $this->container['wool_produced_kg'];
    }

    /**
     * Sets wool_produced_kg
     *
     * @param float $wool_produced_kg Greasy wool produced in kg
     *
     * @return self
     */
    public function setWoolProducedKg($wool_produced_kg)
    {
        if (is_null($wool_produced_kg)) {
            throw new \InvalidArgumentException('non-nullable wool_produced_kg cannot be null');
        }
        $this->container['wool_produced_kg'] = $wool_produced_kg;

        return $this;
    }

    /**
     * Gets sheep_meat_produced_kg
     *
     * @return float
     */
    public function getSheepMeatProducedKg()
    {
        return $this->container['sheep_meat_produced_kg'];
    }

    /**
     * Sets sheep_meat_produced_kg
     *
     * @param float $sheep_meat_produced_kg Sheep meat produced in kg liveweight
     *
     * @return self
     */
    public function setSheepMeatProducedKg($sheep_meat_produced_kg)
    {
        if (is_null($sheep_meat_produced_kg)) {
            throw new \InvalidArgumentException('non-nullable sheep_meat_produced_kg cannot be null');
        }
        $this->container['sheep_meat_produced_kg'] = $sheep_meat_produced_kg;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


