<?php
/**
 * PostBeefRequestBurningInnerBurning
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AIA Calculator API
 *
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PostBeefRequestBurningInnerBurning Class Doc Comment
 *
 * @category Class
 * @description Inputs required for any savannah burning activities that took place
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PostBeefRequestBurningInnerBurning implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'post_beef_request_burning_inner_burning';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'fuel' => 'string',
        'season' => 'string',
        'patchiness' => 'string',
        'rainfall_zone' => 'string',
        'years_since_last_fire' => 'float',
        'fire_scar_area' => 'float',
        'vegetation' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'fuel' => null,
        'season' => null,
        'patchiness' => null,
        'rainfall_zone' => null,
        'years_since_last_fire' => null,
        'fire_scar_area' => null,
        'vegetation' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'fuel' => false,
        'season' => false,
        'patchiness' => false,
        'rainfall_zone' => false,
        'years_since_last_fire' => false,
        'fire_scar_area' => false,
        'vegetation' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'fuel' => 'fuel',
        'season' => 'season',
        'patchiness' => 'patchiness',
        'rainfall_zone' => 'rainfallZone',
        'years_since_last_fire' => 'yearsSinceLastFire',
        'fire_scar_area' => 'fireScarArea',
        'vegetation' => 'vegetation'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'fuel' => 'setFuel',
        'season' => 'setSeason',
        'patchiness' => 'setPatchiness',
        'rainfall_zone' => 'setRainfallZone',
        'years_since_last_fire' => 'setYearsSinceLastFire',
        'fire_scar_area' => 'setFireScarArea',
        'vegetation' => 'setVegetation'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'fuel' => 'getFuel',
        'season' => 'getSeason',
        'patchiness' => 'getPatchiness',
        'rainfall_zone' => 'getRainfallZone',
        'years_since_last_fire' => 'getYearsSinceLastFire',
        'fire_scar_area' => 'getFireScarArea',
        'vegetation' => 'getVegetation'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const FUEL_FINE = 'fine';
    public const FUEL_COARSE = 'coarse';
    public const SEASON_EARLY_DRY_SEASON = 'early dry season';
    public const SEASON_LATE_DRY_SEASON = 'late dry season';
    public const PATCHINESS_LOW = 'low';
    public const PATCHINESS_HIGH = 'high';
    public const RAINFALL_ZONE_LOW = 'low';
    public const RAINFALL_ZONE_HIGH = 'high';
    public const VEGETATION_SHRUBLAND_HUMMOCK = 'Shrubland hummock';
    public const VEGETATION_WOODLAND_HUMMOCK = 'Woodland Hummock';
    public const VEGETATION_MELALEUCA_WOODLAND = 'Melaleuca woodland';
    public const VEGETATION_WOODLAND_MIXED = 'Woodland Mixed';
    public const VEGETATION_OPEN_FOREST_MIXED = 'Open forest mixed';
    public const VEGETATION_SHRUBLAND__HEATH_WITH_HUMMOCK_GRASS = 'Shrubland (heath) with hummock grass';
    public const VEGETATION_WOODLAND_WITH_HUMMOCK_GRASS = 'Woodland with hummock grass';
    public const VEGETATION_OPEN_WOODLAND_WITH_MIXED_GRASS = 'Open woodland with mixed grass';
    public const VEGETATION_WOODLAND_WITH_MIXED_GRASS = 'Woodland with mixed grass';
    public const VEGETATION_WOODLAND_WITH_TUSSOCK_GRASS = 'Woodland with tussock grass';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getFuelAllowableValues()
    {
        return [
            self::FUEL_FINE,
            self::FUEL_COARSE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSeasonAllowableValues()
    {
        return [
            self::SEASON_EARLY_DRY_SEASON,
            self::SEASON_LATE_DRY_SEASON,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPatchinessAllowableValues()
    {
        return [
            self::PATCHINESS_LOW,
            self::PATCHINESS_HIGH,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getRainfallZoneAllowableValues()
    {
        return [
            self::RAINFALL_ZONE_LOW,
            self::RAINFALL_ZONE_HIGH,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getVegetationAllowableValues()
    {
        return [
            self::VEGETATION_SHRUBLAND_HUMMOCK,
            self::VEGETATION_WOODLAND_HUMMOCK,
            self::VEGETATION_MELALEUCA_WOODLAND,
            self::VEGETATION_WOODLAND_MIXED,
            self::VEGETATION_OPEN_FOREST_MIXED,
            self::VEGETATION_SHRUBLAND__HEATH_WITH_HUMMOCK_GRASS,
            self::VEGETATION_WOODLAND_WITH_HUMMOCK_GRASS,
            self::VEGETATION_OPEN_WOODLAND_WITH_MIXED_GRASS,
            self::VEGETATION_WOODLAND_WITH_MIXED_GRASS,
            self::VEGETATION_WOODLAND_WITH_TUSSOCK_GRASS,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('fuel', $data ?? [], 'coarse');
        $this->setIfExists('season', $data ?? [], 'early dry season');
        $this->setIfExists('patchiness', $data ?? [], 'high');
        $this->setIfExists('rainfall_zone', $data ?? [], 'low');
        $this->setIfExists('years_since_last_fire', $data ?? [], 0);
        $this->setIfExists('fire_scar_area', $data ?? [], 0);
        $this->setIfExists('vegetation', $data ?? [], 'Melaleuca woodland');
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['fuel'] === null) {
            $invalidProperties[] = "'fuel' can't be null";
        }
        $allowedValues = $this->getFuelAllowableValues();
        if (!is_null($this->container['fuel']) && !in_array($this->container['fuel'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'fuel', must be one of '%s'",
                $this->container['fuel'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['season'] === null) {
            $invalidProperties[] = "'season' can't be null";
        }
        $allowedValues = $this->getSeasonAllowableValues();
        if (!is_null($this->container['season']) && !in_array($this->container['season'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'season', must be one of '%s'",
                $this->container['season'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['patchiness'] === null) {
            $invalidProperties[] = "'patchiness' can't be null";
        }
        $allowedValues = $this->getPatchinessAllowableValues();
        if (!is_null($this->container['patchiness']) && !in_array($this->container['patchiness'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'patchiness', must be one of '%s'",
                $this->container['patchiness'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['rainfall_zone'] === null) {
            $invalidProperties[] = "'rainfall_zone' can't be null";
        }
        $allowedValues = $this->getRainfallZoneAllowableValues();
        if (!is_null($this->container['rainfall_zone']) && !in_array($this->container['rainfall_zone'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'rainfall_zone', must be one of '%s'",
                $this->container['rainfall_zone'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['years_since_last_fire'] === null) {
            $invalidProperties[] = "'years_since_last_fire' can't be null";
        }
        if ($this->container['fire_scar_area'] === null) {
            $invalidProperties[] = "'fire_scar_area' can't be null";
        }
        if ($this->container['vegetation'] === null) {
            $invalidProperties[] = "'vegetation' can't be null";
        }
        $allowedValues = $this->getVegetationAllowableValues();
        if (!is_null($this->container['vegetation']) && !in_array($this->container['vegetation'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'vegetation', must be one of '%s'",
                $this->container['vegetation'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets fuel
     *
     * @return string
     */
    public function getFuel()
    {
        return $this->container['fuel'];
    }

    /**
     * Sets fuel
     *
     * @param string $fuel The fuel class size that was burnt
     *
     * @return self
     */
    public function setFuel($fuel)
    {
        if (is_null($fuel)) {
            throw new \InvalidArgumentException('non-nullable fuel cannot be null');
        }
        $allowedValues = $this->getFuelAllowableValues();
        if (!in_array($fuel, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'fuel', must be one of '%s'",
                    $fuel,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['fuel'] = $fuel;

        return $this;
    }

    /**
     * Gets season
     *
     * @return string
     */
    public function getSeason()
    {
        return $this->container['season'];
    }

    /**
     * Sets season
     *
     * @param string $season The time relative to the fire season in which the burning took place
     *
     * @return self
     */
    public function setSeason($season)
    {
        if (is_null($season)) {
            throw new \InvalidArgumentException('non-nullable season cannot be null');
        }
        $allowedValues = $this->getSeasonAllowableValues();
        if (!in_array($season, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'season', must be one of '%s'",
                    $season,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['season'] = $season;

        return $this;
    }

    /**
     * Gets patchiness
     *
     * @return string
     */
    public function getPatchiness()
    {
        return $this->container['patchiness'];
    }

    /**
     * Sets patchiness
     *
     * @param string $patchiness The patchiness of the savannah/vegetation that was burnt
     *
     * @return self
     */
    public function setPatchiness($patchiness)
    {
        if (is_null($patchiness)) {
            throw new \InvalidArgumentException('non-nullable patchiness cannot be null');
        }
        $allowedValues = $this->getPatchinessAllowableValues();
        if (!in_array($patchiness, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'patchiness', must be one of '%s'",
                    $patchiness,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['patchiness'] = $patchiness;

        return $this;
    }

    /**
     * Gets rainfall_zone
     *
     * @return string
     */
    public function getRainfallZone()
    {
        return $this->container['rainfall_zone'];
    }

    /**
     * Sets rainfall_zone
     *
     * @param string $rainfall_zone The rainfall zone in which the burning took place
     *
     * @return self
     */
    public function setRainfallZone($rainfall_zone)
    {
        if (is_null($rainfall_zone)) {
            throw new \InvalidArgumentException('non-nullable rainfall_zone cannot be null');
        }
        $allowedValues = $this->getRainfallZoneAllowableValues();
        if (!in_array($rainfall_zone, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'rainfall_zone', must be one of '%s'",
                    $rainfall_zone,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['rainfall_zone'] = $rainfall_zone;

        return $this;
    }

    /**
     * Gets years_since_last_fire
     *
     * @return float
     */
    public function getYearsSinceLastFire()
    {
        return $this->container['years_since_last_fire'];
    }

    /**
     * Sets years_since_last_fire
     *
     * @param float $years_since_last_fire Time since the last fire, in years
     *
     * @return self
     */
    public function setYearsSinceLastFire($years_since_last_fire)
    {
        if (is_null($years_since_last_fire)) {
            throw new \InvalidArgumentException('non-nullable years_since_last_fire cannot be null');
        }
        $this->container['years_since_last_fire'] = $years_since_last_fire;

        return $this;
    }

    /**
     * Gets fire_scar_area
     *
     * @return float
     */
    public function getFireScarArea()
    {
        return $this->container['fire_scar_area'];
    }

    /**
     * Sets fire_scar_area
     *
     * @param float $fire_scar_area The total area of the fire scar, in ha (hectares)
     *
     * @return self
     */
    public function setFireScarArea($fire_scar_area)
    {
        if (is_null($fire_scar_area)) {
            throw new \InvalidArgumentException('non-nullable fire_scar_area cannot be null');
        }
        $this->container['fire_scar_area'] = $fire_scar_area;

        return $this;
    }

    /**
     * Gets vegetation
     *
     * @return string
     */
    public function getVegetation()
    {
        return $this->container['vegetation'];
    }

    /**
     * Sets vegetation
     *
     * @param string $vegetation The vegetation class that was burnt
     *
     * @return self
     */
    public function setVegetation($vegetation)
    {
        if (is_null($vegetation)) {
            throw new \InvalidArgumentException('non-nullable vegetation cannot be null');
        }
        $allowedValues = $this->getVegetationAllowableValues();
        if (!in_array($vegetation, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'vegetation', must be one of '%s'",
                    $vegetation,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['vegetation'] = $vegetation;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


