<?php
/**
 * PostPorkRequestPorkInnerClassesSowsManureSpring
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AIA Calculator API
 *
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PostPorkRequestPorkInnerClassesSowsManureSpring Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PostPorkRequestPorkInnerClassesSowsManureSpring implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'post_pork_request_pork_inner_classes_sows_manure_spring';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'outdoor_systems' => 'float',
        'covered_anaerobic_pond' => 'float',
        'uncovered_anaerobic_pond' => 'float',
        'deep_litter' => 'float',
        'undefined_system' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'outdoor_systems' => null,
        'covered_anaerobic_pond' => null,
        'uncovered_anaerobic_pond' => null,
        'deep_litter' => null,
        'undefined_system' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'outdoor_systems' => false,
        'covered_anaerobic_pond' => false,
        'uncovered_anaerobic_pond' => false,
        'deep_litter' => false,
        'undefined_system' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'outdoor_systems' => 'outdoorSystems',
        'covered_anaerobic_pond' => 'coveredAnaerobicPond',
        'uncovered_anaerobic_pond' => 'uncoveredAnaerobicPond',
        'deep_litter' => 'deepLitter',
        'undefined_system' => 'undefinedSystem'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'outdoor_systems' => 'setOutdoorSystems',
        'covered_anaerobic_pond' => 'setCoveredAnaerobicPond',
        'uncovered_anaerobic_pond' => 'setUncoveredAnaerobicPond',
        'deep_litter' => 'setDeepLitter',
        'undefined_system' => 'setUndefinedSystem'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'outdoor_systems' => 'getOutdoorSystems',
        'covered_anaerobic_pond' => 'getCoveredAnaerobicPond',
        'uncovered_anaerobic_pond' => 'getUncoveredAnaerobicPond',
        'deep_litter' => 'getDeepLitter',
        'undefined_system' => 'getUndefinedSystem'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('outdoor_systems', $data ?? [], null);
        $this->setIfExists('covered_anaerobic_pond', $data ?? [], null);
        $this->setIfExists('uncovered_anaerobic_pond', $data ?? [], null);
        $this->setIfExists('deep_litter', $data ?? [], null);
        $this->setIfExists('undefined_system', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets outdoor_systems
     *
     * @return float|null
     */
    public function getOutdoorSystems()
    {
        return $this->container['outdoor_systems'];
    }

    /**
     * Sets outdoor_systems
     *
     * @param float|null $outdoor_systems Amount of volatile solids sent to outoor systems in t (tonnes)
     *
     * @return self
     */
    public function setOutdoorSystems($outdoor_systems)
    {
        if (is_null($outdoor_systems)) {
            throw new \InvalidArgumentException('non-nullable outdoor_systems cannot be null');
        }
        $this->container['outdoor_systems'] = $outdoor_systems;

        return $this;
    }

    /**
     * Gets covered_anaerobic_pond
     *
     * @return float|null
     */
    public function getCoveredAnaerobicPond()
    {
        return $this->container['covered_anaerobic_pond'];
    }

    /**
     * Sets covered_anaerobic_pond
     *
     * @param float|null $covered_anaerobic_pond Amount of volatile solids sent to covered anaerobic pond in t (tonnes)
     *
     * @return self
     */
    public function setCoveredAnaerobicPond($covered_anaerobic_pond)
    {
        if (is_null($covered_anaerobic_pond)) {
            throw new \InvalidArgumentException('non-nullable covered_anaerobic_pond cannot be null');
        }
        $this->container['covered_anaerobic_pond'] = $covered_anaerobic_pond;

        return $this;
    }

    /**
     * Gets uncovered_anaerobic_pond
     *
     * @return float|null
     */
    public function getUncoveredAnaerobicPond()
    {
        return $this->container['uncovered_anaerobic_pond'];
    }

    /**
     * Sets uncovered_anaerobic_pond
     *
     * @param float|null $uncovered_anaerobic_pond Amount of volatile solids sent to uncovered anaerobic pond in t (tonnes)
     *
     * @return self
     */
    public function setUncoveredAnaerobicPond($uncovered_anaerobic_pond)
    {
        if (is_null($uncovered_anaerobic_pond)) {
            throw new \InvalidArgumentException('non-nullable uncovered_anaerobic_pond cannot be null');
        }
        $this->container['uncovered_anaerobic_pond'] = $uncovered_anaerobic_pond;

        return $this;
    }

    /**
     * Gets deep_litter
     *
     * @return float|null
     */
    public function getDeepLitter()
    {
        return $this->container['deep_litter'];
    }

    /**
     * Sets deep_litter
     *
     * @param float|null $deep_litter Amount of volatile solids sent to deep litter in t (tonnes)
     *
     * @return self
     */
    public function setDeepLitter($deep_litter)
    {
        if (is_null($deep_litter)) {
            throw new \InvalidArgumentException('non-nullable deep_litter cannot be null');
        }
        $this->container['deep_litter'] = $deep_litter;

        return $this;
    }

    /**
     * Gets undefined_system
     *
     * @return float|null
     */
    public function getUndefinedSystem()
    {
        return $this->container['undefined_system'];
    }

    /**
     * Sets undefined_system
     *
     * @param float|null $undefined_system Amount of volatile solids where manure management system is not known or defined, in t (tonnes)
     *
     * @return self
     */
    public function setUndefinedSystem($undefined_system)
    {
        if (is_null($undefined_system)) {
            throw new \InvalidArgumentException('non-nullable undefined_system cannot be null');
        }
        $this->container['undefined_system'] = $undefined_system;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


