<?php
/**
 * PostBuffaloRequestBuffalosInnerClasses
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AIA Calculator API
 *
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PostBuffaloRequestBuffalosInnerClasses Class Doc Comment
 *
 * @category Class
 * @description Buffalo classes of different types
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PostBuffaloRequestBuffalosInnerClasses implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'post_buffalo_request_buffalos_inner_classes';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'bulls' => '\OpenAPI\Client\Model\PostBuffaloRequestBuffalosInnerClassesBulls',
        'trade_bulls' => '\OpenAPI\Client\Model\PostBuffaloRequestBuffalosInnerClassesTradeBulls',
        'cows' => '\OpenAPI\Client\Model\PostBuffaloRequestBuffalosInnerClassesCows',
        'trade_cows' => '\OpenAPI\Client\Model\PostBuffaloRequestBuffalosInnerClassesTradeCows',
        'steers' => '\OpenAPI\Client\Model\PostBuffaloRequestBuffalosInnerClassesSteers',
        'trade_steers' => '\OpenAPI\Client\Model\PostBuffaloRequestBuffalosInnerClassesTradeSteers',
        'calfs' => '\OpenAPI\Client\Model\PostBuffaloRequestBuffalosInnerClassesCalfs',
        'trade_calfs' => '\OpenAPI\Client\Model\PostBuffaloRequestBuffalosInnerClassesTradeCalfs'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'bulls' => null,
        'trade_bulls' => null,
        'cows' => null,
        'trade_cows' => null,
        'steers' => null,
        'trade_steers' => null,
        'calfs' => null,
        'trade_calfs' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'bulls' => false,
        'trade_bulls' => false,
        'cows' => false,
        'trade_cows' => false,
        'steers' => false,
        'trade_steers' => false,
        'calfs' => false,
        'trade_calfs' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'bulls' => 'bulls',
        'trade_bulls' => 'tradeBulls',
        'cows' => 'cows',
        'trade_cows' => 'tradeCows',
        'steers' => 'steers',
        'trade_steers' => 'tradeSteers',
        'calfs' => 'calfs',
        'trade_calfs' => 'tradeCalfs'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'bulls' => 'setBulls',
        'trade_bulls' => 'setTradeBulls',
        'cows' => 'setCows',
        'trade_cows' => 'setTradeCows',
        'steers' => 'setSteers',
        'trade_steers' => 'setTradeSteers',
        'calfs' => 'setCalfs',
        'trade_calfs' => 'setTradeCalfs'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'bulls' => 'getBulls',
        'trade_bulls' => 'getTradeBulls',
        'cows' => 'getCows',
        'trade_cows' => 'getTradeCows',
        'steers' => 'getSteers',
        'trade_steers' => 'getTradeSteers',
        'calfs' => 'getCalfs',
        'trade_calfs' => 'getTradeCalfs'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('bulls', $data ?? [], null);
        $this->setIfExists('trade_bulls', $data ?? [], null);
        $this->setIfExists('cows', $data ?? [], null);
        $this->setIfExists('trade_cows', $data ?? [], null);
        $this->setIfExists('steers', $data ?? [], null);
        $this->setIfExists('trade_steers', $data ?? [], null);
        $this->setIfExists('calfs', $data ?? [], null);
        $this->setIfExists('trade_calfs', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets bulls
     *
     * @return \OpenAPI\Client\Model\PostBuffaloRequestBuffalosInnerClassesBulls|null
     */
    public function getBulls()
    {
        return $this->container['bulls'];
    }

    /**
     * Sets bulls
     *
     * @param \OpenAPI\Client\Model\PostBuffaloRequestBuffalosInnerClassesBulls|null $bulls bulls
     *
     * @return self
     */
    public function setBulls($bulls)
    {
        if (is_null($bulls)) {
            throw new \InvalidArgumentException('non-nullable bulls cannot be null');
        }
        $this->container['bulls'] = $bulls;

        return $this;
    }

    /**
     * Gets trade_bulls
     *
     * @return \OpenAPI\Client\Model\PostBuffaloRequestBuffalosInnerClassesTradeBulls|null
     */
    public function getTradeBulls()
    {
        return $this->container['trade_bulls'];
    }

    /**
     * Sets trade_bulls
     *
     * @param \OpenAPI\Client\Model\PostBuffaloRequestBuffalosInnerClassesTradeBulls|null $trade_bulls trade_bulls
     *
     * @return self
     */
    public function setTradeBulls($trade_bulls)
    {
        if (is_null($trade_bulls)) {
            throw new \InvalidArgumentException('non-nullable trade_bulls cannot be null');
        }
        $this->container['trade_bulls'] = $trade_bulls;

        return $this;
    }

    /**
     * Gets cows
     *
     * @return \OpenAPI\Client\Model\PostBuffaloRequestBuffalosInnerClassesCows|null
     */
    public function getCows()
    {
        return $this->container['cows'];
    }

    /**
     * Sets cows
     *
     * @param \OpenAPI\Client\Model\PostBuffaloRequestBuffalosInnerClassesCows|null $cows cows
     *
     * @return self
     */
    public function setCows($cows)
    {
        if (is_null($cows)) {
            throw new \InvalidArgumentException('non-nullable cows cannot be null');
        }
        $this->container['cows'] = $cows;

        return $this;
    }

    /**
     * Gets trade_cows
     *
     * @return \OpenAPI\Client\Model\PostBuffaloRequestBuffalosInnerClassesTradeCows|null
     */
    public function getTradeCows()
    {
        return $this->container['trade_cows'];
    }

    /**
     * Sets trade_cows
     *
     * @param \OpenAPI\Client\Model\PostBuffaloRequestBuffalosInnerClassesTradeCows|null $trade_cows trade_cows
     *
     * @return self
     */
    public function setTradeCows($trade_cows)
    {
        if (is_null($trade_cows)) {
            throw new \InvalidArgumentException('non-nullable trade_cows cannot be null');
        }
        $this->container['trade_cows'] = $trade_cows;

        return $this;
    }

    /**
     * Gets steers
     *
     * @return \OpenAPI\Client\Model\PostBuffaloRequestBuffalosInnerClassesSteers|null
     */
    public function getSteers()
    {
        return $this->container['steers'];
    }

    /**
     * Sets steers
     *
     * @param \OpenAPI\Client\Model\PostBuffaloRequestBuffalosInnerClassesSteers|null $steers steers
     *
     * @return self
     */
    public function setSteers($steers)
    {
        if (is_null($steers)) {
            throw new \InvalidArgumentException('non-nullable steers cannot be null');
        }
        $this->container['steers'] = $steers;

        return $this;
    }

    /**
     * Gets trade_steers
     *
     * @return \OpenAPI\Client\Model\PostBuffaloRequestBuffalosInnerClassesTradeSteers|null
     */
    public function getTradeSteers()
    {
        return $this->container['trade_steers'];
    }

    /**
     * Sets trade_steers
     *
     * @param \OpenAPI\Client\Model\PostBuffaloRequestBuffalosInnerClassesTradeSteers|null $trade_steers trade_steers
     *
     * @return self
     */
    public function setTradeSteers($trade_steers)
    {
        if (is_null($trade_steers)) {
            throw new \InvalidArgumentException('non-nullable trade_steers cannot be null');
        }
        $this->container['trade_steers'] = $trade_steers;

        return $this;
    }

    /**
     * Gets calfs
     *
     * @return \OpenAPI\Client\Model\PostBuffaloRequestBuffalosInnerClassesCalfs|null
     */
    public function getCalfs()
    {
        return $this->container['calfs'];
    }

    /**
     * Sets calfs
     *
     * @param \OpenAPI\Client\Model\PostBuffaloRequestBuffalosInnerClassesCalfs|null $calfs calfs
     *
     * @return self
     */
    public function setCalfs($calfs)
    {
        if (is_null($calfs)) {
            throw new \InvalidArgumentException('non-nullable calfs cannot be null');
        }
        $this->container['calfs'] = $calfs;

        return $this;
    }

    /**
     * Gets trade_calfs
     *
     * @return \OpenAPI\Client\Model\PostBuffaloRequestBuffalosInnerClassesTradeCalfs|null
     */
    public function getTradeCalfs()
    {
        return $this->container['trade_calfs'];
    }

    /**
     * Sets trade_calfs
     *
     * @param \OpenAPI\Client\Model\PostBuffaloRequestBuffalosInnerClassesTradeCalfs|null $trade_calfs trade_calfs
     *
     * @return self
     */
    public function setTradeCalfs($trade_calfs)
    {
        if (is_null($trade_calfs)) {
            throw new \InvalidArgumentException('non-nullable trade_calfs cannot be null');
        }
        $this->container['trade_calfs'] = $trade_calfs;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


