/* tslint:disable */
/* eslint-disable */
/**
 * AIA Calculator API
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostSheepRequestSheepInnerClassesRams } from './PostSheepRequestSheepInnerClassesRams';
import {
    PostSheepRequestSheepInnerClassesRamsFromJSON,
    PostSheepRequestSheepInnerClassesRamsFromJSONTyped,
    PostSheepRequestSheepInnerClassesRamsToJSON,
    PostSheepRequestSheepInnerClassesRamsToJSONTyped,
} from './PostSheepRequestSheepInnerClassesRams';

/**
 * 
 * @export
 * @interface PostSheepRequestSheepInnerClasses
 */
export interface PostSheepRequestSheepInnerClasses {
    /**
     * 
     * @type {PostSheepRequestSheepInnerClassesRams}
     * @memberof PostSheepRequestSheepInnerClasses
     */
    rams?: PostSheepRequestSheepInnerClassesRams;
    /**
     * 
     * @type {PostSheepRequestSheepInnerClassesRams}
     * @memberof PostSheepRequestSheepInnerClasses
     */
    tradeRams?: PostSheepRequestSheepInnerClassesRams;
    /**
     * 
     * @type {PostSheepRequestSheepInnerClassesRams}
     * @memberof PostSheepRequestSheepInnerClasses
     */
    wethers?: PostSheepRequestSheepInnerClassesRams;
    /**
     * 
     * @type {PostSheepRequestSheepInnerClassesRams}
     * @memberof PostSheepRequestSheepInnerClasses
     */
    tradeWethers?: PostSheepRequestSheepInnerClassesRams;
    /**
     * 
     * @type {PostSheepRequestSheepInnerClassesRams}
     * @memberof PostSheepRequestSheepInnerClasses
     */
    maidenBreedingEwes?: PostSheepRequestSheepInnerClassesRams;
    /**
     * 
     * @type {PostSheepRequestSheepInnerClassesRams}
     * @memberof PostSheepRequestSheepInnerClasses
     */
    tradeMaidenBreedingEwes?: PostSheepRequestSheepInnerClassesRams;
    /**
     * 
     * @type {PostSheepRequestSheepInnerClassesRams}
     * @memberof PostSheepRequestSheepInnerClasses
     */
    breedingEwes: PostSheepRequestSheepInnerClassesRams;
    /**
     * 
     * @type {PostSheepRequestSheepInnerClassesRams}
     * @memberof PostSheepRequestSheepInnerClasses
     */
    tradeBreedingEwes?: PostSheepRequestSheepInnerClassesRams;
    /**
     * 
     * @type {PostSheepRequestSheepInnerClassesRams}
     * @memberof PostSheepRequestSheepInnerClasses
     */
    otherEwes?: PostSheepRequestSheepInnerClassesRams;
    /**
     * 
     * @type {PostSheepRequestSheepInnerClassesRams}
     * @memberof PostSheepRequestSheepInnerClasses
     */
    tradeOtherEwes?: PostSheepRequestSheepInnerClassesRams;
    /**
     * 
     * @type {PostSheepRequestSheepInnerClassesRams}
     * @memberof PostSheepRequestSheepInnerClasses
     */
    eweLambs: PostSheepRequestSheepInnerClassesRams;
    /**
     * 
     * @type {PostSheepRequestSheepInnerClassesRams}
     * @memberof PostSheepRequestSheepInnerClasses
     */
    tradeEweLambs?: PostSheepRequestSheepInnerClassesRams;
    /**
     * 
     * @type {PostSheepRequestSheepInnerClassesRams}
     * @memberof PostSheepRequestSheepInnerClasses
     */
    wetherLambs: PostSheepRequestSheepInnerClassesRams;
    /**
     * 
     * @type {PostSheepRequestSheepInnerClassesRams}
     * @memberof PostSheepRequestSheepInnerClasses
     */
    tradeWetherLambs?: PostSheepRequestSheepInnerClassesRams;
}

/**
 * Check if a given object implements the PostSheepRequestSheepInnerClasses interface.
 */
export function instanceOfPostSheepRequestSheepInnerClasses(value: object): value is PostSheepRequestSheepInnerClasses {
    if (!('breedingEwes' in value) || value['breedingEwes'] === undefined) return false;
    if (!('eweLambs' in value) || value['eweLambs'] === undefined) return false;
    if (!('wetherLambs' in value) || value['wetherLambs'] === undefined) return false;
    return true;
}

export function PostSheepRequestSheepInnerClassesFromJSON(json: any): PostSheepRequestSheepInnerClasses {
    return PostSheepRequestSheepInnerClassesFromJSONTyped(json, false);
}

export function PostSheepRequestSheepInnerClassesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostSheepRequestSheepInnerClasses {
    if (json == null) {
        return json;
    }
    return {
        
        'rams': json['rams'] == null ? undefined : PostSheepRequestSheepInnerClassesRamsFromJSON(json['rams']),
        'tradeRams': json['tradeRams'] == null ? undefined : PostSheepRequestSheepInnerClassesRamsFromJSON(json['tradeRams']),
        'wethers': json['wethers'] == null ? undefined : PostSheepRequestSheepInnerClassesRamsFromJSON(json['wethers']),
        'tradeWethers': json['tradeWethers'] == null ? undefined : PostSheepRequestSheepInnerClassesRamsFromJSON(json['tradeWethers']),
        'maidenBreedingEwes': json['maidenBreedingEwes'] == null ? undefined : PostSheepRequestSheepInnerClassesRamsFromJSON(json['maidenBreedingEwes']),
        'tradeMaidenBreedingEwes': json['tradeMaidenBreedingEwes'] == null ? undefined : PostSheepRequestSheepInnerClassesRamsFromJSON(json['tradeMaidenBreedingEwes']),
        'breedingEwes': PostSheepRequestSheepInnerClassesRamsFromJSON(json['breedingEwes']),
        'tradeBreedingEwes': json['tradeBreedingEwes'] == null ? undefined : PostSheepRequestSheepInnerClassesRamsFromJSON(json['tradeBreedingEwes']),
        'otherEwes': json['otherEwes'] == null ? undefined : PostSheepRequestSheepInnerClassesRamsFromJSON(json['otherEwes']),
        'tradeOtherEwes': json['tradeOtherEwes'] == null ? undefined : PostSheepRequestSheepInnerClassesRamsFromJSON(json['tradeOtherEwes']),
        'eweLambs': PostSheepRequestSheepInnerClassesRamsFromJSON(json['eweLambs']),
        'tradeEweLambs': json['tradeEweLambs'] == null ? undefined : PostSheepRequestSheepInnerClassesRamsFromJSON(json['tradeEweLambs']),
        'wetherLambs': PostSheepRequestSheepInnerClassesRamsFromJSON(json['wetherLambs']),
        'tradeWetherLambs': json['tradeWetherLambs'] == null ? undefined : PostSheepRequestSheepInnerClassesRamsFromJSON(json['tradeWetherLambs']),
    };
}

export function PostSheepRequestSheepInnerClassesToJSON(json: any): PostSheepRequestSheepInnerClasses {
    return PostSheepRequestSheepInnerClassesToJSONTyped(json, false);
}

export function PostSheepRequestSheepInnerClassesToJSONTyped(value?: PostSheepRequestSheepInnerClasses | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rams': PostSheepRequestSheepInnerClassesRamsToJSON(value['rams']),
        'tradeRams': PostSheepRequestSheepInnerClassesRamsToJSON(value['tradeRams']),
        'wethers': PostSheepRequestSheepInnerClassesRamsToJSON(value['wethers']),
        'tradeWethers': PostSheepRequestSheepInnerClassesRamsToJSON(value['tradeWethers']),
        'maidenBreedingEwes': PostSheepRequestSheepInnerClassesRamsToJSON(value['maidenBreedingEwes']),
        'tradeMaidenBreedingEwes': PostSheepRequestSheepInnerClassesRamsToJSON(value['tradeMaidenBreedingEwes']),
        'breedingEwes': PostSheepRequestSheepInnerClassesRamsToJSON(value['breedingEwes']),
        'tradeBreedingEwes': PostSheepRequestSheepInnerClassesRamsToJSON(value['tradeBreedingEwes']),
        'otherEwes': PostSheepRequestSheepInnerClassesRamsToJSON(value['otherEwes']),
        'tradeOtherEwes': PostSheepRequestSheepInnerClassesRamsToJSON(value['tradeOtherEwes']),
        'eweLambs': PostSheepRequestSheepInnerClassesRamsToJSON(value['eweLambs']),
        'tradeEweLambs': PostSheepRequestSheepInnerClassesRamsToJSON(value['tradeEweLambs']),
        'wetherLambs': PostSheepRequestSheepInnerClassesRamsToJSON(value['wetherLambs']),
        'tradeWetherLambs': PostSheepRequestSheepInnerClassesRamsToJSON(value['tradeWetherLambs']),
    };
}

