/* tslint:disable */
/* eslint-disable */
/**
 * AIA Calculator API
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostAquaculture200ResponseScope2 } from './PostAquaculture200ResponseScope2';
import {
    PostAquaculture200ResponseScope2FromJSON,
    PostAquaculture200ResponseScope2FromJSONTyped,
    PostAquaculture200ResponseScope2ToJSON,
    PostAquaculture200ResponseScope2ToJSONTyped,
} from './PostAquaculture200ResponseScope2';
import type { PostBuffalo200ResponseScope3 } from './PostBuffalo200ResponseScope3';
import {
    PostBuffalo200ResponseScope3FromJSON,
    PostBuffalo200ResponseScope3FromJSONTyped,
    PostBuffalo200ResponseScope3ToJSON,
    PostBuffalo200ResponseScope3ToJSONTyped,
} from './PostBuffalo200ResponseScope3';
import type { PostAquaculture200ResponseCarbonSequestration } from './PostAquaculture200ResponseCarbonSequestration';
import {
    PostAquaculture200ResponseCarbonSequestrationFromJSON,
    PostAquaculture200ResponseCarbonSequestrationFromJSONTyped,
    PostAquaculture200ResponseCarbonSequestrationToJSON,
    PostAquaculture200ResponseCarbonSequestrationToJSONTyped,
} from './PostAquaculture200ResponseCarbonSequestration';
import type { PostDeer200ResponseIntensities } from './PostDeer200ResponseIntensities';
import {
    PostDeer200ResponseIntensitiesFromJSON,
    PostDeer200ResponseIntensitiesFromJSONTyped,
    PostDeer200ResponseIntensitiesToJSON,
    PostDeer200ResponseIntensitiesToJSONTyped,
} from './PostDeer200ResponseIntensities';
import type { PostDeer200ResponseIntermediateInner } from './PostDeer200ResponseIntermediateInner';
import {
    PostDeer200ResponseIntermediateInnerFromJSON,
    PostDeer200ResponseIntermediateInnerFromJSONTyped,
    PostDeer200ResponseIntermediateInnerToJSON,
    PostDeer200ResponseIntermediateInnerToJSONTyped,
} from './PostDeer200ResponseIntermediateInner';
import type { PostBuffalo200ResponseScope1 } from './PostBuffalo200ResponseScope1';
import {
    PostBuffalo200ResponseScope1FromJSON,
    PostBuffalo200ResponseScope1FromJSONTyped,
    PostBuffalo200ResponseScope1ToJSON,
    PostBuffalo200ResponseScope1ToJSONTyped,
} from './PostBuffalo200ResponseScope1';
import type { PostDeer200ResponseNet } from './PostDeer200ResponseNet';
import {
    PostDeer200ResponseNetFromJSON,
    PostDeer200ResponseNetFromJSONTyped,
    PostDeer200ResponseNetToJSON,
    PostDeer200ResponseNetToJSONTyped,
} from './PostDeer200ResponseNet';

/**
 * Emissions calculation output for the Deer calculator
 * @export
 * @interface PostDeer200Response
 */
export interface PostDeer200Response {
    /**
     * 
     * @type {PostBuffalo200ResponseScope1}
     * @memberof PostDeer200Response
     */
    scope1: PostBuffalo200ResponseScope1;
    /**
     * 
     * @type {PostAquaculture200ResponseScope2}
     * @memberof PostDeer200Response
     */
    scope2: PostAquaculture200ResponseScope2;
    /**
     * 
     * @type {PostBuffalo200ResponseScope3}
     * @memberof PostDeer200Response
     */
    scope3: PostBuffalo200ResponseScope3;
    /**
     * 
     * @type {PostAquaculture200ResponseCarbonSequestration}
     * @memberof PostDeer200Response
     */
    carbonSequestration: PostAquaculture200ResponseCarbonSequestration;
    /**
     * 
     * @type {PostDeer200ResponseNet}
     * @memberof PostDeer200Response
     */
    net: PostDeer200ResponseNet;
    /**
     * 
     * @type {PostDeer200ResponseIntensities}
     * @memberof PostDeer200Response
     */
    intensities: PostDeer200ResponseIntensities;
    /**
     * 
     * @type {Array<PostDeer200ResponseIntermediateInner>}
     * @memberof PostDeer200Response
     */
    intermediate: Array<PostDeer200ResponseIntermediateInner>;
}

/**
 * Check if a given object implements the PostDeer200Response interface.
 */
export function instanceOfPostDeer200Response(value: object): value is PostDeer200Response {
    if (!('scope1' in value) || value['scope1'] === undefined) return false;
    if (!('scope2' in value) || value['scope2'] === undefined) return false;
    if (!('scope3' in value) || value['scope3'] === undefined) return false;
    if (!('carbonSequestration' in value) || value['carbonSequestration'] === undefined) return false;
    if (!('net' in value) || value['net'] === undefined) return false;
    if (!('intensities' in value) || value['intensities'] === undefined) return false;
    if (!('intermediate' in value) || value['intermediate'] === undefined) return false;
    return true;
}

export function PostDeer200ResponseFromJSON(json: any): PostDeer200Response {
    return PostDeer200ResponseFromJSONTyped(json, false);
}

export function PostDeer200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostDeer200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'scope1': PostBuffalo200ResponseScope1FromJSON(json['scope1']),
        'scope2': PostAquaculture200ResponseScope2FromJSON(json['scope2']),
        'scope3': PostBuffalo200ResponseScope3FromJSON(json['scope3']),
        'carbonSequestration': PostAquaculture200ResponseCarbonSequestrationFromJSON(json['carbonSequestration']),
        'net': PostDeer200ResponseNetFromJSON(json['net']),
        'intensities': PostDeer200ResponseIntensitiesFromJSON(json['intensities']),
        'intermediate': ((json['intermediate'] as Array<any>).map(PostDeer200ResponseIntermediateInnerFromJSON)),
    };
}

export function PostDeer200ResponseToJSON(json: any): PostDeer200Response {
    return PostDeer200ResponseToJSONTyped(json, false);
}

export function PostDeer200ResponseToJSONTyped(value?: PostDeer200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scope1': PostBuffalo200ResponseScope1ToJSON(value['scope1']),
        'scope2': PostAquaculture200ResponseScope2ToJSON(value['scope2']),
        'scope3': PostBuffalo200ResponseScope3ToJSON(value['scope3']),
        'carbonSequestration': PostAquaculture200ResponseCarbonSequestrationToJSON(value['carbonSequestration']),
        'net': PostDeer200ResponseNetToJSON(value['net']),
        'intensities': PostDeer200ResponseIntensitiesToJSON(value['intensities']),
        'intermediate': ((value['intermediate'] as Array<any>).map(PostDeer200ResponseIntermediateInnerToJSON)),
    };
}

