/* tslint:disable */
/* eslint-disable */
/**
 * AIA Calculator API
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostAquacultureRequestEnterprisesInnerFuelTransportFuelInner } from './PostAquacultureRequestEnterprisesInnerFuelTransportFuelInner';
import {
    PostAquacultureRequestEnterprisesInnerFuelTransportFuelInnerFromJSON,
    PostAquacultureRequestEnterprisesInnerFuelTransportFuelInnerFromJSONTyped,
    PostAquacultureRequestEnterprisesInnerFuelTransportFuelInnerToJSON,
    PostAquacultureRequestEnterprisesInnerFuelTransportFuelInnerToJSONTyped,
} from './PostAquacultureRequestEnterprisesInnerFuelTransportFuelInner';
import type { PostAquacultureRequestEnterprisesInnerFuelStationaryFuelInner } from './PostAquacultureRequestEnterprisesInnerFuelStationaryFuelInner';
import {
    PostAquacultureRequestEnterprisesInnerFuelStationaryFuelInnerFromJSON,
    PostAquacultureRequestEnterprisesInnerFuelStationaryFuelInnerFromJSONTyped,
    PostAquacultureRequestEnterprisesInnerFuelStationaryFuelInnerToJSON,
    PostAquacultureRequestEnterprisesInnerFuelStationaryFuelInnerToJSONTyped,
} from './PostAquacultureRequestEnterprisesInnerFuelStationaryFuelInner';

/**
 * Fuels used in this enterprise
 * @export
 * @interface PostAquacultureRequestEnterprisesInnerFuel
 */
export interface PostAquacultureRequestEnterprisesInnerFuel {
    /**
     * A list of fuels used in transportation and vehicles
     * @type {Array<PostAquacultureRequestEnterprisesInnerFuelTransportFuelInner>}
     * @memberof PostAquacultureRequestEnterprisesInnerFuel
     */
    transportFuel: Array<PostAquacultureRequestEnterprisesInnerFuelTransportFuelInner>;
    /**
     * A list of fuels used in stationary applications
     * @type {Array<PostAquacultureRequestEnterprisesInnerFuelStationaryFuelInner>}
     * @memberof PostAquacultureRequestEnterprisesInnerFuel
     */
    stationaryFuel: Array<PostAquacultureRequestEnterprisesInnerFuelStationaryFuelInner>;
    /**
     * Amount of natural gas consumed in Mj (megajoules)
     * @type {number}
     * @memberof PostAquacultureRequestEnterprisesInnerFuel
     */
    naturalGas: number;
}

/**
 * Check if a given object implements the PostAquacultureRequestEnterprisesInnerFuel interface.
 */
export function instanceOfPostAquacultureRequestEnterprisesInnerFuel(value: object): value is PostAquacultureRequestEnterprisesInnerFuel {
    if (!('transportFuel' in value) || value['transportFuel'] === undefined) return false;
    if (!('stationaryFuel' in value) || value['stationaryFuel'] === undefined) return false;
    if (!('naturalGas' in value) || value['naturalGas'] === undefined) return false;
    return true;
}

export function PostAquacultureRequestEnterprisesInnerFuelFromJSON(json: any): PostAquacultureRequestEnterprisesInnerFuel {
    return PostAquacultureRequestEnterprisesInnerFuelFromJSONTyped(json, false);
}

export function PostAquacultureRequestEnterprisesInnerFuelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAquacultureRequestEnterprisesInnerFuel {
    if (json == null) {
        return json;
    }
    return {
        
        'transportFuel': ((json['transportFuel'] as Array<any>).map(PostAquacultureRequestEnterprisesInnerFuelTransportFuelInnerFromJSON)),
        'stationaryFuel': ((json['stationaryFuel'] as Array<any>).map(PostAquacultureRequestEnterprisesInnerFuelStationaryFuelInnerFromJSON)),
        'naturalGas': json['naturalGas'],
    };
}

export function PostAquacultureRequestEnterprisesInnerFuelToJSON(json: any): PostAquacultureRequestEnterprisesInnerFuel {
    return PostAquacultureRequestEnterprisesInnerFuelToJSONTyped(json, false);
}

export function PostAquacultureRequestEnterprisesInnerFuelToJSONTyped(value?: PostAquacultureRequestEnterprisesInnerFuel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transportFuel': ((value['transportFuel'] as Array<any>).map(PostAquacultureRequestEnterprisesInnerFuelTransportFuelInnerToJSON)),
        'stationaryFuel': ((value['stationaryFuel'] as Array<any>).map(PostAquacultureRequestEnterprisesInnerFuelStationaryFuelInnerToJSON)),
        'naturalGas': value['naturalGas'],
    };
}

