/* tslint:disable */
/* eslint-disable */
/**
 * AIA Calculator API
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostSheepbeef200ResponseNet
 */
export interface PostSheepbeef200ResponseNet {
    /**
     * Total net emissions of this activity, in tonnes-CO2e/year
     * @type {number}
     * @memberof PostSheepbeef200ResponseNet
     */
    total: number;
    /**
     * Net emissions of beef, in tonnes-CO2e/year
     * @type {number}
     * @memberof PostSheepbeef200ResponseNet
     */
    beef: number;
    /**
     * Net emissions of sheep, in tonnes-CO2e/year
     * @type {number}
     * @memberof PostSheepbeef200ResponseNet
     */
    sheep: number;
}

/**
 * Check if a given object implements the PostSheepbeef200ResponseNet interface.
 */
export function instanceOfPostSheepbeef200ResponseNet(value: object): value is PostSheepbeef200ResponseNet {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('beef' in value) || value['beef'] === undefined) return false;
    if (!('sheep' in value) || value['sheep'] === undefined) return false;
    return true;
}

export function PostSheepbeef200ResponseNetFromJSON(json: any): PostSheepbeef200ResponseNet {
    return PostSheepbeef200ResponseNetFromJSONTyped(json, false);
}

export function PostSheepbeef200ResponseNetFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostSheepbeef200ResponseNet {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'beef': json['beef'],
        'sheep': json['sheep'],
    };
}

export function PostSheepbeef200ResponseNetToJSON(json: any): PostSheepbeef200ResponseNet {
    return PostSheepbeef200ResponseNetToJSONTyped(json, false);
}

export function PostSheepbeef200ResponseNetToJSONTyped(value?: PostSheepbeef200ResponseNet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'beef': value['beef'],
        'sheep': value['sheep'],
    };
}

