/* tslint:disable */
/* eslint-disable */
/**
 * AIA Calculator API
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostBeefRequestVegetationInnerVegetation } from './PostBeefRequestVegetationInnerVegetation';
import {
    PostBeefRequestVegetationInnerVegetationFromJSON,
    PostBeefRequestVegetationInnerVegetationFromJSONTyped,
    PostBeefRequestVegetationInnerVegetationToJSON,
    PostBeefRequestVegetationInnerVegetationToJSONTyped,
} from './PostBeefRequestVegetationInnerVegetation';

/**
 * Non-productive vegetation inputs along with allocations to each Sugar activity
 * @export
 * @interface PostSugarRequestVegetationInner
 */
export interface PostSugarRequestVegetationInner {
    /**
     * 
     * @type {PostBeefRequestVegetationInnerVegetation}
     * @memberof PostSugarRequestVegetationInner
     */
    vegetation: PostBeefRequestVegetationInnerVegetation;
    /**
     * The proportion of the sequestration that is allocated to each sugar activity
     * @type {Array<number>}
     * @memberof PostSugarRequestVegetationInner
     */
    allocationToCrops: Array<number>;
}

/**
 * Check if a given object implements the PostSugarRequestVegetationInner interface.
 */
export function instanceOfPostSugarRequestVegetationInner(value: object): value is PostSugarRequestVegetationInner {
    if (!('vegetation' in value) || value['vegetation'] === undefined) return false;
    if (!('allocationToCrops' in value) || value['allocationToCrops'] === undefined) return false;
    return true;
}

export function PostSugarRequestVegetationInnerFromJSON(json: any): PostSugarRequestVegetationInner {
    return PostSugarRequestVegetationInnerFromJSONTyped(json, false);
}

export function PostSugarRequestVegetationInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostSugarRequestVegetationInner {
    if (json == null) {
        return json;
    }
    return {
        
        'vegetation': PostBeefRequestVegetationInnerVegetationFromJSON(json['vegetation']),
        'allocationToCrops': json['allocationToCrops'],
    };
}

export function PostSugarRequestVegetationInnerToJSON(json: any): PostSugarRequestVegetationInner {
    return PostSugarRequestVegetationInnerToJSONTyped(json, false);
}

export function PostSugarRequestVegetationInnerToJSONTyped(value?: PostSugarRequestVegetationInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vegetation': PostBeefRequestVegetationInnerVegetationToJSON(value['vegetation']),
        'allocationToCrops': value['allocationToCrops'],
    };
}

