/* tslint:disable */
/* eslint-disable */
/**
 * AIA Calculator API
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostAquaculture200ResponseScope2 } from './PostAquaculture200ResponseScope2';
import {
    PostAquaculture200ResponseScope2FromJSON,
    PostAquaculture200ResponseScope2FromJSONTyped,
    PostAquaculture200ResponseScope2ToJSON,
    PostAquaculture200ResponseScope2ToJSONTyped,
} from './PostAquaculture200ResponseScope2';
import type { PostPork200ResponseIntensities } from './PostPork200ResponseIntensities';
import {
    PostPork200ResponseIntensitiesFromJSON,
    PostPork200ResponseIntensitiesFromJSONTyped,
    PostPork200ResponseIntensitiesToJSON,
    PostPork200ResponseIntensitiesToJSONTyped,
} from './PostPork200ResponseIntensities';
import type { PostPork200ResponseNet } from './PostPork200ResponseNet';
import {
    PostPork200ResponseNetFromJSON,
    PostPork200ResponseNetFromJSONTyped,
    PostPork200ResponseNetToJSON,
    PostPork200ResponseNetToJSONTyped,
} from './PostPork200ResponseNet';
import type { PostPork200ResponseScope3 } from './PostPork200ResponseScope3';
import {
    PostPork200ResponseScope3FromJSON,
    PostPork200ResponseScope3FromJSONTyped,
    PostPork200ResponseScope3ToJSON,
    PostPork200ResponseScope3ToJSONTyped,
} from './PostPork200ResponseScope3';
import type { PostPork200ResponseScope1 } from './PostPork200ResponseScope1';
import {
    PostPork200ResponseScope1FromJSON,
    PostPork200ResponseScope1FromJSONTyped,
    PostPork200ResponseScope1ToJSON,
    PostPork200ResponseScope1ToJSONTyped,
} from './PostPork200ResponseScope1';
import type { PostAquaculture200ResponseCarbonSequestration } from './PostAquaculture200ResponseCarbonSequestration';
import {
    PostAquaculture200ResponseCarbonSequestrationFromJSON,
    PostAquaculture200ResponseCarbonSequestrationFromJSONTyped,
    PostAquaculture200ResponseCarbonSequestrationToJSON,
    PostAquaculture200ResponseCarbonSequestrationToJSONTyped,
} from './PostAquaculture200ResponseCarbonSequestration';

/**
 * Intermediate emissions calculation output for the Pork calculator
 * @export
 * @interface PostPork200ResponseIntermediateInner
 */
export interface PostPork200ResponseIntermediateInner {
    /**
     * Unique identifier for this Pork activity
     * @type {string}
     * @memberof PostPork200ResponseIntermediateInner
     */
    id: string;
    /**
     * 
     * @type {PostPork200ResponseScope1}
     * @memberof PostPork200ResponseIntermediateInner
     */
    scope1: PostPork200ResponseScope1;
    /**
     * 
     * @type {PostAquaculture200ResponseScope2}
     * @memberof PostPork200ResponseIntermediateInner
     */
    scope2: PostAquaculture200ResponseScope2;
    /**
     * 
     * @type {PostPork200ResponseScope3}
     * @memberof PostPork200ResponseIntermediateInner
     */
    scope3: PostPork200ResponseScope3;
    /**
     * 
     * @type {PostPork200ResponseNet}
     * @memberof PostPork200ResponseIntermediateInner
     */
    net: PostPork200ResponseNet;
    /**
     * 
     * @type {PostPork200ResponseIntensities}
     * @memberof PostPork200ResponseIntermediateInner
     */
    intensities: PostPork200ResponseIntensities;
    /**
     * 
     * @type {PostAquaculture200ResponseCarbonSequestration}
     * @memberof PostPork200ResponseIntermediateInner
     */
    carbonSequestration: PostAquaculture200ResponseCarbonSequestration;
}

/**
 * Check if a given object implements the PostPork200ResponseIntermediateInner interface.
 */
export function instanceOfPostPork200ResponseIntermediateInner(value: object): value is PostPork200ResponseIntermediateInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('scope1' in value) || value['scope1'] === undefined) return false;
    if (!('scope2' in value) || value['scope2'] === undefined) return false;
    if (!('scope3' in value) || value['scope3'] === undefined) return false;
    if (!('net' in value) || value['net'] === undefined) return false;
    if (!('intensities' in value) || value['intensities'] === undefined) return false;
    if (!('carbonSequestration' in value) || value['carbonSequestration'] === undefined) return false;
    return true;
}

export function PostPork200ResponseIntermediateInnerFromJSON(json: any): PostPork200ResponseIntermediateInner {
    return PostPork200ResponseIntermediateInnerFromJSONTyped(json, false);
}

export function PostPork200ResponseIntermediateInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostPork200ResponseIntermediateInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'scope1': PostPork200ResponseScope1FromJSON(json['scope1']),
        'scope2': PostAquaculture200ResponseScope2FromJSON(json['scope2']),
        'scope3': PostPork200ResponseScope3FromJSON(json['scope3']),
        'net': PostPork200ResponseNetFromJSON(json['net']),
        'intensities': PostPork200ResponseIntensitiesFromJSON(json['intensities']),
        'carbonSequestration': PostAquaculture200ResponseCarbonSequestrationFromJSON(json['carbonSequestration']),
    };
}

export function PostPork200ResponseIntermediateInnerToJSON(json: any): PostPork200ResponseIntermediateInner {
    return PostPork200ResponseIntermediateInnerToJSONTyped(json, false);
}

export function PostPork200ResponseIntermediateInnerToJSONTyped(value?: PostPork200ResponseIntermediateInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'scope1': PostPork200ResponseScope1ToJSON(value['scope1']),
        'scope2': PostAquaculture200ResponseScope2ToJSON(value['scope2']),
        'scope3': PostPork200ResponseScope3ToJSON(value['scope3']),
        'net': PostPork200ResponseNetToJSON(value['net']),
        'intensities': PostPork200ResponseIntensitiesToJSON(value['intensities']),
        'carbonSequestration': PostAquaculture200ResponseCarbonSequestrationToJSON(value['carbonSequestration']),
    };
}

