/* tslint:disable */
/* eslint-disable */
/**
 * AIA Calculator API
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostBeefRequestVegetationInnerVegetation } from './PostBeefRequestVegetationInnerVegetation';
import {
    PostBeefRequestVegetationInnerVegetationFromJSON,
    PostBeefRequestVegetationInnerVegetationFromJSONTyped,
    PostBeefRequestVegetationInnerVegetationToJSON,
    PostBeefRequestVegetationInnerVegetationToJSONTyped,
} from './PostBeefRequestVegetationInnerVegetation';

/**
 * Non-productive vegetation inputs along with allocations to each Beef activity
 * @export
 * @interface PostBeefRequestVegetationInner
 */
export interface PostBeefRequestVegetationInner {
    /**
     * 
     * @type {PostBeefRequestVegetationInnerVegetation}
     * @memberof PostBeefRequestVegetationInner
     */
    vegetation: PostBeefRequestVegetationInnerVegetation;
    /**
     * The proportion of the sequestration that is allocated to beef. Deprecation note: Please use `allocationToBeef` instead
     * @type {number}
     * @memberof PostBeefRequestVegetationInner
     * @deprecated
     */
    beefProportion?: number;
    /**
     * The proportion of the sequestration that is allocated to each beef activity
     * @type {Array<number>}
     * @memberof PostBeefRequestVegetationInner
     */
    allocationToBeef: Array<number>;
}

/**
 * Check if a given object implements the PostBeefRequestVegetationInner interface.
 */
export function instanceOfPostBeefRequestVegetationInner(value: object): value is PostBeefRequestVegetationInner {
    if (!('vegetation' in value) || value['vegetation'] === undefined) return false;
    if (!('allocationToBeef' in value) || value['allocationToBeef'] === undefined) return false;
    return true;
}

export function PostBeefRequestVegetationInnerFromJSON(json: any): PostBeefRequestVegetationInner {
    return PostBeefRequestVegetationInnerFromJSONTyped(json, false);
}

export function PostBeefRequestVegetationInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostBeefRequestVegetationInner {
    if (json == null) {
        return json;
    }
    return {
        
        'vegetation': PostBeefRequestVegetationInnerVegetationFromJSON(json['vegetation']),
        'beefProportion': json['beefProportion'] == null ? undefined : json['beefProportion'],
        'allocationToBeef': json['allocationToBeef'],
    };
}

export function PostBeefRequestVegetationInnerToJSON(json: any): PostBeefRequestVegetationInner {
    return PostBeefRequestVegetationInnerToJSONTyped(json, false);
}

export function PostBeefRequestVegetationInnerToJSONTyped(value?: PostBeefRequestVegetationInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vegetation': PostBeefRequestVegetationInnerVegetationToJSON(value['vegetation']),
        'beefProportion': value['beefProportion'],
        'allocationToBeef': value['allocationToBeef'],
    };
}

