/* tslint:disable */
/* eslint-disable */
/**
 * AIA Calculator API
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostAquaculture200ResponseScope2 } from './PostAquaculture200ResponseScope2';
import {
    PostAquaculture200ResponseScope2FromJSON,
    PostAquaculture200ResponseScope2FromJSONTyped,
    PostAquaculture200ResponseScope2ToJSON,
    PostAquaculture200ResponseScope2ToJSONTyped,
} from './PostAquaculture200ResponseScope2';
import type { PostSheep200ResponseIntermediateInnerIntensities } from './PostSheep200ResponseIntermediateInnerIntensities';
import {
    PostSheep200ResponseIntermediateInnerIntensitiesFromJSON,
    PostSheep200ResponseIntermediateInnerIntensitiesFromJSONTyped,
    PostSheep200ResponseIntermediateInnerIntensitiesToJSON,
    PostSheep200ResponseIntermediateInnerIntensitiesToJSONTyped,
} from './PostSheep200ResponseIntermediateInnerIntensities';
import type { PostBeef200ResponseScope3 } from './PostBeef200ResponseScope3';
import {
    PostBeef200ResponseScope3FromJSON,
    PostBeef200ResponseScope3FromJSONTyped,
    PostBeef200ResponseScope3ToJSON,
    PostBeef200ResponseScope3ToJSONTyped,
} from './PostBeef200ResponseScope3';
import type { PostSheep200ResponseNet } from './PostSheep200ResponseNet';
import {
    PostSheep200ResponseNetFromJSON,
    PostSheep200ResponseNetFromJSONTyped,
    PostSheep200ResponseNetToJSON,
    PostSheep200ResponseNetToJSONTyped,
} from './PostSheep200ResponseNet';
import type { PostAquaculture200ResponseCarbonSequestration } from './PostAquaculture200ResponseCarbonSequestration';
import {
    PostAquaculture200ResponseCarbonSequestrationFromJSON,
    PostAquaculture200ResponseCarbonSequestrationFromJSONTyped,
    PostAquaculture200ResponseCarbonSequestrationToJSON,
    PostAquaculture200ResponseCarbonSequestrationToJSONTyped,
} from './PostAquaculture200ResponseCarbonSequestration';
import type { PostBuffalo200ResponseScope1 } from './PostBuffalo200ResponseScope1';
import {
    PostBuffalo200ResponseScope1FromJSON,
    PostBuffalo200ResponseScope1FromJSONTyped,
    PostBuffalo200ResponseScope1ToJSON,
    PostBuffalo200ResponseScope1ToJSONTyped,
} from './PostBuffalo200ResponseScope1';
import type { PostSheep200ResponseIntermediateInner } from './PostSheep200ResponseIntermediateInner';
import {
    PostSheep200ResponseIntermediateInnerFromJSON,
    PostSheep200ResponseIntermediateInnerFromJSONTyped,
    PostSheep200ResponseIntermediateInnerToJSON,
    PostSheep200ResponseIntermediateInnerToJSONTyped,
} from './PostSheep200ResponseIntermediateInner';

/**
 * Emissions calculation output for the Sheep calculator
 * @export
 * @interface PostSheep200Response
 */
export interface PostSheep200Response {
    /**
     * 
     * @type {PostBuffalo200ResponseScope1}
     * @memberof PostSheep200Response
     */
    scope1: PostBuffalo200ResponseScope1;
    /**
     * 
     * @type {PostAquaculture200ResponseScope2}
     * @memberof PostSheep200Response
     */
    scope2: PostAquaculture200ResponseScope2;
    /**
     * 
     * @type {PostBeef200ResponseScope3}
     * @memberof PostSheep200Response
     */
    scope3: PostBeef200ResponseScope3;
    /**
     * 
     * @type {PostAquaculture200ResponseCarbonSequestration}
     * @memberof PostSheep200Response
     */
    carbonSequestration: PostAquaculture200ResponseCarbonSequestration;
    /**
     * 
     * @type {Array<PostSheep200ResponseIntermediateInner>}
     * @memberof PostSheep200Response
     */
    intermediate: Array<PostSheep200ResponseIntermediateInner>;
    /**
     * 
     * @type {PostSheep200ResponseNet}
     * @memberof PostSheep200Response
     */
    net: PostSheep200ResponseNet;
    /**
     * 
     * @type {PostSheep200ResponseIntermediateInnerIntensities}
     * @memberof PostSheep200Response
     */
    intensities: PostSheep200ResponseIntermediateInnerIntensities;
}

/**
 * Check if a given object implements the PostSheep200Response interface.
 */
export function instanceOfPostSheep200Response(value: object): value is PostSheep200Response {
    if (!('scope1' in value) || value['scope1'] === undefined) return false;
    if (!('scope2' in value) || value['scope2'] === undefined) return false;
    if (!('scope3' in value) || value['scope3'] === undefined) return false;
    if (!('carbonSequestration' in value) || value['carbonSequestration'] === undefined) return false;
    if (!('intermediate' in value) || value['intermediate'] === undefined) return false;
    if (!('net' in value) || value['net'] === undefined) return false;
    if (!('intensities' in value) || value['intensities'] === undefined) return false;
    return true;
}

export function PostSheep200ResponseFromJSON(json: any): PostSheep200Response {
    return PostSheep200ResponseFromJSONTyped(json, false);
}

export function PostSheep200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostSheep200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'scope1': PostBuffalo200ResponseScope1FromJSON(json['scope1']),
        'scope2': PostAquaculture200ResponseScope2FromJSON(json['scope2']),
        'scope3': PostBeef200ResponseScope3FromJSON(json['scope3']),
        'carbonSequestration': PostAquaculture200ResponseCarbonSequestrationFromJSON(json['carbonSequestration']),
        'intermediate': ((json['intermediate'] as Array<any>).map(PostSheep200ResponseIntermediateInnerFromJSON)),
        'net': PostSheep200ResponseNetFromJSON(json['net']),
        'intensities': PostSheep200ResponseIntermediateInnerIntensitiesFromJSON(json['intensities']),
    };
}

export function PostSheep200ResponseToJSON(json: any): PostSheep200Response {
    return PostSheep200ResponseToJSONTyped(json, false);
}

export function PostSheep200ResponseToJSONTyped(value?: PostSheep200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scope1': PostBuffalo200ResponseScope1ToJSON(value['scope1']),
        'scope2': PostAquaculture200ResponseScope2ToJSON(value['scope2']),
        'scope3': PostBeef200ResponseScope3ToJSON(value['scope3']),
        'carbonSequestration': PostAquaculture200ResponseCarbonSequestrationToJSON(value['carbonSequestration']),
        'intermediate': ((value['intermediate'] as Array<any>).map(PostSheep200ResponseIntermediateInnerToJSON)),
        'net': PostSheep200ResponseNetToJSON(value['net']),
        'intensities': PostSheep200ResponseIntermediateInnerIntensitiesToJSON(value['intensities']),
    };
}

