/* tslint:disable */
/* eslint-disable */
/**
 * AIA Calculator API
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Scope 3 emissions are indirect greenhouse gas emissions other than scope 2 emissions that are generated in the wider economy, in tonnes-CO2e (tonnes of carbon dioxide equivalent)
 * @export
 * @interface PostFeedlot200ResponseScope3
 */
export interface PostFeedlot200ResponseScope3 {
    /**
     * Emissions from fertiliser, in tonnes-CO2e
     * @type {number}
     * @memberof PostFeedlot200ResponseScope3
     */
    fertiliser: number;
    /**
     * Emissions from herbicide, in tonnes-CO2e
     * @type {number}
     * @memberof PostFeedlot200ResponseScope3
     */
    herbicide: number;
    /**
     * Emissions from electricity, in tonnes-CO2e
     * @type {number}
     * @memberof PostFeedlot200ResponseScope3
     */
    electricity: number;
    /**
     * Emissions from fuel, in tonnes-CO2e
     * @type {number}
     * @memberof PostFeedlot200ResponseScope3
     */
    fuel: number;
    /**
     * Emissions from lime, in tonnes-CO2e
     * @type {number}
     * @memberof PostFeedlot200ResponseScope3
     */
    lime: number;
    /**
     * Emissions from feed, in tonnes-CO2e
     * @type {number}
     * @memberof PostFeedlot200ResponseScope3
     */
    feed: number;
    /**
     * Emissions from purchased livestock, in tonnes-CO2e
     * @type {number}
     * @memberof PostFeedlot200ResponseScope3
     */
    purchaseLivestock: number;
    /**
     * Total scope 3 emissions, in tonnes-CO2e
     * @type {number}
     * @memberof PostFeedlot200ResponseScope3
     */
    total: number;
}

/**
 * Check if a given object implements the PostFeedlot200ResponseScope3 interface.
 */
export function instanceOfPostFeedlot200ResponseScope3(value: object): value is PostFeedlot200ResponseScope3 {
    if (!('fertiliser' in value) || value['fertiliser'] === undefined) return false;
    if (!('herbicide' in value) || value['herbicide'] === undefined) return false;
    if (!('electricity' in value) || value['electricity'] === undefined) return false;
    if (!('fuel' in value) || value['fuel'] === undefined) return false;
    if (!('lime' in value) || value['lime'] === undefined) return false;
    if (!('feed' in value) || value['feed'] === undefined) return false;
    if (!('purchaseLivestock' in value) || value['purchaseLivestock'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function PostFeedlot200ResponseScope3FromJSON(json: any): PostFeedlot200ResponseScope3 {
    return PostFeedlot200ResponseScope3FromJSONTyped(json, false);
}

export function PostFeedlot200ResponseScope3FromJSONTyped(json: any, ignoreDiscriminator: boolean): PostFeedlot200ResponseScope3 {
    if (json == null) {
        return json;
    }
    return {
        
        'fertiliser': json['fertiliser'],
        'herbicide': json['herbicide'],
        'electricity': json['electricity'],
        'fuel': json['fuel'],
        'lime': json['lime'],
        'feed': json['feed'],
        'purchaseLivestock': json['purchaseLivestock'],
        'total': json['total'],
    };
}

export function PostFeedlot200ResponseScope3ToJSON(json: any): PostFeedlot200ResponseScope3 {
    return PostFeedlot200ResponseScope3ToJSONTyped(json, false);
}

export function PostFeedlot200ResponseScope3ToJSONTyped(value?: PostFeedlot200ResponseScope3 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fertiliser': value['fertiliser'],
        'herbicide': value['herbicide'],
        'electricity': value['electricity'],
        'fuel': value['fuel'],
        'lime': value['lime'],
        'feed': value['feed'],
        'purchaseLivestock': value['purchaseLivestock'],
        'total': value['total'],
    };
}

