/* tslint:disable */
/* eslint-disable */
/**
 * AIA Calculator API
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostPorkRequestPorkInnerFeedProductsInner } from './PostPorkRequestPorkInnerFeedProductsInner';
import {
    PostPorkRequestPorkInnerFeedProductsInnerFromJSON,
    PostPorkRequestPorkInnerFeedProductsInnerFromJSONTyped,
    PostPorkRequestPorkInnerFeedProductsInnerToJSON,
    PostPorkRequestPorkInnerFeedProductsInnerToJSONTyped,
} from './PostPorkRequestPorkInnerFeedProductsInner';
import type { PostBeefRequestBeefInnerFertiliser } from './PostBeefRequestBeefInnerFertiliser';
import {
    PostBeefRequestBeefInnerFertiliserFromJSON,
    PostBeefRequestBeefInnerFertiliserFromJSONTyped,
    PostBeefRequestBeefInnerFertiliserToJSON,
    PostBeefRequestBeefInnerFertiliserToJSONTyped,
} from './PostBeefRequestBeefInnerFertiliser';
import type { PostPorkRequestPorkInnerClasses } from './PostPorkRequestPorkInnerClasses';
import {
    PostPorkRequestPorkInnerClassesFromJSON,
    PostPorkRequestPorkInnerClassesFromJSONTyped,
    PostPorkRequestPorkInnerClassesToJSON,
    PostPorkRequestPorkInnerClassesToJSONTyped,
} from './PostPorkRequestPorkInnerClasses';

/**
 * Input data required for a single Pork enterprise
 * @export
 * @interface PostPorkRequestPorkInner
 */
export interface PostPorkRequestPorkInner {
    /**
     * Unique identifier for this Pork activity
     * @type {string}
     * @memberof PostPorkRequestPorkInner
     */
    id?: string;
    /**
     * 
     * @type {PostPorkRequestPorkInnerClasses}
     * @memberof PostPorkRequestPorkInner
     */
    classes: PostPorkRequestPorkInnerClasses;
    /**
     * Lime applied in tonnes
     * @type {number}
     * @memberof PostPorkRequestPorkInner
     */
    limestone: number;
    /**
     * Fraction of lime as limestone vs dolomite, between 0 and 1
     * @type {number}
     * @memberof PostPorkRequestPorkInner
     */
    limestoneFraction: number;
    /**
     * 
     * @type {PostBeefRequestBeefInnerFertiliser}
     * @memberof PostPorkRequestPorkInner
     */
    fertiliser: PostBeefRequestBeefInnerFertiliser;
    /**
     * Diesel usage in L (litres)
     * @type {number}
     * @memberof PostPorkRequestPorkInner
     */
    diesel: number;
    /**
     * Petrol usage in L (litres)
     * @type {number}
     * @memberof PostPorkRequestPorkInner
     */
    petrol: number;
    /**
     * LPG Fuel usage in L (litres)
     * @type {number}
     * @memberof PostPorkRequestPorkInner
     */
    lpg: number;
    /**
     * Source of electricity
     * @type {string}
     * @memberof PostPorkRequestPorkInner
     */
    electricitySource: PostPorkRequestPorkInnerElectricitySourceEnum;
    /**
     * Percent of total electricity usage that is drawn from renewable sources, between 0 and 1. Unused if `electricitySource` is `Renewable`
     * @type {number}
     * @memberof PostPorkRequestPorkInner
     */
    electricityRenewable: number;
    /**
     * Electricity use in KWh (kilowatt hours)
     * @type {number}
     * @memberof PostPorkRequestPorkInner
     */
    electricityUse: number;
    /**
     * Total amount of active ingredients of from herbicide (Paraquat, Diquat, Glyphosate) in kg (kilograms)
     * @type {number}
     * @memberof PostPorkRequestPorkInner
     */
    herbicide: number;
    /**
     * Total amount of active ingredients of from other herbicides in kg (kilograms)
     * @type {number}
     * @memberof PostPorkRequestPorkInner
     */
    herbicideOther: number;
    /**
     * Hay, barley, straw, etc. purchased for pig bedding, in tonnes
     * @type {number}
     * @memberof PostPorkRequestPorkInner
     */
    beddingHayBarleyStraw: number;
    /**
     * 
     * @type {Array<PostPorkRequestPorkInnerFeedProductsInner>}
     * @memberof PostPorkRequestPorkInner
     */
    feedProducts: Array<PostPorkRequestPorkInnerFeedProductsInner>;
}


/**
 * @export
 */
export const PostPorkRequestPorkInnerElectricitySourceEnum = {
    StateGrid: 'State Grid',
    Renewable: 'Renewable'
} as const;
export type PostPorkRequestPorkInnerElectricitySourceEnum = typeof PostPorkRequestPorkInnerElectricitySourceEnum[keyof typeof PostPorkRequestPorkInnerElectricitySourceEnum];


/**
 * Check if a given object implements the PostPorkRequestPorkInner interface.
 */
export function instanceOfPostPorkRequestPorkInner(value: object): value is PostPorkRequestPorkInner {
    if (!('classes' in value) || value['classes'] === undefined) return false;
    if (!('limestone' in value) || value['limestone'] === undefined) return false;
    if (!('limestoneFraction' in value) || value['limestoneFraction'] === undefined) return false;
    if (!('fertiliser' in value) || value['fertiliser'] === undefined) return false;
    if (!('diesel' in value) || value['diesel'] === undefined) return false;
    if (!('petrol' in value) || value['petrol'] === undefined) return false;
    if (!('lpg' in value) || value['lpg'] === undefined) return false;
    if (!('electricitySource' in value) || value['electricitySource'] === undefined) return false;
    if (!('electricityRenewable' in value) || value['electricityRenewable'] === undefined) return false;
    if (!('electricityUse' in value) || value['electricityUse'] === undefined) return false;
    if (!('herbicide' in value) || value['herbicide'] === undefined) return false;
    if (!('herbicideOther' in value) || value['herbicideOther'] === undefined) return false;
    if (!('beddingHayBarleyStraw' in value) || value['beddingHayBarleyStraw'] === undefined) return false;
    if (!('feedProducts' in value) || value['feedProducts'] === undefined) return false;
    return true;
}

export function PostPorkRequestPorkInnerFromJSON(json: any): PostPorkRequestPorkInner {
    return PostPorkRequestPorkInnerFromJSONTyped(json, false);
}

export function PostPorkRequestPorkInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostPorkRequestPorkInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'classes': PostPorkRequestPorkInnerClassesFromJSON(json['classes']),
        'limestone': json['limestone'],
        'limestoneFraction': json['limestoneFraction'],
        'fertiliser': PostBeefRequestBeefInnerFertiliserFromJSON(json['fertiliser']),
        'diesel': json['diesel'],
        'petrol': json['petrol'],
        'lpg': json['lpg'],
        'electricitySource': json['electricitySource'],
        'electricityRenewable': json['electricityRenewable'],
        'electricityUse': json['electricityUse'],
        'herbicide': json['herbicide'],
        'herbicideOther': json['herbicideOther'],
        'beddingHayBarleyStraw': json['beddingHayBarleyStraw'],
        'feedProducts': ((json['feedProducts'] as Array<any>).map(PostPorkRequestPorkInnerFeedProductsInnerFromJSON)),
    };
}

export function PostPorkRequestPorkInnerToJSON(json: any): PostPorkRequestPorkInner {
    return PostPorkRequestPorkInnerToJSONTyped(json, false);
}

export function PostPorkRequestPorkInnerToJSONTyped(value?: PostPorkRequestPorkInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'classes': PostPorkRequestPorkInnerClassesToJSON(value['classes']),
        'limestone': value['limestone'],
        'limestoneFraction': value['limestoneFraction'],
        'fertiliser': PostBeefRequestBeefInnerFertiliserToJSON(value['fertiliser']),
        'diesel': value['diesel'],
        'petrol': value['petrol'],
        'lpg': value['lpg'],
        'electricitySource': value['electricitySource'],
        'electricityRenewable': value['electricityRenewable'],
        'electricityUse': value['electricityUse'],
        'herbicide': value['herbicide'],
        'herbicideOther': value['herbicideOther'],
        'beddingHayBarleyStraw': value['beddingHayBarleyStraw'],
        'feedProducts': ((value['feedProducts'] as Array<any>).map(PostPorkRequestPorkInnerFeedProductsInnerToJSON)),
    };
}

