/* tslint:disable */
/* eslint-disable */
/**
 * AIA Calculator API
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostPorkRequestPorkInnerClassesSowsManure } from './PostPorkRequestPorkInnerClassesSowsManure';
import {
    PostPorkRequestPorkInnerClassesSowsManureFromJSON,
    PostPorkRequestPorkInnerClassesSowsManureFromJSONTyped,
    PostPorkRequestPorkInnerClassesSowsManureToJSON,
    PostPorkRequestPorkInnerClassesSowsManureToJSONTyped,
} from './PostPorkRequestPorkInnerClassesSowsManure';
import type { PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInner } from './PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInner';
import {
    PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInnerFromJSON,
    PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInnerFromJSONTyped,
    PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInnerToJSON,
    PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInnerToJSONTyped,
} from './PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInner';

/**
 * Suckers
 * @export
 * @interface PostPorkRequestPorkInnerClassesSuckers
 */
export interface PostPorkRequestPorkInnerClassesSuckers {
    /**
     * Pig numbers in autumn
     * @type {number}
     * @memberof PostPorkRequestPorkInnerClassesSuckers
     */
    autumn: number;
    /**
     * Pig numbers in winter
     * @type {number}
     * @memberof PostPorkRequestPorkInnerClassesSuckers
     */
    winter: number;
    /**
     * Pig numbers in spring
     * @type {number}
     * @memberof PostPorkRequestPorkInnerClassesSuckers
     */
    spring: number;
    /**
     * Pig numbers in summer
     * @type {number}
     * @memberof PostPorkRequestPorkInnerClassesSuckers
     */
    summer: number;
    /**
     * Number of animals sold (head)
     * @type {number}
     * @memberof PostPorkRequestPorkInnerClassesSuckers
     */
    headSold: number;
    /**
     * Weight at sale, in liveweight kg/head (kilogram per head)
     * @type {number}
     * @memberof PostPorkRequestPorkInnerClassesSuckers
     */
    saleWeight: number;
    /**
     * 
     * @type {Array<PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInner>}
     * @memberof PostPorkRequestPorkInnerClassesSuckers
     */
    purchases?: Array<PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInner>;
    /**
     * 
     * @type {PostPorkRequestPorkInnerClassesSowsManure}
     * @memberof PostPorkRequestPorkInnerClassesSuckers
     */
    manure: PostPorkRequestPorkInnerClassesSowsManure;
}

/**
 * Check if a given object implements the PostPorkRequestPorkInnerClassesSuckers interface.
 */
export function instanceOfPostPorkRequestPorkInnerClassesSuckers(value: object): value is PostPorkRequestPorkInnerClassesSuckers {
    if (!('autumn' in value) || value['autumn'] === undefined) return false;
    if (!('winter' in value) || value['winter'] === undefined) return false;
    if (!('spring' in value) || value['spring'] === undefined) return false;
    if (!('summer' in value) || value['summer'] === undefined) return false;
    if (!('headSold' in value) || value['headSold'] === undefined) return false;
    if (!('saleWeight' in value) || value['saleWeight'] === undefined) return false;
    if (!('manure' in value) || value['manure'] === undefined) return false;
    return true;
}

export function PostPorkRequestPorkInnerClassesSuckersFromJSON(json: any): PostPorkRequestPorkInnerClassesSuckers {
    return PostPorkRequestPorkInnerClassesSuckersFromJSONTyped(json, false);
}

export function PostPorkRequestPorkInnerClassesSuckersFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostPorkRequestPorkInnerClassesSuckers {
    if (json == null) {
        return json;
    }
    return {
        
        'autumn': json['autumn'],
        'winter': json['winter'],
        'spring': json['spring'],
        'summer': json['summer'],
        'headSold': json['headSold'],
        'saleWeight': json['saleWeight'],
        'purchases': json['purchases'] == null ? undefined : ((json['purchases'] as Array<any>).map(PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInnerFromJSON)),
        'manure': PostPorkRequestPorkInnerClassesSowsManureFromJSON(json['manure']),
    };
}

export function PostPorkRequestPorkInnerClassesSuckersToJSON(json: any): PostPorkRequestPorkInnerClassesSuckers {
    return PostPorkRequestPorkInnerClassesSuckersToJSONTyped(json, false);
}

export function PostPorkRequestPorkInnerClassesSuckersToJSONTyped(value?: PostPorkRequestPorkInnerClassesSuckers | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'autumn': value['autumn'],
        'winter': value['winter'],
        'spring': value['spring'],
        'summer': value['summer'],
        'headSold': value['headSold'],
        'saleWeight': value['saleWeight'],
        'purchases': value['purchases'] == null ? undefined : ((value['purchases'] as Array<any>).map(PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInnerToJSON)),
        'manure': PostPorkRequestPorkInnerClassesSowsManureToJSON(value['manure']),
    };
}

