/* tslint:disable */
/* eslint-disable */
/**
 * AIA Calculator API
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostBuffaloRequestBuffalosInnerClassesBullsAutumn } from './PostBuffaloRequestBuffalosInnerClassesBullsAutumn';
import {
    PostBuffaloRequestBuffalosInnerClassesBullsAutumnFromJSON,
    PostBuffaloRequestBuffalosInnerClassesBullsAutumnFromJSONTyped,
    PostBuffaloRequestBuffalosInnerClassesBullsAutumnToJSON,
    PostBuffaloRequestBuffalosInnerClassesBullsAutumnToJSONTyped,
} from './PostBuffaloRequestBuffalosInnerClassesBullsAutumn';
import type { PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInner } from './PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInner';
import {
    PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInnerFromJSON,
    PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInnerFromJSONTyped,
    PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInnerToJSON,
    PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInnerToJSONTyped,
} from './PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInner';

/**
 * trade maiden breeding does/nannies
 * @export
 * @interface PostGoatRequestGoatsInnerClassesTradeMaidenBreedingDoesNannies
 */
export interface PostGoatRequestGoatsInnerClassesTradeMaidenBreedingDoesNannies {
    /**
     * 
     * @type {PostBuffaloRequestBuffalosInnerClassesBullsAutumn}
     * @memberof PostGoatRequestGoatsInnerClassesTradeMaidenBreedingDoesNannies
     */
    autumn: PostBuffaloRequestBuffalosInnerClassesBullsAutumn;
    /**
     * 
     * @type {PostBuffaloRequestBuffalosInnerClassesBullsAutumn}
     * @memberof PostGoatRequestGoatsInnerClassesTradeMaidenBreedingDoesNannies
     */
    winter: PostBuffaloRequestBuffalosInnerClassesBullsAutumn;
    /**
     * 
     * @type {PostBuffaloRequestBuffalosInnerClassesBullsAutumn}
     * @memberof PostGoatRequestGoatsInnerClassesTradeMaidenBreedingDoesNannies
     */
    spring: PostBuffaloRequestBuffalosInnerClassesBullsAutumn;
    /**
     * 
     * @type {PostBuffaloRequestBuffalosInnerClassesBullsAutumn}
     * @memberof PostGoatRequestGoatsInnerClassesTradeMaidenBreedingDoesNannies
     */
    summer: PostBuffaloRequestBuffalosInnerClassesBullsAutumn;
    /**
     * Number of animals sold (head)
     * @type {number}
     * @memberof PostGoatRequestGoatsInnerClassesTradeMaidenBreedingDoesNannies
     */
    headSold: number;
    /**
     * Weight at sale, in liveweight kg/head (kilogram per head)
     * @type {number}
     * @memberof PostGoatRequestGoatsInnerClassesTradeMaidenBreedingDoesNannies
     */
    saleWeight: number;
    /**
     * Number of goat shorn, in head
     * @type {number}
     * @memberof PostGoatRequestGoatsInnerClassesTradeMaidenBreedingDoesNannies
     */
    headShorn: number;
    /**
     * Weight of wool shorn, in kg/head (kilogram per head)
     * @type {number}
     * @memberof PostGoatRequestGoatsInnerClassesTradeMaidenBreedingDoesNannies
     */
    woolShorn: number;
    /**
     * Percentage of clean wool from weight of yield, from 0 to 100
     * @type {number}
     * @memberof PostGoatRequestGoatsInnerClassesTradeMaidenBreedingDoesNannies
     */
    cleanWoolYield: number;
    /**
     * 
     * @type {Array<PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInner>}
     * @memberof PostGoatRequestGoatsInnerClassesTradeMaidenBreedingDoesNannies
     */
    purchases?: Array<PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInner>;
}

/**
 * Check if a given object implements the PostGoatRequestGoatsInnerClassesTradeMaidenBreedingDoesNannies interface.
 */
export function instanceOfPostGoatRequestGoatsInnerClassesTradeMaidenBreedingDoesNannies(value: object): value is PostGoatRequestGoatsInnerClassesTradeMaidenBreedingDoesNannies {
    if (!('autumn' in value) || value['autumn'] === undefined) return false;
    if (!('winter' in value) || value['winter'] === undefined) return false;
    if (!('spring' in value) || value['spring'] === undefined) return false;
    if (!('summer' in value) || value['summer'] === undefined) return false;
    if (!('headSold' in value) || value['headSold'] === undefined) return false;
    if (!('saleWeight' in value) || value['saleWeight'] === undefined) return false;
    if (!('headShorn' in value) || value['headShorn'] === undefined) return false;
    if (!('woolShorn' in value) || value['woolShorn'] === undefined) return false;
    if (!('cleanWoolYield' in value) || value['cleanWoolYield'] === undefined) return false;
    return true;
}

export function PostGoatRequestGoatsInnerClassesTradeMaidenBreedingDoesNanniesFromJSON(json: any): PostGoatRequestGoatsInnerClassesTradeMaidenBreedingDoesNannies {
    return PostGoatRequestGoatsInnerClassesTradeMaidenBreedingDoesNanniesFromJSONTyped(json, false);
}

export function PostGoatRequestGoatsInnerClassesTradeMaidenBreedingDoesNanniesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostGoatRequestGoatsInnerClassesTradeMaidenBreedingDoesNannies {
    if (json == null) {
        return json;
    }
    return {
        
        'autumn': PostBuffaloRequestBuffalosInnerClassesBullsAutumnFromJSON(json['autumn']),
        'winter': PostBuffaloRequestBuffalosInnerClassesBullsAutumnFromJSON(json['winter']),
        'spring': PostBuffaloRequestBuffalosInnerClassesBullsAutumnFromJSON(json['spring']),
        'summer': PostBuffaloRequestBuffalosInnerClassesBullsAutumnFromJSON(json['summer']),
        'headSold': json['headSold'],
        'saleWeight': json['saleWeight'],
        'headShorn': json['headShorn'],
        'woolShorn': json['woolShorn'],
        'cleanWoolYield': json['cleanWoolYield'],
        'purchases': json['purchases'] == null ? undefined : ((json['purchases'] as Array<any>).map(PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInnerFromJSON)),
    };
}

export function PostGoatRequestGoatsInnerClassesTradeMaidenBreedingDoesNanniesToJSON(json: any): PostGoatRequestGoatsInnerClassesTradeMaidenBreedingDoesNannies {
    return PostGoatRequestGoatsInnerClassesTradeMaidenBreedingDoesNanniesToJSONTyped(json, false);
}

export function PostGoatRequestGoatsInnerClassesTradeMaidenBreedingDoesNanniesToJSONTyped(value?: PostGoatRequestGoatsInnerClassesTradeMaidenBreedingDoesNannies | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'autumn': PostBuffaloRequestBuffalosInnerClassesBullsAutumnToJSON(value['autumn']),
        'winter': PostBuffaloRequestBuffalosInnerClassesBullsAutumnToJSON(value['winter']),
        'spring': PostBuffaloRequestBuffalosInnerClassesBullsAutumnToJSON(value['spring']),
        'summer': PostBuffaloRequestBuffalosInnerClassesBullsAutumnToJSON(value['summer']),
        'headSold': value['headSold'],
        'saleWeight': value['saleWeight'],
        'headShorn': value['headShorn'],
        'woolShorn': value['woolShorn'],
        'cleanWoolYield': value['cleanWoolYield'],
        'purchases': value['purchases'] == null ? undefined : ((value['purchases'] as Array<any>).map(PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInnerToJSON)),
    };
}

