/* tslint:disable */
/* eslint-disable */
/**
 * AIA Calculator API
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostGrainsRequestCropsInner } from './PostGrainsRequestCropsInner';
import {
    PostGrainsRequestCropsInnerFromJSON,
    PostGrainsRequestCropsInnerFromJSONTyped,
    PostGrainsRequestCropsInnerToJSON,
    PostGrainsRequestCropsInnerToJSONTyped,
} from './PostGrainsRequestCropsInner';
import type { PostGrainsRequestVegetationInner } from './PostGrainsRequestVegetationInner';
import {
    PostGrainsRequestVegetationInnerFromJSON,
    PostGrainsRequestVegetationInnerFromJSONTyped,
    PostGrainsRequestVegetationInnerToJSON,
    PostGrainsRequestVegetationInnerToJSONTyped,
} from './PostGrainsRequestVegetationInner';

/**
 * Input data required for a single Grains enterprise
 * @export
 * @interface PostGrainsRequest
 */
export interface PostGrainsRequest {
    /**
     * Unique identifier for this Grains activity
     * @type {string}
     * @memberof PostGrainsRequest
     */
    id?: string;
    /**
     * What state the location is in. Note: Western Australia is split up into two regions, `wa_nw` is North-West Western Australia, `wa_sw` is South-West Western Australia
     * @type {string}
     * @memberof PostGrainsRequest
     */
    state: PostGrainsRequestStateEnum;
    /**
     * 
     * @type {Array<PostGrainsRequestCropsInner>}
     * @memberof PostGrainsRequest
     */
    crops: Array<PostGrainsRequestCropsInner>;
    /**
     * Percent of total electricity usage that is drawn from renewable sources, between 0 and 1. Unused if `electricitySource` is `Renewable`
     * @type {number}
     * @memberof PostGrainsRequest
     */
    electricityRenewable: number;
    /**
     * Electricity use in KWh (kilowatt hours)
     * @type {number}
     * @memberof PostGrainsRequest
     */
    electricityUse: number;
    /**
     * 
     * @type {Array<PostGrainsRequestVegetationInner>}
     * @memberof PostGrainsRequest
     */
    vegetation: Array<PostGrainsRequestVegetationInner>;
}


/**
 * @export
 */
export const PostGrainsRequestStateEnum = {
    Nsw: 'nsw',
    Vic: 'vic',
    Qld: 'qld',
    Sa: 'sa',
    WaNw: 'wa_nw',
    WaSw: 'wa_sw',
    Tas: 'tas',
    Nt: 'nt',
    Act: 'act'
} as const;
export type PostGrainsRequestStateEnum = typeof PostGrainsRequestStateEnum[keyof typeof PostGrainsRequestStateEnum];


/**
 * Check if a given object implements the PostGrainsRequest interface.
 */
export function instanceOfPostGrainsRequest(value: object): value is PostGrainsRequest {
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('crops' in value) || value['crops'] === undefined) return false;
    if (!('electricityRenewable' in value) || value['electricityRenewable'] === undefined) return false;
    if (!('electricityUse' in value) || value['electricityUse'] === undefined) return false;
    if (!('vegetation' in value) || value['vegetation'] === undefined) return false;
    return true;
}

export function PostGrainsRequestFromJSON(json: any): PostGrainsRequest {
    return PostGrainsRequestFromJSONTyped(json, false);
}

export function PostGrainsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostGrainsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'state': json['state'],
        'crops': ((json['crops'] as Array<any>).map(PostGrainsRequestCropsInnerFromJSON)),
        'electricityRenewable': json['electricityRenewable'],
        'electricityUse': json['electricityUse'],
        'vegetation': ((json['vegetation'] as Array<any>).map(PostGrainsRequestVegetationInnerFromJSON)),
    };
}

export function PostGrainsRequestToJSON(json: any): PostGrainsRequest {
    return PostGrainsRequestToJSONTyped(json, false);
}

export function PostGrainsRequestToJSONTyped(value?: PostGrainsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'state': value['state'],
        'crops': ((value['crops'] as Array<any>).map(PostGrainsRequestCropsInnerToJSON)),
        'electricityRenewable': value['electricityRenewable'],
        'electricityUse': value['electricityUse'],
        'vegetation': ((value['vegetation'] as Array<any>).map(PostGrainsRequestVegetationInnerToJSON)),
    };
}

