/* tslint:disable */
/* eslint-disable */
/**
 * AIA Calculator API
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostDairyRequestDairyInnerClassesMilkingCowsAutumn } from './PostDairyRequestDairyInnerClassesMilkingCowsAutumn';
import {
    PostDairyRequestDairyInnerClassesMilkingCowsAutumnFromJSON,
    PostDairyRequestDairyInnerClassesMilkingCowsAutumnFromJSONTyped,
    PostDairyRequestDairyInnerClassesMilkingCowsAutumnToJSON,
    PostDairyRequestDairyInnerClassesMilkingCowsAutumnToJSONTyped,
} from './PostDairyRequestDairyInnerClassesMilkingCowsAutumn';

/**
 * Dairy bulls whose age is greater than 1 year old
 * @export
 * @interface PostDairyRequestDairyInnerClassesDairyBullsGt1
 */
export interface PostDairyRequestDairyInnerClassesDairyBullsGt1 {
    /**
     * 
     * @type {PostDairyRequestDairyInnerClassesMilkingCowsAutumn}
     * @memberof PostDairyRequestDairyInnerClassesDairyBullsGt1
     */
    autumn: PostDairyRequestDairyInnerClassesMilkingCowsAutumn;
    /**
     * 
     * @type {PostDairyRequestDairyInnerClassesMilkingCowsAutumn}
     * @memberof PostDairyRequestDairyInnerClassesDairyBullsGt1
     */
    winter: PostDairyRequestDairyInnerClassesMilkingCowsAutumn;
    /**
     * 
     * @type {PostDairyRequestDairyInnerClassesMilkingCowsAutumn}
     * @memberof PostDairyRequestDairyInnerClassesDairyBullsGt1
     */
    spring: PostDairyRequestDairyInnerClassesMilkingCowsAutumn;
    /**
     * 
     * @type {PostDairyRequestDairyInnerClassesMilkingCowsAutumn}
     * @memberof PostDairyRequestDairyInnerClassesDairyBullsGt1
     */
    summer: PostDairyRequestDairyInnerClassesMilkingCowsAutumn;
}

/**
 * Check if a given object implements the PostDairyRequestDairyInnerClassesDairyBullsGt1 interface.
 */
export function instanceOfPostDairyRequestDairyInnerClassesDairyBullsGt1(value: object): value is PostDairyRequestDairyInnerClassesDairyBullsGt1 {
    if (!('autumn' in value) || value['autumn'] === undefined) return false;
    if (!('winter' in value) || value['winter'] === undefined) return false;
    if (!('spring' in value) || value['spring'] === undefined) return false;
    if (!('summer' in value) || value['summer'] === undefined) return false;
    return true;
}

export function PostDairyRequestDairyInnerClassesDairyBullsGt1FromJSON(json: any): PostDairyRequestDairyInnerClassesDairyBullsGt1 {
    return PostDairyRequestDairyInnerClassesDairyBullsGt1FromJSONTyped(json, false);
}

export function PostDairyRequestDairyInnerClassesDairyBullsGt1FromJSONTyped(json: any, ignoreDiscriminator: boolean): PostDairyRequestDairyInnerClassesDairyBullsGt1 {
    if (json == null) {
        return json;
    }
    return {
        
        'autumn': PostDairyRequestDairyInnerClassesMilkingCowsAutumnFromJSON(json['autumn']),
        'winter': PostDairyRequestDairyInnerClassesMilkingCowsAutumnFromJSON(json['winter']),
        'spring': PostDairyRequestDairyInnerClassesMilkingCowsAutumnFromJSON(json['spring']),
        'summer': PostDairyRequestDairyInnerClassesMilkingCowsAutumnFromJSON(json['summer']),
    };
}

export function PostDairyRequestDairyInnerClassesDairyBullsGt1ToJSON(json: any): PostDairyRequestDairyInnerClassesDairyBullsGt1 {
    return PostDairyRequestDairyInnerClassesDairyBullsGt1ToJSONTyped(json, false);
}

export function PostDairyRequestDairyInnerClassesDairyBullsGt1ToJSONTyped(value?: PostDairyRequestDairyInnerClassesDairyBullsGt1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'autumn': PostDairyRequestDairyInnerClassesMilkingCowsAutumnToJSON(value['autumn']),
        'winter': PostDairyRequestDairyInnerClassesMilkingCowsAutumnToJSON(value['winter']),
        'spring': PostDairyRequestDairyInnerClassesMilkingCowsAutumnToJSON(value['spring']),
        'summer': PostDairyRequestDairyInnerClassesMilkingCowsAutumnToJSON(value['summer']),
    };
}

