/* tslint:disable */
/* eslint-disable */
/**
 * AIA Calculator API
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostAquaculture200ResponseScope2 } from './PostAquaculture200ResponseScope2';
import {
    PostAquaculture200ResponseScope2FromJSON,
    PostAquaculture200ResponseScope2FromJSONTyped,
    PostAquaculture200ResponseScope2ToJSON,
    PostAquaculture200ResponseScope2ToJSONTyped,
} from './PostAquaculture200ResponseScope2';
import type { PostCotton200ResponseNet } from './PostCotton200ResponseNet';
import {
    PostCotton200ResponseNetFromJSON,
    PostCotton200ResponseNetFromJSONTyped,
    PostCotton200ResponseNetToJSON,
    PostCotton200ResponseNetToJSONTyped,
} from './PostCotton200ResponseNet';
import type { PostSugar200ResponseIntermediateInnerIntensities } from './PostSugar200ResponseIntermediateInnerIntensities';
import {
    PostSugar200ResponseIntermediateInnerIntensitiesFromJSON,
    PostSugar200ResponseIntermediateInnerIntensitiesFromJSONTyped,
    PostSugar200ResponseIntermediateInnerIntensitiesToJSON,
    PostSugar200ResponseIntermediateInnerIntensitiesToJSONTyped,
} from './PostSugar200ResponseIntermediateInnerIntensities';
import type { PostAquaculture200ResponseCarbonSequestration } from './PostAquaculture200ResponseCarbonSequestration';
import {
    PostAquaculture200ResponseCarbonSequestrationFromJSON,
    PostAquaculture200ResponseCarbonSequestrationFromJSONTyped,
    PostAquaculture200ResponseCarbonSequestrationToJSON,
    PostAquaculture200ResponseCarbonSequestrationToJSONTyped,
} from './PostAquaculture200ResponseCarbonSequestration';
import type { PostSugar200ResponseIntermediateInner } from './PostSugar200ResponseIntermediateInner';
import {
    PostSugar200ResponseIntermediateInnerFromJSON,
    PostSugar200ResponseIntermediateInnerFromJSONTyped,
    PostSugar200ResponseIntermediateInnerToJSON,
    PostSugar200ResponseIntermediateInnerToJSONTyped,
} from './PostSugar200ResponseIntermediateInner';
import type { PostCotton200ResponseScope3 } from './PostCotton200ResponseScope3';
import {
    PostCotton200ResponseScope3FromJSON,
    PostCotton200ResponseScope3FromJSONTyped,
    PostCotton200ResponseScope3ToJSON,
    PostCotton200ResponseScope3ToJSONTyped,
} from './PostCotton200ResponseScope3';
import type { PostCotton200ResponseScope1 } from './PostCotton200ResponseScope1';
import {
    PostCotton200ResponseScope1FromJSON,
    PostCotton200ResponseScope1FromJSONTyped,
    PostCotton200ResponseScope1ToJSON,
    PostCotton200ResponseScope1ToJSONTyped,
} from './PostCotton200ResponseScope1';

/**
 * Emissions calculation output for the Sugar calculator
 * @export
 * @interface PostSugar200Response
 */
export interface PostSugar200Response {
    /**
     * 
     * @type {PostCotton200ResponseScope1}
     * @memberof PostSugar200Response
     */
    scope1: PostCotton200ResponseScope1;
    /**
     * 
     * @type {PostAquaculture200ResponseScope2}
     * @memberof PostSugar200Response
     */
    scope2: PostAquaculture200ResponseScope2;
    /**
     * 
     * @type {PostCotton200ResponseScope3}
     * @memberof PostSugar200Response
     */
    scope3: PostCotton200ResponseScope3;
    /**
     * 
     * @type {PostAquaculture200ResponseCarbonSequestration}
     * @memberof PostSugar200Response
     */
    carbonSequestration: PostAquaculture200ResponseCarbonSequestration;
    /**
     * 
     * @type {Array<PostSugar200ResponseIntermediateInner>}
     * @memberof PostSugar200Response
     */
    intermediate: Array<PostSugar200ResponseIntermediateInner>;
    /**
     * 
     * @type {PostCotton200ResponseNet}
     * @memberof PostSugar200Response
     */
    net: PostCotton200ResponseNet;
    /**
     * Emissions intensity for each crop (in order), in t-CO2e/t crop
     * @type {Array<PostSugar200ResponseIntermediateInnerIntensities>}
     * @memberof PostSugar200Response
     */
    intensities: Array<PostSugar200ResponseIntermediateInnerIntensities>;
}

/**
 * Check if a given object implements the PostSugar200Response interface.
 */
export function instanceOfPostSugar200Response(value: object): value is PostSugar200Response {
    if (!('scope1' in value) || value['scope1'] === undefined) return false;
    if (!('scope2' in value) || value['scope2'] === undefined) return false;
    if (!('scope3' in value) || value['scope3'] === undefined) return false;
    if (!('carbonSequestration' in value) || value['carbonSequestration'] === undefined) return false;
    if (!('intermediate' in value) || value['intermediate'] === undefined) return false;
    if (!('net' in value) || value['net'] === undefined) return false;
    if (!('intensities' in value) || value['intensities'] === undefined) return false;
    return true;
}

export function PostSugar200ResponseFromJSON(json: any): PostSugar200Response {
    return PostSugar200ResponseFromJSONTyped(json, false);
}

export function PostSugar200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostSugar200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'scope1': PostCotton200ResponseScope1FromJSON(json['scope1']),
        'scope2': PostAquaculture200ResponseScope2FromJSON(json['scope2']),
        'scope3': PostCotton200ResponseScope3FromJSON(json['scope3']),
        'carbonSequestration': PostAquaculture200ResponseCarbonSequestrationFromJSON(json['carbonSequestration']),
        'intermediate': ((json['intermediate'] as Array<any>).map(PostSugar200ResponseIntermediateInnerFromJSON)),
        'net': PostCotton200ResponseNetFromJSON(json['net']),
        'intensities': ((json['intensities'] as Array<any>).map(PostSugar200ResponseIntermediateInnerIntensitiesFromJSON)),
    };
}

export function PostSugar200ResponseToJSON(json: any): PostSugar200Response {
    return PostSugar200ResponseToJSONTyped(json, false);
}

export function PostSugar200ResponseToJSONTyped(value?: PostSugar200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scope1': PostCotton200ResponseScope1ToJSON(value['scope1']),
        'scope2': PostAquaculture200ResponseScope2ToJSON(value['scope2']),
        'scope3': PostCotton200ResponseScope3ToJSON(value['scope3']),
        'carbonSequestration': PostAquaculture200ResponseCarbonSequestrationToJSON(value['carbonSequestration']),
        'intermediate': ((value['intermediate'] as Array<any>).map(PostSugar200ResponseIntermediateInnerToJSON)),
        'net': PostCotton200ResponseNetToJSON(value['net']),
        'intensities': ((value['intensities'] as Array<any>).map(PostSugar200ResponseIntermediateInnerIntensitiesToJSON)),
    };
}

