/* tslint:disable */
/* eslint-disable */
/**
 * AIA Calculator API
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostDairyRequestDairyInner } from './PostDairyRequestDairyInner';
import {
    PostDairyRequestDairyInnerFromJSON,
    PostDairyRequestDairyInnerFromJSONTyped,
    PostDairyRequestDairyInnerToJSON,
    PostDairyRequestDairyInnerToJSONTyped,
} from './PostDairyRequestDairyInner';
import type { PostDairyRequestVegetationInner } from './PostDairyRequestVegetationInner';
import {
    PostDairyRequestVegetationInnerFromJSON,
    PostDairyRequestVegetationInnerFromJSONTyped,
    PostDairyRequestVegetationInnerToJSON,
    PostDairyRequestVegetationInnerToJSONTyped,
} from './PostDairyRequestVegetationInner';

/**
 * Input data required for a single Dairy enterprise
 * @export
 * @interface PostDairyRequest
 */
export interface PostDairyRequest {
    /**
     * Unique identifier for this Dairy activity
     * @type {string}
     * @memberof PostDairyRequest
     */
    id?: string;
    /**
     * What state the location is in. Note: Western Australia is split up into two regions, `wa_nw` is North-West Western Australia, `wa_sw` is South-West Western Australia
     * @type {string}
     * @memberof PostDairyRequest
     */
    state: PostDairyRequestStateEnum;
    /**
     * Is there enough rainfall to drain through the soil profile. Note: this is typically above 600mm
     * @type {boolean}
     * @memberof PostDairyRequest
     */
    rainfallAbove600: boolean;
    /**
     * Production system
     * @type {string}
     * @memberof PostDairyRequest
     */
    productionSystem: PostDairyRequestProductionSystemEnum;
    /**
     * 
     * @type {Array<PostDairyRequestDairyInner>}
     * @memberof PostDairyRequest
     */
    dairy: Array<PostDairyRequestDairyInner>;
    /**
     * 
     * @type {Array<PostDairyRequestVegetationInner>}
     * @memberof PostDairyRequest
     */
    vegetation: Array<PostDairyRequestVegetationInner>;
}


/**
 * @export
 */
export const PostDairyRequestStateEnum = {
    Nsw: 'nsw',
    Vic: 'vic',
    Qld: 'qld',
    Sa: 'sa',
    WaNw: 'wa_nw',
    WaSw: 'wa_sw',
    Tas: 'tas',
    Nt: 'nt',
    Act: 'act'
} as const;
export type PostDairyRequestStateEnum = typeof PostDairyRequestStateEnum[keyof typeof PostDairyRequestStateEnum];

/**
 * @export
 */
export const PostDairyRequestProductionSystemEnum = {
    NonIrrigatedCrop: 'Non-irrigated Crop',
    IrrigatedCrop: 'Irrigated Crop',
    IrrigatedPasture: 'Irrigated Pasture',
    NonIrrigatedPasture: 'Non-irrigated Pasture'
} as const;
export type PostDairyRequestProductionSystemEnum = typeof PostDairyRequestProductionSystemEnum[keyof typeof PostDairyRequestProductionSystemEnum];


/**
 * Check if a given object implements the PostDairyRequest interface.
 */
export function instanceOfPostDairyRequest(value: object): value is PostDairyRequest {
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('rainfallAbove600' in value) || value['rainfallAbove600'] === undefined) return false;
    if (!('productionSystem' in value) || value['productionSystem'] === undefined) return false;
    if (!('dairy' in value) || value['dairy'] === undefined) return false;
    if (!('vegetation' in value) || value['vegetation'] === undefined) return false;
    return true;
}

export function PostDairyRequestFromJSON(json: any): PostDairyRequest {
    return PostDairyRequestFromJSONTyped(json, false);
}

export function PostDairyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostDairyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'state': json['state'],
        'rainfallAbove600': json['rainfallAbove600'],
        'productionSystem': json['productionSystem'],
        'dairy': ((json['dairy'] as Array<any>).map(PostDairyRequestDairyInnerFromJSON)),
        'vegetation': ((json['vegetation'] as Array<any>).map(PostDairyRequestVegetationInnerFromJSON)),
    };
}

export function PostDairyRequestToJSON(json: any): PostDairyRequest {
    return PostDairyRequestToJSONTyped(json, false);
}

export function PostDairyRequestToJSONTyped(value?: PostDairyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'state': value['state'],
        'rainfallAbove600': value['rainfallAbove600'],
        'productionSystem': value['productionSystem'],
        'dairy': ((value['dairy'] as Array<any>).map(PostDairyRequestDairyInnerToJSON)),
        'vegetation': ((value['vegetation'] as Array<any>).map(PostDairyRequestVegetationInnerToJSON)),
    };
}

