/* tslint:disable */
/* eslint-disable */
/**
 * AIA Calculator API
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostBeefRequestBeefInnerClassesBullsGt1PurchasesInner } from './PostBeefRequestBeefInnerClassesBullsGt1PurchasesInner';
import {
    PostBeefRequestBeefInnerClassesBullsGt1PurchasesInnerFromJSON,
    PostBeefRequestBeefInnerClassesBullsGt1PurchasesInnerFromJSONTyped,
    PostBeefRequestBeefInnerClassesBullsGt1PurchasesInnerToJSON,
    PostBeefRequestBeefInnerClassesBullsGt1PurchasesInnerToJSONTyped,
} from './PostBeefRequestBeefInnerClassesBullsGt1PurchasesInner';
import type { PostBeefRequestBeefInnerClassesBullsGt1Autumn } from './PostBeefRequestBeefInnerClassesBullsGt1Autumn';
import {
    PostBeefRequestBeefInnerClassesBullsGt1AutumnFromJSON,
    PostBeefRequestBeefInnerClassesBullsGt1AutumnFromJSONTyped,
    PostBeefRequestBeefInnerClassesBullsGt1AutumnToJSON,
    PostBeefRequestBeefInnerClassesBullsGt1AutumnToJSONTyped,
} from './PostBeefRequestBeefInnerClassesBullsGt1Autumn';

/**
 * Traded cows whose age is greater than 2 years old
 * @export
 * @interface PostBeefRequestBeefInnerClassesCowsGt2Traded
 */
export interface PostBeefRequestBeefInnerClassesCowsGt2Traded {
    /**
     * 
     * @type {PostBeefRequestBeefInnerClassesBullsGt1Autumn}
     * @memberof PostBeefRequestBeefInnerClassesCowsGt2Traded
     */
    autumn: PostBeefRequestBeefInnerClassesBullsGt1Autumn;
    /**
     * 
     * @type {PostBeefRequestBeefInnerClassesBullsGt1Autumn}
     * @memberof PostBeefRequestBeefInnerClassesCowsGt2Traded
     */
    winter: PostBeefRequestBeefInnerClassesBullsGt1Autumn;
    /**
     * 
     * @type {PostBeefRequestBeefInnerClassesBullsGt1Autumn}
     * @memberof PostBeefRequestBeefInnerClassesCowsGt2Traded
     */
    spring: PostBeefRequestBeefInnerClassesBullsGt1Autumn;
    /**
     * 
     * @type {PostBeefRequestBeefInnerClassesBullsGt1Autumn}
     * @memberof PostBeefRequestBeefInnerClassesCowsGt2Traded
     */
    summer: PostBeefRequestBeefInnerClassesBullsGt1Autumn;
    /**
     * Number of animals sold (head)
     * @type {number}
     * @memberof PostBeefRequestBeefInnerClassesCowsGt2Traded
     */
    headSold: number;
    /**
     * Weight at sale, in liveweight kg/head (kilogram per head)
     * @type {number}
     * @memberof PostBeefRequestBeefInnerClassesCowsGt2Traded
     */
    saleWeight: number;
    /**
     * 
     * @type {Array<PostBeefRequestBeefInnerClassesBullsGt1PurchasesInner>}
     * @memberof PostBeefRequestBeefInnerClassesCowsGt2Traded
     */
    purchases?: Array<PostBeefRequestBeefInnerClassesBullsGt1PurchasesInner>;
}

/**
 * Check if a given object implements the PostBeefRequestBeefInnerClassesCowsGt2Traded interface.
 */
export function instanceOfPostBeefRequestBeefInnerClassesCowsGt2Traded(value: object): value is PostBeefRequestBeefInnerClassesCowsGt2Traded {
    if (!('autumn' in value) || value['autumn'] === undefined) return false;
    if (!('winter' in value) || value['winter'] === undefined) return false;
    if (!('spring' in value) || value['spring'] === undefined) return false;
    if (!('summer' in value) || value['summer'] === undefined) return false;
    if (!('headSold' in value) || value['headSold'] === undefined) return false;
    if (!('saleWeight' in value) || value['saleWeight'] === undefined) return false;
    return true;
}

export function PostBeefRequestBeefInnerClassesCowsGt2TradedFromJSON(json: any): PostBeefRequestBeefInnerClassesCowsGt2Traded {
    return PostBeefRequestBeefInnerClassesCowsGt2TradedFromJSONTyped(json, false);
}

export function PostBeefRequestBeefInnerClassesCowsGt2TradedFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostBeefRequestBeefInnerClassesCowsGt2Traded {
    if (json == null) {
        return json;
    }
    return {
        
        'autumn': PostBeefRequestBeefInnerClassesBullsGt1AutumnFromJSON(json['autumn']),
        'winter': PostBeefRequestBeefInnerClassesBullsGt1AutumnFromJSON(json['winter']),
        'spring': PostBeefRequestBeefInnerClassesBullsGt1AutumnFromJSON(json['spring']),
        'summer': PostBeefRequestBeefInnerClassesBullsGt1AutumnFromJSON(json['summer']),
        'headSold': json['headSold'],
        'saleWeight': json['saleWeight'],
        'purchases': json['purchases'] == null ? undefined : ((json['purchases'] as Array<any>).map(PostBeefRequestBeefInnerClassesBullsGt1PurchasesInnerFromJSON)),
    };
}

export function PostBeefRequestBeefInnerClassesCowsGt2TradedToJSON(json: any): PostBeefRequestBeefInnerClassesCowsGt2Traded {
    return PostBeefRequestBeefInnerClassesCowsGt2TradedToJSONTyped(json, false);
}

export function PostBeefRequestBeefInnerClassesCowsGt2TradedToJSONTyped(value?: PostBeefRequestBeefInnerClassesCowsGt2Traded | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'autumn': PostBeefRequestBeefInnerClassesBullsGt1AutumnToJSON(value['autumn']),
        'winter': PostBeefRequestBeefInnerClassesBullsGt1AutumnToJSON(value['winter']),
        'spring': PostBeefRequestBeefInnerClassesBullsGt1AutumnToJSON(value['spring']),
        'summer': PostBeefRequestBeefInnerClassesBullsGt1AutumnToJSON(value['summer']),
        'headSold': value['headSold'],
        'saleWeight': value['saleWeight'],
        'purchases': value['purchases'] == null ? undefined : ((value['purchases'] as Array<any>).map(PostBeefRequestBeefInnerClassesBullsGt1PurchasesInnerToJSON)),
    };
}

