/* tslint:disable */
/* eslint-disable */
/**
 * AIA Calculator API
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostBuffaloRequestBuffalosInnerClassesBullsAutumn } from './PostBuffaloRequestBuffalosInnerClassesBullsAutumn';
import {
    PostBuffaloRequestBuffalosInnerClassesBullsAutumnFromJSON,
    PostBuffaloRequestBuffalosInnerClassesBullsAutumnFromJSONTyped,
    PostBuffaloRequestBuffalosInnerClassesBullsAutumnToJSON,
    PostBuffaloRequestBuffalosInnerClassesBullsAutumnToJSONTyped,
} from './PostBuffaloRequestBuffalosInnerClassesBullsAutumn';
import type { PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInner } from './PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInner';
import {
    PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInnerFromJSON,
    PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInnerFromJSONTyped,
    PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInnerToJSON,
    PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInnerToJSONTyped,
} from './PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInner';

/**
 * Cows
 * @export
 * @interface PostBuffaloRequestBuffalosInnerClassesCows
 */
export interface PostBuffaloRequestBuffalosInnerClassesCows {
    /**
     * 
     * @type {PostBuffaloRequestBuffalosInnerClassesBullsAutumn}
     * @memberof PostBuffaloRequestBuffalosInnerClassesCows
     */
    autumn: PostBuffaloRequestBuffalosInnerClassesBullsAutumn;
    /**
     * 
     * @type {PostBuffaloRequestBuffalosInnerClassesBullsAutumn}
     * @memberof PostBuffaloRequestBuffalosInnerClassesCows
     */
    winter: PostBuffaloRequestBuffalosInnerClassesBullsAutumn;
    /**
     * 
     * @type {PostBuffaloRequestBuffalosInnerClassesBullsAutumn}
     * @memberof PostBuffaloRequestBuffalosInnerClassesCows
     */
    spring: PostBuffaloRequestBuffalosInnerClassesBullsAutumn;
    /**
     * 
     * @type {PostBuffaloRequestBuffalosInnerClassesBullsAutumn}
     * @memberof PostBuffaloRequestBuffalosInnerClassesCows
     */
    summer: PostBuffaloRequestBuffalosInnerClassesBullsAutumn;
    /**
     * Number of animals sold (head)
     * @type {number}
     * @memberof PostBuffaloRequestBuffalosInnerClassesCows
     */
    headSold: number;
    /**
     * Weight at sale, in liveweight kg/head (kilogram per head)
     * @type {number}
     * @memberof PostBuffaloRequestBuffalosInnerClassesCows
     */
    saleWeight: number;
    /**
     * 
     * @type {Array<PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInner>}
     * @memberof PostBuffaloRequestBuffalosInnerClassesCows
     */
    purchases?: Array<PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInner>;
}

/**
 * Check if a given object implements the PostBuffaloRequestBuffalosInnerClassesCows interface.
 */
export function instanceOfPostBuffaloRequestBuffalosInnerClassesCows(value: object): value is PostBuffaloRequestBuffalosInnerClassesCows {
    if (!('autumn' in value) || value['autumn'] === undefined) return false;
    if (!('winter' in value) || value['winter'] === undefined) return false;
    if (!('spring' in value) || value['spring'] === undefined) return false;
    if (!('summer' in value) || value['summer'] === undefined) return false;
    if (!('headSold' in value) || value['headSold'] === undefined) return false;
    if (!('saleWeight' in value) || value['saleWeight'] === undefined) return false;
    return true;
}

export function PostBuffaloRequestBuffalosInnerClassesCowsFromJSON(json: any): PostBuffaloRequestBuffalosInnerClassesCows {
    return PostBuffaloRequestBuffalosInnerClassesCowsFromJSONTyped(json, false);
}

export function PostBuffaloRequestBuffalosInnerClassesCowsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostBuffaloRequestBuffalosInnerClassesCows {
    if (json == null) {
        return json;
    }
    return {
        
        'autumn': PostBuffaloRequestBuffalosInnerClassesBullsAutumnFromJSON(json['autumn']),
        'winter': PostBuffaloRequestBuffalosInnerClassesBullsAutumnFromJSON(json['winter']),
        'spring': PostBuffaloRequestBuffalosInnerClassesBullsAutumnFromJSON(json['spring']),
        'summer': PostBuffaloRequestBuffalosInnerClassesBullsAutumnFromJSON(json['summer']),
        'headSold': json['headSold'],
        'saleWeight': json['saleWeight'],
        'purchases': json['purchases'] == null ? undefined : ((json['purchases'] as Array<any>).map(PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInnerFromJSON)),
    };
}

export function PostBuffaloRequestBuffalosInnerClassesCowsToJSON(json: any): PostBuffaloRequestBuffalosInnerClassesCows {
    return PostBuffaloRequestBuffalosInnerClassesCowsToJSONTyped(json, false);
}

export function PostBuffaloRequestBuffalosInnerClassesCowsToJSONTyped(value?: PostBuffaloRequestBuffalosInnerClassesCows | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'autumn': PostBuffaloRequestBuffalosInnerClassesBullsAutumnToJSON(value['autumn']),
        'winter': PostBuffaloRequestBuffalosInnerClassesBullsAutumnToJSON(value['winter']),
        'spring': PostBuffaloRequestBuffalosInnerClassesBullsAutumnToJSON(value['spring']),
        'summer': PostBuffaloRequestBuffalosInnerClassesBullsAutumnToJSON(value['summer']),
        'headSold': value['headSold'],
        'saleWeight': value['saleWeight'],
        'purchases': value['purchases'] == null ? undefined : ((value['purchases'] as Array<any>).map(PostBuffaloRequestBuffalosInnerClassesBullsPurchasesInnerToJSON)),
    };
}

