# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.post_goat_request_goats_inner_classes_breeding_does_nannies import PostGoatRequestGoatsInnerClassesBreedingDoesNannies
from openapi_client.models.post_goat_request_goats_inner_classes_bucks_billy import PostGoatRequestGoatsInnerClassesBucksBilly
from openapi_client.models.post_goat_request_goats_inner_classes_kids import PostGoatRequestGoatsInnerClassesKids
from openapi_client.models.post_goat_request_goats_inner_classes_maiden_breeding_does_nannies import PostGoatRequestGoatsInnerClassesMaidenBreedingDoesNannies
from openapi_client.models.post_goat_request_goats_inner_classes_other_does_culled_females import PostGoatRequestGoatsInnerClassesOtherDoesCulledFemales
from openapi_client.models.post_goat_request_goats_inner_classes_trade_breeding_does_nannies import PostGoatRequestGoatsInnerClassesTradeBreedingDoesNannies
from openapi_client.models.post_goat_request_goats_inner_classes_trade_bucks import PostGoatRequestGoatsInnerClassesTradeBucks
from openapi_client.models.post_goat_request_goats_inner_classes_trade_does import PostGoatRequestGoatsInnerClassesTradeDoes
from openapi_client.models.post_goat_request_goats_inner_classes_trade_kids import PostGoatRequestGoatsInnerClassesTradeKids
from openapi_client.models.post_goat_request_goats_inner_classes_trade_maiden_breeding_does_nannies import PostGoatRequestGoatsInnerClassesTradeMaidenBreedingDoesNannies
from openapi_client.models.post_goat_request_goats_inner_classes_trade_other_does_culled_females import PostGoatRequestGoatsInnerClassesTradeOtherDoesCulledFemales
from openapi_client.models.post_goat_request_goats_inner_classes_trade_wethers import PostGoatRequestGoatsInnerClassesTradeWethers
from openapi_client.models.post_goat_request_goats_inner_classes_wethers import PostGoatRequestGoatsInnerClassesWethers
from typing import Optional, Set
from typing_extensions import Self

class PostGoatRequestGoatsInnerClasses(BaseModel):
    """
    Goat classes of different types
    """ # noqa: E501
    bucks_billy: Optional[PostGoatRequestGoatsInnerClassesBucksBilly] = Field(default=None, alias="bucksBilly")
    trade_bucks: Optional[PostGoatRequestGoatsInnerClassesTradeBucks] = Field(default=None, alias="tradeBucks")
    wethers: Optional[PostGoatRequestGoatsInnerClassesWethers] = None
    trade_wethers: Optional[PostGoatRequestGoatsInnerClassesTradeWethers] = Field(default=None, alias="tradeWethers")
    maiden_breeding_does_nannies: Optional[PostGoatRequestGoatsInnerClassesMaidenBreedingDoesNannies] = Field(default=None, alias="maidenBreedingDoesNannies")
    trade_maiden_breeding_does_nannies: Optional[PostGoatRequestGoatsInnerClassesTradeMaidenBreedingDoesNannies] = Field(default=None, alias="tradeMaidenBreedingDoesNannies")
    breeding_does_nannies: Optional[PostGoatRequestGoatsInnerClassesBreedingDoesNannies] = Field(default=None, alias="breedingDoesNannies")
    trade_breeding_does_nannies: Optional[PostGoatRequestGoatsInnerClassesTradeBreedingDoesNannies] = Field(default=None, alias="tradeBreedingDoesNannies")
    other_does_culled_females: Optional[PostGoatRequestGoatsInnerClassesOtherDoesCulledFemales] = Field(default=None, alias="otherDoesCulledFemales")
    trade_other_does_culled_females: Optional[PostGoatRequestGoatsInnerClassesTradeOtherDoesCulledFemales] = Field(default=None, alias="tradeOtherDoesCulledFemales")
    kids: Optional[PostGoatRequestGoatsInnerClassesKids] = None
    trade_kids: Optional[PostGoatRequestGoatsInnerClassesTradeKids] = Field(default=None, alias="tradeKids")
    trade_does: Optional[PostGoatRequestGoatsInnerClassesTradeDoes] = Field(default=None, alias="tradeDoes")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["bucksBilly", "tradeBucks", "wethers", "tradeWethers", "maidenBreedingDoesNannies", "tradeMaidenBreedingDoesNannies", "breedingDoesNannies", "tradeBreedingDoesNannies", "otherDoesCulledFemales", "tradeOtherDoesCulledFemales", "kids", "tradeKids", "tradeDoes"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostGoatRequestGoatsInnerClasses from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of bucks_billy
        if self.bucks_billy:
            _dict['bucksBilly'] = self.bucks_billy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of trade_bucks
        if self.trade_bucks:
            _dict['tradeBucks'] = self.trade_bucks.to_dict()
        # override the default output from pydantic by calling `to_dict()` of wethers
        if self.wethers:
            _dict['wethers'] = self.wethers.to_dict()
        # override the default output from pydantic by calling `to_dict()` of trade_wethers
        if self.trade_wethers:
            _dict['tradeWethers'] = self.trade_wethers.to_dict()
        # override the default output from pydantic by calling `to_dict()` of maiden_breeding_does_nannies
        if self.maiden_breeding_does_nannies:
            _dict['maidenBreedingDoesNannies'] = self.maiden_breeding_does_nannies.to_dict()
        # override the default output from pydantic by calling `to_dict()` of trade_maiden_breeding_does_nannies
        if self.trade_maiden_breeding_does_nannies:
            _dict['tradeMaidenBreedingDoesNannies'] = self.trade_maiden_breeding_does_nannies.to_dict()
        # override the default output from pydantic by calling `to_dict()` of breeding_does_nannies
        if self.breeding_does_nannies:
            _dict['breedingDoesNannies'] = self.breeding_does_nannies.to_dict()
        # override the default output from pydantic by calling `to_dict()` of trade_breeding_does_nannies
        if self.trade_breeding_does_nannies:
            _dict['tradeBreedingDoesNannies'] = self.trade_breeding_does_nannies.to_dict()
        # override the default output from pydantic by calling `to_dict()` of other_does_culled_females
        if self.other_does_culled_females:
            _dict['otherDoesCulledFemales'] = self.other_does_culled_females.to_dict()
        # override the default output from pydantic by calling `to_dict()` of trade_other_does_culled_females
        if self.trade_other_does_culled_females:
            _dict['tradeOtherDoesCulledFemales'] = self.trade_other_does_culled_females.to_dict()
        # override the default output from pydantic by calling `to_dict()` of kids
        if self.kids:
            _dict['kids'] = self.kids.to_dict()
        # override the default output from pydantic by calling `to_dict()` of trade_kids
        if self.trade_kids:
            _dict['tradeKids'] = self.trade_kids.to_dict()
        # override the default output from pydantic by calling `to_dict()` of trade_does
        if self.trade_does:
            _dict['tradeDoes'] = self.trade_does.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostGoatRequestGoatsInnerClasses from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bucksBilly": PostGoatRequestGoatsInnerClassesBucksBilly.from_dict(obj["bucksBilly"]) if obj.get("bucksBilly") is not None else None,
            "tradeBucks": PostGoatRequestGoatsInnerClassesTradeBucks.from_dict(obj["tradeBucks"]) if obj.get("tradeBucks") is not None else None,
            "wethers": PostGoatRequestGoatsInnerClassesWethers.from_dict(obj["wethers"]) if obj.get("wethers") is not None else None,
            "tradeWethers": PostGoatRequestGoatsInnerClassesTradeWethers.from_dict(obj["tradeWethers"]) if obj.get("tradeWethers") is not None else None,
            "maidenBreedingDoesNannies": PostGoatRequestGoatsInnerClassesMaidenBreedingDoesNannies.from_dict(obj["maidenBreedingDoesNannies"]) if obj.get("maidenBreedingDoesNannies") is not None else None,
            "tradeMaidenBreedingDoesNannies": PostGoatRequestGoatsInnerClassesTradeMaidenBreedingDoesNannies.from_dict(obj["tradeMaidenBreedingDoesNannies"]) if obj.get("tradeMaidenBreedingDoesNannies") is not None else None,
            "breedingDoesNannies": PostGoatRequestGoatsInnerClassesBreedingDoesNannies.from_dict(obj["breedingDoesNannies"]) if obj.get("breedingDoesNannies") is not None else None,
            "tradeBreedingDoesNannies": PostGoatRequestGoatsInnerClassesTradeBreedingDoesNannies.from_dict(obj["tradeBreedingDoesNannies"]) if obj.get("tradeBreedingDoesNannies") is not None else None,
            "otherDoesCulledFemales": PostGoatRequestGoatsInnerClassesOtherDoesCulledFemales.from_dict(obj["otherDoesCulledFemales"]) if obj.get("otherDoesCulledFemales") is not None else None,
            "tradeOtherDoesCulledFemales": PostGoatRequestGoatsInnerClassesTradeOtherDoesCulledFemales.from_dict(obj["tradeOtherDoesCulledFemales"]) if obj.get("tradeOtherDoesCulledFemales") is not None else None,
            "kids": PostGoatRequestGoatsInnerClassesKids.from_dict(obj["kids"]) if obj.get("kids") is not None else None,
            "tradeKids": PostGoatRequestGoatsInnerClassesTradeKids.from_dict(obj["tradeKids"]) if obj.get("tradeKids") is not None else None,
            "tradeDoes": PostGoatRequestGoatsInnerClassesTradeDoes.from_dict(obj["tradeDoes"]) if obj.get("tradeDoes") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


