# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from openapi_client.models.post_aquaculture_request_enterprises_inner_fluid_waste_inner import PostAquacultureRequestEnterprisesInnerFluidWasteInner
from openapi_client.models.post_aquaculture_request_enterprises_inner_fuel import PostAquacultureRequestEnterprisesInnerFuel
from openapi_client.models.post_aquaculture_request_enterprises_inner_solid_waste import PostAquacultureRequestEnterprisesInnerSolidWaste
from openapi_client.models.post_horticulture_request_crops_inner_refrigerants_inner import PostHorticultureRequestCropsInnerRefrigerantsInner
from openapi_client.models.post_processing_request_products_inner_product import PostProcessingRequestProductsInnerProduct
from typing import Optional, Set
from typing_extensions import Self

class PostProcessingRequestProductsInner(BaseModel):
    """
    Input data required for processing a specific product
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Unique identifier for this activity")
    product: PostProcessingRequestProductsInnerProduct
    electricity_renewable: Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]] = Field(description="Percent of total electricity usage that is drawn from renewable sources, between 0 and 1. Unused if `electricitySource` is `Renewable`", alias="electricityRenewable")
    electricity_use: Union[StrictFloat, StrictInt] = Field(description="Electricity use in KWh (kilowatt hours)", alias="electricityUse")
    electricity_source: StrictStr = Field(description="Source of electricity", alias="electricitySource")
    fuel: PostAquacultureRequestEnterprisesInnerFuel
    refrigerants: List[PostHorticultureRequestCropsInnerRefrigerantsInner] = Field(description="Refrigerant type")
    fluid_waste: List[PostAquacultureRequestEnterprisesInnerFluidWasteInner] = Field(description="Amount of fluid waste, in kL (kilolitres)", alias="fluidWaste")
    solid_waste: PostAquacultureRequestEnterprisesInnerSolidWaste = Field(alias="solidWaste")
    purchased_co2: Union[StrictFloat, StrictInt] = Field(description="Quantity of CO2 purchased, in kg CO2", alias="purchasedCO2")
    carbon_offsets: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Carbon offsets purchased, in t CO2. Offsetting 2 t CO2 would be 2.0 (not -2.0)", alias="carbonOffsets")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "product", "electricityRenewable", "electricityUse", "electricitySource", "fuel", "refrigerants", "fluidWaste", "solidWaste", "purchasedCO2", "carbonOffsets"]

    @field_validator('electricity_source')
    def electricity_source_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['State Grid', 'Renewable']):
            raise ValueError("must be one of enum values ('State Grid', 'Renewable')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostProcessingRequestProductsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of product
        if self.product:
            _dict['product'] = self.product.to_dict()
        # override the default output from pydantic by calling `to_dict()` of fuel
        if self.fuel:
            _dict['fuel'] = self.fuel.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in refrigerants (list)
        _items = []
        if self.refrigerants:
            for _item_refrigerants in self.refrigerants:
                if _item_refrigerants:
                    _items.append(_item_refrigerants.to_dict())
            _dict['refrigerants'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in fluid_waste (list)
        _items = []
        if self.fluid_waste:
            for _item_fluid_waste in self.fluid_waste:
                if _item_fluid_waste:
                    _items.append(_item_fluid_waste.to_dict())
            _dict['fluidWaste'] = _items
        # override the default output from pydantic by calling `to_dict()` of solid_waste
        if self.solid_waste:
            _dict['solidWaste'] = self.solid_waste.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostProcessingRequestProductsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "product": PostProcessingRequestProductsInnerProduct.from_dict(obj["product"]) if obj.get("product") is not None else None,
            "electricityRenewable": obj.get("electricityRenewable"),
            "electricityUse": obj.get("electricityUse"),
            "electricitySource": obj.get("electricitySource"),
            "fuel": PostAquacultureRequestEnterprisesInnerFuel.from_dict(obj["fuel"]) if obj.get("fuel") is not None else None,
            "refrigerants": [PostHorticultureRequestCropsInnerRefrigerantsInner.from_dict(_item) for _item in obj["refrigerants"]] if obj.get("refrigerants") is not None else None,
            "fluidWaste": [PostAquacultureRequestEnterprisesInnerFluidWasteInner.from_dict(_item) for _item in obj["fluidWaste"]] if obj.get("fluidWaste") is not None else None,
            "solidWaste": PostAquacultureRequestEnterprisesInnerSolidWaste.from_dict(obj["solidWaste"]) if obj.get("solidWaste") is not None else None,
            "purchasedCO2": obj.get("purchasedCO2"),
            "carbonOffsets": obj.get("carbonOffsets")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


