# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self

class PostGoat200ResponseIntensities(BaseModel):
    """
    PostGoat200ResponseIntensities
    """ # noqa: E501
    amount_meat_produced: Union[StrictFloat, StrictInt] = Field(description="Amount of goat meat produced in kg liveweight", alias="amountMeatProduced")
    amount_wool_produced: Union[StrictFloat, StrictInt] = Field(description="Amount of wool produced in kg greasy", alias="amountWoolProduced")
    goat_meat_breeding_including_sequestration: Union[StrictFloat, StrictInt] = Field(description="Goat meat (breeding herd) including carbon sequestration, in kg-CO2e/kg liveweight", alias="goatMeatBreedingIncludingSequestration")
    goat_meat_breeding_excluding_sequestration: Union[StrictFloat, StrictInt] = Field(description="Goat meat (breeding herd) excluding carbon sequestration, in kg-CO2e/kg liveweight", alias="goatMeatBreedingExcludingSequestration")
    wool_including_sequestration: Union[StrictFloat, StrictInt] = Field(description="Wool production including carbon sequestration, in kg-CO2e/kg greasy", alias="woolIncludingSequestration")
    wool_excluding_sequestration: Union[StrictFloat, StrictInt] = Field(description="Wool production excluding carbon sequestration, in kg-CO2e/kg greasy", alias="woolExcludingSequestration")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["amountMeatProduced", "amountWoolProduced", "goatMeatBreedingIncludingSequestration", "goatMeatBreedingExcludingSequestration", "woolIncludingSequestration", "woolExcludingSequestration"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostGoat200ResponseIntensities from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostGoat200ResponseIntensities from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "amountMeatProduced": obj.get("amountMeatProduced"),
            "amountWoolProduced": obj.get("amountWoolProduced"),
            "goatMeatBreedingIncludingSequestration": obj.get("goatMeatBreedingIncludingSequestration"),
            "goatMeatBreedingExcludingSequestration": obj.get("goatMeatBreedingExcludingSequestration"),
            "woolIncludingSequestration": obj.get("woolIncludingSequestration"),
            "woolExcludingSequestration": obj.get("woolExcludingSequestration")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


