# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from openapi_client.models.post_beef_request_beef_inner_fertiliser import PostBeefRequestBeefInnerFertiliser
from openapi_client.models.post_dairy_request_dairy_inner_areas import PostDairyRequestDairyInnerAreas
from openapi_client.models.post_dairy_request_dairy_inner_classes import PostDairyRequestDairyInnerClasses
from openapi_client.models.post_dairy_request_dairy_inner_manure_management_milking_cows import PostDairyRequestDairyInnerManureManagementMilkingCows
from openapi_client.models.post_dairy_request_dairy_inner_seasonal_fertiliser import PostDairyRequestDairyInnerSeasonalFertiliser
from typing import Optional, Set
from typing_extensions import Self

class PostDairyRequestDairyInner(BaseModel):
    """
    PostDairyRequestDairyInner
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Unique identifier for this activity")
    classes: PostDairyRequestDairyInnerClasses
    limestone: Union[StrictFloat, StrictInt] = Field(description="Lime applied in tonnes")
    limestone_fraction: Union[StrictFloat, StrictInt] = Field(description="Fraction of lime as limestone vs dolomite, between 0 and 1", alias="limestoneFraction")
    fertiliser: PostBeefRequestBeefInnerFertiliser
    seasonal_fertiliser: PostDairyRequestDairyInnerSeasonalFertiliser = Field(alias="seasonalFertiliser")
    areas: PostDairyRequestDairyInnerAreas
    diesel: Union[StrictFloat, StrictInt] = Field(description="Diesel usage in L (litres)")
    petrol: Union[StrictFloat, StrictInt] = Field(description="Petrol usage in L (litres)")
    lpg: Union[StrictFloat, StrictInt] = Field(description="LPG Fuel usage in L (litres)")
    electricity_renewable: Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]] = Field(description="Percent of total electricity usage that is drawn from renewable sources, between 0 and 1. Unused if `electricitySource` is `Renewable`", alias="electricityRenewable")
    electricity_use: Union[StrictFloat, StrictInt] = Field(description="Electricity use in KWh (kilowatt hours)", alias="electricityUse")
    grain_feed: Union[StrictFloat, StrictInt] = Field(description="Grain purchased for cattle feed in tonnes", alias="grainFeed")
    hay_feed: Union[StrictFloat, StrictInt] = Field(description="Hay purchased for cattle feed in tonnes", alias="hayFeed")
    cottonseed_feed: Union[StrictFloat, StrictInt] = Field(description="Cotton seed purchased for cattle feed in tonnes", alias="cottonseedFeed")
    herbicide: Union[StrictFloat, StrictInt] = Field(description="Total amount of active ingredients of from herbicide (Paraquat, Diquat, Glyphosate) in kg (kilograms)")
    herbicide_other: Union[StrictFloat, StrictInt] = Field(description="Total amount of active ingredients of from other herbicides in kg (kilograms)", alias="herbicideOther")
    manure_management_milking_cows: PostDairyRequestDairyInnerManureManagementMilkingCows = Field(alias="manureManagementMilkingCows")
    manure_management_other_dairy_cows: PostDairyRequestDairyInnerManureManagementMilkingCows = Field(alias="manureManagementOtherDairyCows")
    emissions_allocation_to_red_meat_production: Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]] = Field(description="Allocation as a fraction, from 0 to 1", alias="emissionsAllocationToRedMeatProduction")
    truck_type: StrictStr = Field(description="Type of truck used for cattle transport", alias="truckType")
    distance_cattle_transported: Union[StrictFloat, StrictInt] = Field(description="Distance cattle are transported between farms, in km (kilometres)", alias="distanceCattleTransported")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "classes", "limestone", "limestoneFraction", "fertiliser", "seasonalFertiliser", "areas", "diesel", "petrol", "lpg", "electricityRenewable", "electricityUse", "grainFeed", "hayFeed", "cottonseedFeed", "herbicide", "herbicideOther", "manureManagementMilkingCows", "manureManagementOtherDairyCows", "emissionsAllocationToRedMeatProduction", "truckType", "distanceCattleTransported"]

    @field_validator('truck_type')
    def truck_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['4 Deck Trailer', '6 Deck Trailer', 'B-Double']):
            raise ValueError("must be one of enum values ('4 Deck Trailer', '6 Deck Trailer', 'B-Double')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostDairyRequestDairyInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of classes
        if self.classes:
            _dict['classes'] = self.classes.to_dict()
        # override the default output from pydantic by calling `to_dict()` of fertiliser
        if self.fertiliser:
            _dict['fertiliser'] = self.fertiliser.to_dict()
        # override the default output from pydantic by calling `to_dict()` of seasonal_fertiliser
        if self.seasonal_fertiliser:
            _dict['seasonalFertiliser'] = self.seasonal_fertiliser.to_dict()
        # override the default output from pydantic by calling `to_dict()` of areas
        if self.areas:
            _dict['areas'] = self.areas.to_dict()
        # override the default output from pydantic by calling `to_dict()` of manure_management_milking_cows
        if self.manure_management_milking_cows:
            _dict['manureManagementMilkingCows'] = self.manure_management_milking_cows.to_dict()
        # override the default output from pydantic by calling `to_dict()` of manure_management_other_dairy_cows
        if self.manure_management_other_dairy_cows:
            _dict['manureManagementOtherDairyCows'] = self.manure_management_other_dairy_cows.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostDairyRequestDairyInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "classes": PostDairyRequestDairyInnerClasses.from_dict(obj["classes"]) if obj.get("classes") is not None else None,
            "limestone": obj.get("limestone"),
            "limestoneFraction": obj.get("limestoneFraction"),
            "fertiliser": PostBeefRequestBeefInnerFertiliser.from_dict(obj["fertiliser"]) if obj.get("fertiliser") is not None else None,
            "seasonalFertiliser": PostDairyRequestDairyInnerSeasonalFertiliser.from_dict(obj["seasonalFertiliser"]) if obj.get("seasonalFertiliser") is not None else None,
            "areas": PostDairyRequestDairyInnerAreas.from_dict(obj["areas"]) if obj.get("areas") is not None else None,
            "diesel": obj.get("diesel"),
            "petrol": obj.get("petrol"),
            "lpg": obj.get("lpg"),
            "electricityRenewable": obj.get("electricityRenewable"),
            "electricityUse": obj.get("electricityUse"),
            "grainFeed": obj.get("grainFeed"),
            "hayFeed": obj.get("hayFeed"),
            "cottonseedFeed": obj.get("cottonseedFeed"),
            "herbicide": obj.get("herbicide"),
            "herbicideOther": obj.get("herbicideOther"),
            "manureManagementMilkingCows": PostDairyRequestDairyInnerManureManagementMilkingCows.from_dict(obj["manureManagementMilkingCows"]) if obj.get("manureManagementMilkingCows") is not None else None,
            "manureManagementOtherDairyCows": PostDairyRequestDairyInnerManureManagementMilkingCows.from_dict(obj["manureManagementOtherDairyCows"]) if obj.get("manureManagementOtherDairyCows") is not None else None,
            "emissionsAllocationToRedMeatProduction": obj.get("emissionsAllocationToRedMeatProduction"),
            "truckType": obj.get("truckType"),
            "distanceCattleTransported": obj.get("distanceCattleTransported")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


