# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self

class PostPoultry200ResponseIntensities(BaseModel):
    """
    PostPoultry200ResponseIntensities
    """ # noqa: E501
    poultry_meat_including_sequestration: Union[StrictFloat, StrictInt] = Field(description="Poultry meat including carbon sequestration, in kg-CO2e/kg liveweight", alias="poultryMeatIncludingSequestration")
    poultry_meat_excluding_sequestration: Union[StrictFloat, StrictInt] = Field(description="Poultry meat excluding carbon sequestration, in kg-CO2e/kg liveweight", alias="poultryMeatExcludingSequestration")
    poultry_eggs_including_sequestration: Union[StrictFloat, StrictInt] = Field(description="Poultry eggs including carbon sequestration, in kg-CO2e/kg liveweight", alias="poultryEggsIncludingSequestration")
    poultry_eggs_excluding_sequestration: Union[StrictFloat, StrictInt] = Field(description="Poultry eggs excluding carbon sequestration, in kg-CO2e/kg liveweight", alias="poultryEggsExcludingSequestration")
    meat_produced_kg: Union[StrictFloat, StrictInt] = Field(description="Poultry meat produced in kg", alias="meatProducedKg")
    eggs_produced_kg: Union[StrictFloat, StrictInt] = Field(description="Amount of eggs produced, in kg", alias="eggsProducedKg")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["poultryMeatIncludingSequestration", "poultryMeatExcludingSequestration", "poultryEggsIncludingSequestration", "poultryEggsExcludingSequestration", "meatProducedKg", "eggsProducedKg"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostPoultry200ResponseIntensities from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostPoultry200ResponseIntensities from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "poultryMeatIncludingSequestration": obj.get("poultryMeatIncludingSequestration"),
            "poultryMeatExcludingSequestration": obj.get("poultryMeatExcludingSequestration"),
            "poultryEggsIncludingSequestration": obj.get("poultryEggsIncludingSequestration"),
            "poultryEggsExcludingSequestration": obj.get("poultryEggsExcludingSequestration"),
            "meatProducedKg": obj.get("meatProducedKg"),
            "eggsProducedKg": obj.get("eggsProducedKg")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


