# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Union
from openapi_client.models.post_poultry_request_broilers_inner_groups_inner_feed_inner import PostPoultryRequestBroilersInnerGroupsInnerFeedInner
from openapi_client.models.post_poultry_request_broilers_inner_groups_inner_meat_chicken_growers import PostPoultryRequestBroilersInnerGroupsInnerMeatChickenGrowers
from typing import Optional, Set
from typing_extensions import Self

class PostPoultryRequestBroilersInnerGroupsInner(BaseModel):
    """
    Poultry broiler group
    """ # noqa: E501
    meat_chicken_growers: PostPoultryRequestBroilersInnerGroupsInnerMeatChickenGrowers = Field(alias="meatChickenGrowers")
    meat_chicken_layers: PostPoultryRequestBroilersInnerGroupsInnerMeatChickenGrowers = Field(alias="meatChickenLayers")
    meat_other: PostPoultryRequestBroilersInnerGroupsInnerMeatChickenGrowers = Field(alias="meatOther")
    feed: List[PostPoultryRequestBroilersInnerGroupsInnerFeedInner]
    custom_feed_purchased: Union[StrictFloat, StrictInt] = Field(description="Custom feed purchased, in tonnes", alias="customFeedPurchased")
    custom_feed_emission_intensity: Union[StrictFloat, StrictInt] = Field(description="Emissions intensity of custom feed in GHG (kg CO2-e/kg input)", alias="customFeedEmissionIntensity")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["meatChickenGrowers", "meatChickenLayers", "meatOther", "feed", "customFeedPurchased", "customFeedEmissionIntensity"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostPoultryRequestBroilersInnerGroupsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of meat_chicken_growers
        if self.meat_chicken_growers:
            _dict['meatChickenGrowers'] = self.meat_chicken_growers.to_dict()
        # override the default output from pydantic by calling `to_dict()` of meat_chicken_layers
        if self.meat_chicken_layers:
            _dict['meatChickenLayers'] = self.meat_chicken_layers.to_dict()
        # override the default output from pydantic by calling `to_dict()` of meat_other
        if self.meat_other:
            _dict['meatOther'] = self.meat_other.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in feed (list)
        _items = []
        if self.feed:
            for _item_feed in self.feed:
                if _item_feed:
                    _items.append(_item_feed.to_dict())
            _dict['feed'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostPoultryRequestBroilersInnerGroupsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "meatChickenGrowers": PostPoultryRequestBroilersInnerGroupsInnerMeatChickenGrowers.from_dict(obj["meatChickenGrowers"]) if obj.get("meatChickenGrowers") is not None else None,
            "meatChickenLayers": PostPoultryRequestBroilersInnerGroupsInnerMeatChickenGrowers.from_dict(obj["meatChickenLayers"]) if obj.get("meatChickenLayers") is not None else None,
            "meatOther": PostPoultryRequestBroilersInnerGroupsInnerMeatChickenGrowers.from_dict(obj["meatOther"]) if obj.get("meatOther") is not None else None,
            "feed": [PostPoultryRequestBroilersInnerGroupsInnerFeedInner.from_dict(_item) for _item in obj["feed"]] if obj.get("feed") is not None else None,
            "customFeedPurchased": obj.get("customFeedPurchased"),
            "customFeedEmissionIntensity": obj.get("customFeedEmissionIntensity")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


