# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self

class PostFeedlotRequestFeedlotsInnerGroupsInnerStaysInner(BaseModel):
    """
    A class of cattle with a specific feedlot stay duration
    """ # noqa: E501
    livestock: Union[StrictFloat, StrictInt] = Field(description="Number of animals (head)")
    stay_average_duration: Union[StrictFloat, StrictInt] = Field(description="Average stay length in feedlot, in days", alias="stayAverageDuration")
    liveweight: Union[StrictFloat, StrictInt] = Field(description="Average liveweight of animals in kg/head (kilogram per head)")
    dry_matter_digestibility: Union[StrictFloat, StrictInt] = Field(description="Percent dry matter digestibility of the feed eaten, from 0 to 100", alias="dryMatterDigestibility")
    crude_protein: Union[StrictFloat, StrictInt] = Field(description="Percent crude protein of the whole diet, from 0 to 100", alias="crudeProtein")
    nitrogen_retention: Union[StrictFloat, StrictInt] = Field(description="Percent nitrogen retention of intake, from 0 to 100", alias="nitrogenRetention")
    daily_intake: Union[StrictFloat, StrictInt] = Field(description="Daily intake of dry matter in kilograms per head per day", alias="dailyIntake")
    ndf: Union[StrictFloat, StrictInt] = Field(description="Percent Neutral detergent fibre (NDF) of intake, from 0 to 100")
    ether_extract: Union[StrictFloat, StrictInt] = Field(description="Percent ether extract of intake, from 0 to 100", alias="etherExtract")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["livestock", "stayAverageDuration", "liveweight", "dryMatterDigestibility", "crudeProtein", "nitrogenRetention", "dailyIntake", "ndf", "etherExtract"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostFeedlotRequestFeedlotsInnerGroupsInnerStaysInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostFeedlotRequestFeedlotsInnerGroupsInnerStaysInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "livestock": obj.get("livestock"),
            "stayAverageDuration": obj.get("stayAverageDuration"),
            "liveweight": obj.get("liveweight"),
            "dryMatterDigestibility": obj.get("dryMatterDigestibility"),
            "crudeProtein": obj.get("crudeProtein"),
            "nitrogenRetention": obj.get("nitrogenRetention"),
            "dailyIntake": obj.get("dailyIntake"),
            "ndf": obj.get("ndf"),
            "etherExtract": obj.get("etherExtract")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


